INSERT INTO flashcards (chapter, term, definition, is_default) VALUES
-- Chapter 1: The Modern State of Health and Fitness
(1, 'Evidence-based practice', 'Using scientific evidence, clinical experience, and client values to guide training decisions.', true),
(1, 'Integrated training', 'A comprehensive approach that combines all forms of training (flexibility, core, balance, reactive, resistance, cardio) in a progressive manner.', true),
(1, 'Kinetic chain', 'The concept that the human body is a linked system of interdependent segments (nervous, skeletal, and muscular systems) that work together to produce movement.', true),
(1, 'Deconditioned', 'A state of lost physical fitness, which may include decreased cardiovascular endurance, muscular strength, and flexibility.', true),
(1, 'Obesity', 'A condition of excess body fat; defined as a BMI of 30 or higher. Associated with increased risk of heart disease, diabetes, and musculoskeletal dysfunction.', true),
(1, 'Overweight', 'A BMI of 25 to 29.9, indicating body weight above normal standards relative to height.', true),
(1, 'Coronary heart disease', 'A condition caused by narrowing of coronary arteries due to plaque buildup (atherosclerosis). Leading cause of death in the United States.', true),
(1, 'Diabetes mellitus', 'A chronic metabolic disorder characterized by high blood glucose levels due to inadequate insulin production (Type 1) or insulin resistance (Type 2).', true),
(1, 'Physical activity', 'Any bodily movement produced by skeletal muscles that requires energy expenditure beyond resting levels.', true),
(1, 'Exercise', 'A type of physical activity that is planned, structured, repetitive, and performed with the goal of improving or maintaining physical fitness.', true),
(1, 'Muscular system', 'The system of tissues that provides movement of and within the body; one of the three systems comprising the kinetic chain.', true),
(1, 'Nervous system', 'The network of neurons that transmits signals between the brain and body; provides communication and coordination within the kinetic chain.', true),
(1, 'Skeletal system', 'The framework of bones and joints that provides structure, support, and protection; one of the three systems of the kinetic chain.', true),
(1, 'Risk factor', 'A characteristic or condition that increases the likelihood of developing a disease. Examples include physical inactivity, smoking, and poor nutrition.', true),
(1, 'Personal training', 'The profession of coaching individuals through exercise programs designed to improve health, fitness, and performance based on individual goals and needs.', true),
-- Chapter 2: Basic Exercise Science
(2, 'Agonist', 'The muscle that is the primary mover in a given exercise. Example: biceps during a bicep curl.', true),
(2, 'Antagonist', 'The muscle that opposes the primary mover. Example: triceps during a bicep curl.', true),
(2, 'Synergist', 'A muscle that assists the agonist in performing a movement.', true),
(2, 'Stabilizer', 'A muscle that supports a joint during movement, allowing the agonist to work effectively.', true),
(2, 'Golgi Tendon Organ (GTO)', 'A sensory receptor in tendons that senses changes in muscular tension. When stimulated, it causes the muscle to relax (autogenic inhibition).', true),
(2, 'Muscle spindle', 'A sensory receptor within muscle that detects changes in muscle length. When stimulated quickly, it causes a reflexive contraction.', true),
(2, 'Skeletal muscle', 'Voluntary, striated muscle tissue attached to bones via tendons. Responsible for producing movement and maintaining posture.', true),
(2, 'Smooth muscle', 'Involuntary, non-striated muscle found in the walls of blood vessels, the digestive tract, and other internal organs.', true),
(2, 'Cardiac muscle', 'Involuntary, striated muscle found only in the heart. Contracts rhythmically to pump blood throughout the body.', true),
(2, 'Motor unit', 'A motor neuron and all of the muscle fibers it innervates. The functional unit of the neuromuscular system.', true),
(2, 'Neuromuscular junction', 'The site where a motor neuron meets a muscle fiber. Acetylcholine is released here to stimulate muscle contraction.', true),
(2, 'Type I (slow-twitch) muscle fibers', 'Smaller, fatigue-resistant fibers that produce less force but are used for endurance activities. High in mitochondria and capillary density.', true),
(2, 'Type II (fast-twitch) muscle fibers', 'Larger fibers that produce more force and power but fatigue quickly. Used for high-intensity, short-duration activities like sprinting.', true),
(2, 'Proprioception', 'The body''s ability to sense its position and movement in space using sensory receptors in muscles, tendons, and joints.', true),
(2, 'Concentric contraction', 'A muscle action where the muscle shortens while producing force; the ''positive'' phase of a lift.', true),
(2, 'Eccentric contraction', 'A muscle action where the muscle lengthens while producing force; the ''negative'' or lowering phase of a lift.', true),
(2, 'Isometric contraction', 'A muscle action where force is produced without a change in muscle length. Example: holding a plank.', true),
(2, 'Sarcomere', 'The smallest functional unit of muscle contraction. Contains actin (thin) and myosin (thick) filaments that slide past each other to produce force.', true),
(2, 'Sliding filament theory', 'The theory explaining muscle contraction: myosin heads attach to actin filaments and pull them toward the center of the sarcomere, shortening the muscle.', true),
(2, 'All-or-nothing principle', 'A motor unit''s muscle fibers either contract fully or not at all when stimulated. Force is modulated by recruiting more or fewer motor units.', true),
-- Chapter 3: The Cardiorespiratory System
(3, 'Heart', 'A four-chambered muscular organ that pumps blood throughout the body. Right side handles pulmonary circulation; left side handles systemic circulation.', true),
(3, 'Stroke volume', 'The amount of blood pumped out of the left ventricle with each heartbeat. Increases with aerobic training.', true),
(3, 'Cardiac output', 'The total volume of blood pumped by the heart per minute. Calculated as heart rate x stroke volume.', true),
(3, 'VO2max', 'The maximum rate of oxygen consumption during maximal exercise. Considered the best measure of cardiorespiratory fitness.', true),
(3, 'Heart rate reserve (HRR)', 'The difference between maximal heart rate and resting heart rate. Used in the Karvonen formula to calculate target training heart rates.', true),
(3, 'Karvonen formula', 'Target HR = (HRmax - HRrest) x %intensity + HRrest. A method for calculating target heart rate zones using heart rate reserve.', true),
(3, 'Maximal heart rate (HRmax)', 'The highest heart rate an individual can achieve during maximal exertion. Commonly estimated as 220 minus age.', true),
(3, 'Arteries', 'Blood vessels that carry oxygenated blood away from the heart to the body''s tissues (except pulmonary arteries, which carry deoxygenated blood to the lungs).', true),
(3, 'Veins', 'Blood vessels that return deoxygenated blood back to the heart (except pulmonary veins, which return oxygenated blood from the lungs).', true),
(3, 'Capillaries', 'The smallest blood vessels where gas, nutrient, and waste exchange occurs between blood and tissue cells.', true),
(3, 'Blood pressure', 'The force exerted by blood against arterial walls. Measured as systolic (contraction) over diastolic (relaxation). Normal is less than 120/80 mmHg.', true),
(3, 'Systolic blood pressure', 'The pressure in arteries when the heart contracts (beats). The top number in a blood pressure reading.', true),
(3, 'Diastolic blood pressure', 'The pressure in arteries when the heart is relaxed between beats. The bottom number in a blood pressure reading.', true),
(3, 'Respiratory rate', 'The number of breaths taken per minute. Increases during exercise to meet the body''s increased oxygen demand.', true),
(3, 'Tidal volume', 'The amount of air inhaled or exhaled during a normal breath. Increases during exercise to improve gas exchange.', true),
(3, 'Ventilatory threshold', 'The point during exercise at which breathing becomes labored and the body can no longer produce energy efficiently through aerobic metabolism alone.', true),
(3, 'Steady-state cardio', 'Exercise performed at a consistent intensity where oxygen supply meets demand, allowing sustained effort. Typically in heart rate Zone 1.', true),
(3, 'EPOC (Excess Post-exercise Oxygen Consumption)', 'The elevated rate of oxygen intake that occurs after exercise as the body recovers. Higher after intense exercise; contributes to additional calorie burn.', true),
-- Chapter 4: Fitness Assessment
(4, 'Overhead Squat Assessment', 'A transitional movement assessment used to evaluate dynamic flexibility, core strength, balance, and overall neuromuscular control.', true),
(4, 'Kinetic chain checkpoints', 'Five points observed during movement assessments: feet/ankles, knees, lumbo-pelvic-hip complex (LPHC), shoulders, head/cervical spine.', true),
(4, 'Upper crossed syndrome', 'A postural distortion characterized by rounded shoulders and forward head posture, caused by overactive upper trapezius/levator scapulae and underactive deep cervical flexors/lower trapezius.', true),
(4, 'Lower crossed syndrome', 'A postural distortion characterized by an anterior pelvic tilt and increased lumbar lordosis, caused by overactive hip flexors/erector spinae and underactive glutes/abdominals.', true),
(4, 'PAR-Q (Physical Activity Readiness Questionnaire)', 'A pre-participation screening tool that identifies individuals who may need medical clearance before starting an exercise program.', true),
(4, 'Single-leg squat assessment', 'A transitional assessment that evaluates unilateral lower-extremity strength, stability, and neuromuscular control. Compensations include knee valgus and trunk rotation.', true),
(4, 'Pushing assessment', 'An observation of upper-body pushing movement (e.g., push-up) to identify compensations such as low back arching and forward head posture.', true),
(4, 'Pulling assessment', 'An observation of upper-body pulling movement (e.g., standing cable row) to identify compensations such as shoulder elevation and forward head posture.', true),
(4, 'Body composition', 'The relative proportion of fat mass and fat-free mass (muscle, bone, water, organs) in the body. Common methods include skinfold calipers, BIA, and circumference measurements.', true),
(4, 'Body mass index (BMI)', 'A measure of body weight relative to height (kg/m²). Used as a general screening tool but does not distinguish between fat and lean mass.', true),
(4, 'Circumference measurements', 'Body measurements taken at specific anatomical sites to track changes in body size. Common sites include waist, hips, chest, and limbs.', true),
(4, 'Cardiorespiratory fitness assessments', 'Tests that estimate VO2max or aerobic capacity, including the YMCA 3-minute step test, Rockport walk test, and the YMCA bike test.', true),
(4, 'Pronation distortion syndrome', 'A postural distortion characterized by excessive foot pronation (flat feet), knee valgus, and adducted/internally rotated hips.', true),
(4, 'Gait assessment', 'Observation of a client''s walking pattern to identify compensation patterns at the kinetic chain checkpoints (foot/ankle, knee, LPHC, shoulder, head).', true),
(4, 'Static posture assessment', 'A visual observation of a client''s resting alignment from anterior, posterior, and lateral views to identify postural deviations.', true),
(4, 'Subjective information', 'Data gathered from the client about their personal history, including occupation, lifestyle, medical history, and exercise experience.', true),
(4, 'Objective information', 'Measurable data collected by the trainer, including physiological assessments, body composition, cardiorespiratory tests, and movement assessments.', true),
-- Chapter 5: Human Movement Science
(5, 'Eccentric contraction', 'A muscle action where the muscle lengthens under tension (the lowering phase). Example: lowering a dumbbell during a bicep curl.', true),
(5, 'Concentric contraction', 'A muscle action where the muscle shortens under tension (the lifting phase). Example: curling a dumbbell up.', true),
(5, 'Isometric contraction', 'A muscle action where the muscle produces force without changing length. Example: holding a plank.', true),
(5, 'Force-velocity curve', 'As the velocity of a concentric contraction increases, the force the muscle can produce decreases. Slow movements = more force.', true),
(5, 'Biomechanics', 'The study of how forces act on and within the human body during movement, including levers, torque, and planes of motion.', true),
(5, 'Force couple', 'Muscles working together on opposite sides of a joint to produce rotation. Example: the upper trapezius and lower serratus anterior rotate the scapula upward.', true),
(5, 'Length-tension relationship', 'The principle that a muscle generates the most force when it is at its optimal resting length. Overly shortened or lengthened muscles produce less force.', true),
(5, 'Force-production capacity', 'The ability of the neuromuscular system to produce internal tension to overcome external forces; depends on motor unit recruitment and muscle cross-section.', true),
(5, 'Sagittal plane', 'An imaginary plane that divides the body into left and right halves. Movements include flexion and extension (e.g., bicep curls, squats).', true),
(5, 'Frontal plane', 'An imaginary plane that divides the body into front and back halves. Movements include abduction and adduction (e.g., lateral raises, side lunges).', true),
(5, 'Transverse plane', 'An imaginary plane that divides the body into upper and lower halves. Movements include rotation (e.g., cable woodchops, throwing).', true),
(5, 'Lever system', 'A rigid structure (bone) that rotates around a fixed point (joint/fulcrum) when force (muscle) is applied to move a resistance (load).', true),
(5, 'Torque', 'A rotational force produced around an axis. Calculated as force x distance from the axis of rotation (moment arm).', true),
(5, 'Neuromuscular efficiency', 'The ability of the nervous system to recruit the correct muscles (agonists, antagonists, synergists, stabilizers) to produce force and reduce force in all planes of motion.', true),
(5, 'Muscle synergies', 'Groups of muscles that are recruited together by the nervous system to produce coordinated functional movements rather than isolated actions.', true),
(5, 'Motor behavior', 'The study of how motor skills are learned and controlled, encompassing motor control, motor learning, and motor development.', true),
(5, 'Sensorimotor integration', 'The process by which the nervous system gathers sensory information and uses it to produce an appropriate motor response.', true),
(5, 'Mechanical advantage', 'A characteristic of a lever system where the effort arm is longer than the resistance arm, allowing a smaller force to move a larger load.', true),
-- Chapter 6: Flexibility Training Concepts
(6, 'Self-myofascial release (SMR)', 'A flexibility technique using tools like foam rollers to apply pressure to tight muscles, reducing adhesions and improving range of motion.', true),
(6, 'Autogenic inhibition', 'The process by which neural impulses from the GTO override muscle spindle activity, causing a muscle to relax. This is why holding a stretch works.', true),
(6, 'Reciprocal inhibition', 'The simultaneous relaxation of one muscle during contraction of its antagonist. Example: hip flexors relax when glutes contract.', true),
(6, 'Flexibility', 'The normal extensibility of all soft tissues that allows full range of motion at a joint or series of joints.', true),
(6, 'Static stretching', 'Holding a stretch at the end range of motion for 30 seconds. Used in the corrective and active flexibility phases to lengthen overactive muscles.', true),
(6, 'Active-isolated stretching', 'A stretching technique using reciprocal inhibition by actively contracting the antagonist muscle to stretch the agonist. Held for 1-2 seconds, 5-10 reps.', true),
(6, 'Dynamic stretching', 'Active movements that take a joint through its full range of motion, mimicking functional movements. Used as part of a warm-up. Example: walking lunges with rotation.', true),
(6, 'Corrective flexibility', 'The first phase of flexibility training using SMR and static stretching. Goal: correct muscle imbalances and improve joint range of motion.', true),
(6, 'Active flexibility', 'The second phase of flexibility training using SMR and active-isolated stretching. Goal: improve soft tissue extensibility and neuromuscular efficiency.', true),
(6, 'Functional flexibility', 'The third phase of flexibility training using SMR and dynamic stretching. Goal: achieve optimal multiplanar soft tissue extensibility with neuromuscular control.', true),
(6, 'Fascia', 'A connective tissue that surrounds muscles, bones, and joints, providing support and structure. Can develop adhesions (knots) that restrict movement.', true),
(6, 'Adhesion (knot)', 'An area of increased tissue density caused by trauma, inflammation, or poor posture. Restricts normal muscle function and range of motion. Addressed with SMR.', true),
(6, 'Davis''s law', 'Soft tissue remodels along the lines of stress placed upon it. Prolonged poor posture can cause tissues to adapt to shortened positions.', true),
(6, 'Relative flexibility', 'The tendency of the body to seek the path of least resistance during movement, leading to compensation patterns at joints with greater mobility.', true),
(6, 'Neuromuscular stretching', 'An advanced form of stretching (e.g., PNF) that uses the neuromuscular system''s reflexes (autogenic and reciprocal inhibition) to achieve greater flexibility.', true),
(6, 'Pattern overload', 'Repetitive stress on the same tissues without adequate recovery, leading to muscle imbalances, adhesions, and potential injury.', true),
(6, 'Postural distortion patterns', 'Predictable patterns of muscle imbalances. The three main patterns are pronation distortion, lower crossed syndrome, and upper crossed syndrome.', true),
-- Chapter 7: Cardiorespiratory Fitness Training
(7, 'Zone 1 (Base training)', 'Heart rate zone at 65-75% HRmax. Builds an aerobic base, improves fat utilization, and develops cardiovascular efficiency. Used in Stage I training.', true),
(7, 'Zone 2 (Fitness training)', 'Heart rate zone at 76-85% HRmax. Increases aerobic and anaerobic endurance. Used in Stage II training.', true),
(7, 'Zone 3 (Peak performance)', 'Heart rate zone at 86-95% HRmax. High-intensity training that increases peak power and anaerobic capacity. Used in Stage III training.', true),
(7, 'FITTE factors', 'Variables used to design a cardiorespiratory program: Frequency, Intensity, Time, Type, and Enjoyment.', true),
(7, 'Stage I (aerobic base training)', 'Beginner cardio stage using Zone 1. Steady-state exercise at 65-75% HRmax for 20-60 minutes. Goal: build aerobic base and exercise tolerance.', true),
(7, 'Stage II (aerobic efficiency training)', 'Intermediate cardio stage introducing Zone 2 intervals. Alternates between Zone 1 and Zone 2. Goal: increase aerobic endurance and caloric expenditure.', true),
(7, 'Stage III (anaerobic endurance training)', 'Advanced cardio stage introducing Zone 3 intervals. Alternates between Zone 1 and Zone 3. Goal: improve anaerobic threshold and peak VO2.', true),
(7, 'Interval training', 'Alternating between higher-intensity and lower-intensity exercise bouts. More effective for improving VO2max and caloric expenditure than steady-state alone.', true),
(7, 'Rate of perceived exertion (RPE)', 'A subjective scale (typically 1-10) used to gauge exercise intensity based on how hard the client feels they are working.', true),
(7, 'Talk test', 'A simple method to gauge exercise intensity: if a client can speak comfortably, they are likely in an aerobic zone; if they cannot, they are likely in an anaerobic zone.', true),
(7, 'Frequency (FITTE)', 'How often a client performs cardiorespiratory exercise per week. General recommendation: 3-5 days per week for most adults.', true),
(7, 'Intensity (FITTE)', 'How hard a client exercises during cardio training. Measured by HRmax percentage, HRR (Karvonen), RPE, or the talk test.', true),
(7, 'Time (FITTE)', 'The duration of each cardiorespiratory exercise session. General recommendation: 20-60 minutes depending on intensity and fitness level.', true),
(7, 'Type (FITTE)', 'The mode or form of cardiorespiratory exercise (e.g., walking, cycling, swimming, rowing). Should match the client''s goals and abilities.', true),
(7, 'Enjoyment (FITTE)', 'Selecting cardio activities the client finds pleasurable. Crucial for long-term adherence to an exercise program.', true),
(7, 'General warm-up', 'Low-intensity activity (e.g., walking or light cycling) performed for 5-10 minutes before exercise to increase heart rate, blood flow, and tissue temperature.', true),
(7, 'Cool-down', 'A period of low-intensity activity after exercise to gradually reduce heart rate, prevent blood pooling, and promote recovery.', true),
(7, 'Aerobic metabolism', 'Energy production using oxygen to break down carbohydrates and fats. Primary energy system during sustained, lower-intensity exercise.', true),
-- Chapter 8: Core Training Concepts
(8, 'Local stabilization system', 'Deep muscles that attach directly to the vertebrae (transverse abdominis, multifidus, internal obliques, pelvic floor). They stabilize the spine.', true),
(8, 'Global stabilization system', 'Muscles that attach from the pelvis to the spine (quadratus lumborum, psoas major, external obliques). They transfer force between upper and lower body.', true),
(8, 'Drawing-in maneuver', 'Pulling the navel toward the spine to activate the transverse abdominis and stabilize the lumbo-pelvic-hip complex.', true),
(8, 'Global movement system', 'The outermost core muscles responsible for movement and force production (rectus abdominis, hip flexors, hamstring complex, quadriceps).', true),
(8, 'Bracing', 'Co-contracting the global muscles (abdominals, low back, glutes) to create a rigid, stable torso. Used during heavy lifting for spinal protection.', true),
(8, 'Core', 'The lumbo-pelvic-hip complex (LPHC), thoracic spine, and cervical spine. It is where the body''s center of gravity is located and where all movement originates.', true),
(8, 'Core stabilization training', 'Exercises that target the local stabilization system with minimal spinal movement. Examples: plank, floor bridge, prone cobra. Used in OPT Phase 1.', true),
(8, 'Core strength training', 'Exercises involving more dynamic movements through a full range of motion while maintaining core stability. Examples: ball crunch, cable rotation. Used in OPT Phases 2-3.', true),
(8, 'Core power training', 'Explosive core exercises performed at high velocities. Examples: medicine ball throws, rotation chest pass. Used in OPT Phase 5.', true),
(8, 'Transverse abdominis (TVA)', 'The deepest abdominal muscle that wraps around the spine like a corset. Primary muscle activated during the drawing-in maneuver; critical for spinal stabilization.', true),
(8, 'Multifidus', 'A deep spinal muscle that provides segmental stabilization of the vertebrae. Works with the TVA to protect the lumbar spine.', true),
(8, 'Rectus abdominis', 'The most superficial abdominal muscle (the ''six-pack''). Part of the global movement system; responsible for spinal flexion.', true),
(8, 'Internal obliques', 'A deep core muscle that works with the TVA for spinal stabilization. Part of the local stabilization system; assists with rotation and lateral flexion.', true),
(8, 'External obliques', 'A superficial core muscle that assists with trunk rotation, lateral flexion, and force transfer. Part of the global stabilization system.', true),
(8, 'Lumbo-pelvic-hip complex (LPHC)', 'The region comprising the lumbar spine, pelvis, and hip joints. Considered the foundation of the core and the center of the kinetic chain.', true),
(8, 'Intervertebral stability', 'The ability of each spinal segment to maintain proper alignment and resist unwanted movement during loading and dynamic activity.', true),
(8, 'Rate of force production', 'How quickly a muscle can generate force. Core power training increases the rate of force production in the LPHC muscles.', true),
-- Chapter 9: Balance Training Concepts
(9, 'Balance', 'The ability to sustain or return the body''s center of gravity over its base of support. Requires integration of visual, vestibular, and proprioceptive systems.', true),
(9, 'Proprioception', 'The body''s ability to sense the position and movement of its joints and limbs in space. Provided by mechanoreceptors in muscles, tendons, and joints.', true),
(9, 'Base of support', 'The area beneath and between the points of contact the body has with the ground. A wider base increases stability.', true),
(9, 'Center of gravity', 'The point at which the body''s mass is evenly distributed. Located approximately at the sacrum (S2) when standing. Lowering it increases stability.', true),
(9, 'Static balance', 'The ability to maintain a stable position while stationary. Example: single-leg stance.', true),
(9, 'Dynamic balance', 'The ability to maintain stability while in motion or transitioning between movements. Example: single-leg hop and hold.', true),
(9, 'Balance stabilization training', 'Exercises that involve minimal joint motion on an unstable surface. Examples: single-leg balance, single-leg balance reach. Used in OPT Phase 1.', true),
(9, 'Balance strength training', 'Exercises involving dynamic movements through a full range of motion in an unstable environment. Examples: single-leg squat, lunge to balance. Used in OPT Phases 2-3.', true),
(9, 'Balance power training', 'Exercises that involve explosive movements with controlled landings on unstable surfaces. Examples: hop to stabilization, box jump-down. Used in OPT Phase 5.', true),
(9, 'Vestibular system', 'The sensory system located in the inner ear that provides information about head position and movement, contributing to balance and spatial orientation.', true),
(9, 'Visual system', 'Uses visual references (horizon, objects) to provide the brain with information about body position relative to the environment. Important for balance.', true),
(9, 'Somatosensory system', 'The network of sensory receptors in the skin, muscles, tendons, and joints that provides proprioceptive and tactile input for balance control.', true),
(9, 'Mechanoreceptors', 'Sensory receptors that respond to mechanical pressure or distortion. Include muscle spindles, GTOs, and joint receptors. Critical for proprioception and balance.', true),
(9, 'Joint receptors', 'Proprioceptors located in joint capsules that detect pressure, acceleration, and deceleration. Respond to joint position changes and help maintain balance.', true),
(9, 'Postural control', 'The ability of the neuromuscular system to maintain the center of gravity within the base of support, both at rest and during movement.', true),
(9, 'Sensorimotor integration for balance', 'The process of receiving sensory input from proprioceptive, visual, and vestibular systems and producing an appropriate motor response to maintain equilibrium.', true),
(9, 'Multiplanar balance training', 'Performing balance exercises that challenge stability in all three planes of motion (sagittal, frontal, transverse) to develop functional real-world balance.', true),
-- Chapter 10: Plyometric (Reactive) Training Concepts
(10, 'Plyometric training', 'Quick, powerful movements involving an eccentric contraction immediately followed by a concentric contraction. Designed to improve the rate of force production.', true),
(10, 'Stretch-shortening cycle', 'The three-phase mechanism of plyometric movement: eccentric (loading), amortization (transition), and concentric (unloading). Stores and releases elastic energy.', true),
(10, 'Amortization phase', 'The transition phase between the eccentric and concentric phases of a plyometric exercise. Must be as short as possible to maximize power output.', true),
(10, 'Reactive training', 'Exercises that use quick, powerful movements to enhance the neuromuscular system''s ability to produce force rapidly. Synonymous with plyometric training in NASM.', true),
(10, 'Eccentric phase (plyometrics)', 'The loading phase of a plyometric exercise where the muscle lengthens and stores elastic energy. Also called the deceleration or cocking phase.', true),
(10, 'Concentric phase (plyometrics)', 'The unloading phase of a plyometric exercise where stored elastic energy is released to produce an explosive movement.', true),
(10, 'Integrated performance paradigm', 'The concept that in order to move efficiently, the body must eccentrically decelerate, isometrically stabilize, and concentrically accelerate during functional movement.', true),
(10, 'Rate of force production', 'The speed at which muscles can generate force. The primary goal of plyometric training is to increase this rate.', true),
(10, 'Reactive stabilization training', 'Low-intensity plyometric exercises that involve holding a landing or stabilizing after a movement. Examples: squat jump with stabilization. Used in OPT Phase 1.', true),
(10, 'Reactive strength training', 'Moderate-intensity plyometric exercises involving repeated jumps or movements without prolonged holds. Examples: tuck jumps, squat jumps. Used in OPT Phases 2-3.', true),
(10, 'Reactive power training', 'High-intensity plyometric exercises performed as explosively as possible. Examples: ice skaters, depth jumps, plyometric push-ups. Used in OPT Phase 5.', true),
(10, 'Type II fiber recruitment', 'Plyometric training preferentially recruits fast-twitch muscle fibers, which produce high force at high speeds, improving explosive power.', true),
(10, 'Elastic energy', 'Energy stored in the series elastic components (tendons and connective tissue) of muscles during the eccentric phase, then released during the concentric phase.', true),
(10, 'Neuromuscular efficiency (plyometrics)', 'The ability of the nervous system to properly recruit muscles with the right timing and force. Plyometric training improves this through repeated high-speed contractions.', true),
(10, 'Deceleration', 'The ability to slow down or absorb force, primarily through eccentric muscle actions. Must be trained before explosive concentric movements to prevent injury.', true),
(10, 'Proper landing mechanics', 'Landing with soft knees, feet shoulder-width apart, toes pointing forward, and avoiding knee valgus. Essential for safe plyometric training.', true),
(10, 'Power', 'The ability to produce the greatest amount of force in the shortest time. Calculated as force x velocity. The ultimate goal of plyometric training.', true),
-- Chapter 11: SAQ Training
(11, 'Speed', 'The ability to move the body in one direction as fast as possible. Stride rate x stride length.', true),
(11, 'Agility', 'The ability to accelerate, decelerate, stabilize, and change direction quickly while maintaining proper posture.', true),
(11, 'Quickness', 'The ability to react and change body position with maximal rate of force production, in all planes of motion and from all body positions.', true),
(11, 'Cone drills (pro agility / 5-10-5)', 'An agility drill where the athlete shuffles 5 yards to one side, 10 yards back the other way, and 5 yards to finish. Tests change-of-direction speed.', true),
(11, 'Ladder drills', 'Speed and quickness drills performed through a floor ladder to improve foot speed, coordination, and neuromuscular efficiency.', true),
(11, 'Stride length', 'The distance covered with each stride during sprinting. Increasing stride length (without over-striding) contributes to greater speed.', true),
(11, 'Stride rate (frequency)', 'The number of strides taken per unit of time. Combined with stride length, it determines running speed.', true),
(11, 'Backpedal', 'A linear SAQ drill where the athlete runs backward with short, quick steps while maintaining a slight forward lean at the hips.', true),
(11, 'Reactive training for SAQ', 'SAQ drills that incorporate an unpredictable stimulus (e.g., coach pointing a direction) requiring the athlete to react and move quickly.', true),
(11, 'T-drill', 'An agility drill performed in a T-shaped pattern combining forward sprint, lateral shuffles, and backpedaling. Tests multidirectional speed.', true),
(11, 'SAQ programming in OPT', 'Phase 1-2: low intensity with limited complexity. Phase 3-4: moderate-to-high intensity. Phase 5: high intensity with maximum effort and sport specificity.', true),
(11, 'Deceleration', 'The ability to reduce velocity. Requires eccentric strength and is essential for injury prevention during change-of-direction movements.', true),
(11, 'Box drill', 'A four-corner agility drill that involves sprinting, shuffling, and backpedaling around a square or rectangular pattern.', true),
(11, 'Linear speed', 'The rate of movement in a straight line, developed through proper sprint mechanics, arm drive, and leg drive.', true),
(11, 'SAQ warm-up guidelines', 'SAQ training should follow a thorough dynamic warm-up and be performed before resistance training when the nervous system is fresh.', true),
-- Chapter 12: Resistance Training Concepts
(12, 'Stabilization Endurance (Phase 1)', 'OPT Phase 1: high reps (12-20), low intensity, slow tempo (4/2/1), unstable environments. Goal: improve stability and correct imbalances.', true),
(12, 'Strength Endurance (Phase 2)', 'OPT Phase 2: supersets of stable and unstable exercises. Moderate reps (8-12). Goal: improve stabilization endurance and prime movers.', true),
(12, 'Muscular Development (Phase 3)', 'OPT Phase 3: higher volume (3-5 sets, 6-12 reps), moderate to high intensity. Goal: maximal muscle growth (hypertrophy).', true),
(12, 'Maximal Strength (Phase 4)', 'OPT Phase 4: heavy loads (85-100% 1RM), low reps (1-5), long rest (3-5 min). Goal: increase maximal strength.', true),
(12, 'Power (Phase 5)', 'OPT Phase 5: supersets of heavy strength exercise + explosive power exercise. Goal: develop speed and power.', true),
(12, 'Repetition (rep)', 'One complete movement of a particular exercise through a full range of motion.', true),
(12, 'Set', 'A group of consecutive repetitions performed without rest.', true),
(12, 'Training volume', 'The total amount of work performed in a training session, often calculated as sets x reps x load.', true),
(12, 'Training intensity', 'The level of effort or demand placed on the body during exercise. In resistance training, typically expressed as a percentage of one-repetition maximum (%1RM).', true),
(12, 'Tempo', 'The speed at which each rep is performed, expressed as a three- or four-digit code (eccentric/isometric hold/concentric/isometric hold). Example: 4/2/1 tempo.', true),
(12, 'Rest interval', 'The time between sets or exercises. Stabilization: 0-90 sec; Strength: 0-60 sec; Hypertrophy: 0-60 sec; Max Strength: 3-5 min; Power: 3-5 min.', true),
(12, 'Superset', 'A training system where two exercises are performed back-to-back with minimal rest, typically pairing opposing muscle groups or the same muscle group.', true),
(12, 'Circuit training', 'A training system where a series of exercises (typically 5-10) are performed one after another with minimal rest between each. Effective for improving muscular endurance and cardiovascular fitness.', true),
(12, 'Drop set', 'A training system where an exercise is performed to fatigue, then the weight is immediately reduced and the set continues for additional reps.', true),
(12, 'Pyramid training', 'A training system that involves increasing weight with each set while decreasing reps (ascending), or decreasing weight while increasing reps (descending).', true),
(12, 'Split routine', 'A training program that divides body parts into different training days (e.g., upper/lower split, push/pull split) to allow targeted volume and adequate recovery.', true),
(12, 'Periodization', 'A systematic plan that varies training variables (volume, intensity, exercise selection) over specific time periods to maximize adaptations and prevent overtraining.', true),
(12, 'General Adaptation Syndrome (GAS)', 'Selye''s model describing how the body responds to stress in three stages: alarm reaction, resistance development, and exhaustion. Underpins periodization.', true),
(12, 'One-repetition maximum (1RM)', 'The maximum amount of weight that can be lifted for one complete repetition of an exercise with proper form. Used to prescribe training intensity.', true),
(12, 'Mechanical specificity', 'The weight and movements placed on the body during exercise must mirror those experienced during sport or daily activity (SAID principle applied to resistance training).', true),
(12, 'Neuromuscular specificity', 'The speed of contraction during training must match the desired speed during functional performance.', true),
-- Chapter 13: The OPT Model
(13, 'OPT Model', 'Optimum Performance Training model. NASM''s systematic training framework with 3 levels (Stabilization, Strength, Power) and 5 phases.', true),
(13, 'Periodization', 'Systematic planning of training that varies volume, intensity, and exercise selection over time to prevent plateaus and overtraining.', true),
(13, 'OPT model', 'Optimum Performance Training — NASM''s systematic training program that uses progressive, phase-based training across stabilization, strength, and power levels.', true),
(13, 'Phase 1: Stabilization Endurance', 'High reps (12-20), low intensity (50-70% 1RM), slow tempo (4/2/1), unstable but controlled environments. Goal: improve muscular endurance, stability, and correct imbalances.', true),
(13, 'Phase 2: Strength Endurance', 'Moderate reps (8-12), moderate intensity (70-80% 1RM). Supersets a stable exercise with a stabilization exercise for each body part.', true),
(13, 'Phase 3: Muscular Development (Hypertrophy)', 'Moderate-to-high reps (6-12), high volume (3-5 sets), moderate-to-high intensity (75-85% 1RM), moderate tempo (2/0/2). Goal: maximal muscle growth.', true),
(13, 'Phase 4: Maximal Strength', 'Low reps (1-5), high intensity (85-100% 1RM), longer rest (3-5 min). Goal: recruit the maximum number of motor units and increase maximal force production.', true),
(13, 'Phase 5: Power', 'Supersets a heavy strength exercise (85-100% 1RM) with a power/explosive exercise (30-45% 1RM) performed as fast as possible. Goal: develop both high force and high velocity.', true),
(13, 'Acute variables', 'Training program components that can be manipulated: reps, sets, intensity, tempo, rest interval, volume, frequency, duration, and exercise selection.', true),
(13, 'Mesocycle', 'A training period lasting approximately 2-6 weeks, during which specific training goals and acute variables are emphasized. Each OPT phase is typically one mesocycle.', true),
(13, 'Macrocycle', 'An overall training period, usually spanning an entire year or training season, encompassing all mesocycles.', true),
(13, 'Microcycle', 'The shortest training period, typically one week, representing the day-to-day training plan.', true),
(13, 'Undulating (nonlinear) periodization', 'A periodization method that varies training stimuli on a daily or weekly basis rather than in extended blocks. Can improve adherence and provide varied stimuli.', true),
(13, 'Stabilization level', 'The first level of the OPT model containing Phase 1. Focuses on improving stability, correcting imbalances, and building an exercise foundation.', true),
(13, 'Strength level', 'The second level of the OPT model containing Phases 2, 3, and 4. Focuses on building strength endurance, hypertrophy, and maximal strength.', true),
(13, 'Power level', 'The third level of the OPT model containing Phase 5. Focuses on producing force at high velocities (rate of force production).', true),
(13, 'Phase 5 tempo', 'Strength exercise: slow/controlled; Power exercise: explosive (X/X/X — as fast as can be controlled). Rest 3-5 minutes between supersets.', true),
(13, 'Progressive overload', 'The gradual and systematic increase of training stress over time, essential for continued adaptation. Achieved by manipulating acute variables.', true),
-- Chapter 14: Nutrition
(14, 'Macronutrients', 'Nutrients needed in large amounts: carbohydrates (4 cal/g), protein (4 cal/g), and fat (9 cal/g).', true),
(14, 'BMR (Basal Metabolic Rate)', 'The number of calories your body needs at complete rest to maintain basic life functions. Accounts for ~70% of daily energy expenditure.', true),
(14, 'TDEE (Total Daily Energy Expenditure)', 'Total calories burned in a day. Includes BMR + physical activity + thermic effect of food.', true),
(14, 'Macronutrients', 'Nutrients required in large amounts that provide energy: carbohydrates (4 kcal/g), proteins (4 kcal/g), and fats (9 kcal/g).', true),
(14, 'Micronutrients', 'Vitamins and minerals required in small amounts that do not provide energy directly but are essential for metabolic processes, immune function, and bone health.', true),
(14, 'Glycemic index (GI)', 'A scale (0-100) that ranks carbohydrates based on how quickly they raise blood glucose levels compared to pure glucose (GI = 100). Low GI < 55, High GI > 70.', true),
(14, 'Recommended protein intake for active individuals', 'Approximately 1.2-2.0 g/kg of body weight per day, depending on activity type and intensity. Supports muscle repair and growth.', true),
(14, 'Essential amino acids', 'Nine amino acids that cannot be synthesized by the body and must be obtained through diet: histidine, isoleucine, leucine, lysine, methionine, phenylalanine, threonine, tryptophan, valine.', true),
(14, 'Hydration guidelines', 'Drink approximately 14-22 oz of water 2 hours before exercise. During exercise, drink 6-12 oz every 15-20 minutes. After exercise, drink 16-24 oz per pound of body weight lost.', true),
(14, 'Total Daily Energy Expenditure (TDEE)', 'The total number of calories burned in a day, comprising resting metabolic rate (RMR), thermic effect of food (TEF), and thermic effect of physical activity (TEPA).', true),
(14, 'Resting metabolic rate (RMR)', 'The number of calories the body requires at rest to maintain normal physiological functions. Accounts for approximately 70% of TDEE.', true),
(14, 'Thermic effect of food (TEF)', 'The energy expended during digestion, absorption, and metabolism of food. Accounts for approximately 10% of TDEE. Protein has the highest thermic effect.', true),
(14, 'Saturated vs. unsaturated fat', 'Saturated fats (solid at room temperature, animal sources) may raise LDL cholesterol. Unsaturated fats (liquid at room temperature, plant/fish sources) support heart health.', true),
(14, 'Fiber', 'An indigestible carbohydrate that supports digestive health, helps regulate blood sugar, and promotes satiety. Recommended intake: 25-38 g/day.', true),
(14, 'Nutrient timing', 'Strategically consuming nutrients around exercise to optimize performance and recovery. A combination of protein and carbohydrates within 1-2 hours post-exercise supports glycogen replenishment and muscle repair.', true),
(14, 'Caloric surplus and deficit', 'A surplus (consuming more calories than TDEE) promotes weight gain; a deficit (consuming fewer calories than TDEE) promotes weight loss. ~3,500 kcal ≈ 1 lb of body fat.', true),
(14, 'Scope of practice for nutrition', 'Personal trainers can provide general nutritional information (MyPlate guidelines, food labels) but cannot prescribe specific diets or meal plans unless also a licensed/registered dietitian.', true),
(14, 'Water functions in the body', 'Regulates body temperature, transports nutrients and oxygen, cushions organs and joints, removes waste products. The body is approximately 60% water.', true),
-- Chapter 15: Supplements
(15, 'Dietary supplement', 'A product taken by mouth intended to supplement the diet, including vitamins, minerals, herbs, amino acids, and enzymes. Regulated under DSHEA, not evaluated by the FDA for efficacy before sale.', true),
(15, 'Creatine monohydrate', 'One of the most researched supplements; increases phosphocreatine stores in muscle, improving short-duration, high-intensity exercise performance. Typical dose: 3-5 g/day after loading.', true),
(15, 'Whey protein', 'A fast-digesting, complete protein derived from milk. Rich in branched-chain amino acids (BCAAs), especially leucine. Commonly used post-exercise for muscle protein synthesis.', true),
(15, 'Casein protein', 'A slow-digesting milk protein that provides a sustained release of amino acids. Often consumed before sleep to support overnight muscle recovery.', true),
(15, 'Branched-chain amino acids (BCAAs)', 'Three essential amino acids — leucine, isoleucine, and valine — that play a key role in muscle protein synthesis. Leucine is the primary trigger for MPS.', true),
(15, 'Caffeine as ergogenic aid', 'A stimulant that can improve endurance performance, increase alertness, and reduce perceived exertion. Effective dose: approximately 3-6 mg/kg body weight taken 30-60 min before exercise.', true),
(15, 'Beta-alanine', 'An amino acid supplement that increases intramuscular carnosine levels, buffering hydrogen ions during high-intensity exercise. May reduce fatigue and improve performance in efforts lasting 1-4 minutes.', true),
(15, 'Ergogenic aid', 'Any substance, device, or practice that enhances energy production, use, or recovery to improve physical performance.', true),
(15, 'DSHEA (1994)', 'Dietary Supplement Health and Education Act — the federal law that regulates supplements as foods, not drugs. Manufacturers are responsible for safety; the FDA does not approve supplements before sale.', true),
(15, 'Vitamin D', 'A fat-soluble vitamin essential for calcium absorption, bone health, and immune function. Deficiency is common, especially in those with limited sun exposure.', true),
(15, 'Iron', 'A mineral essential for oxygen transport in hemoglobin and myoglobin. Deficiency can cause fatigue and impaired exercise performance, particularly in female athletes.', true),
(15, 'Sodium bicarbonate', 'An extracellular buffer supplement that may improve performance in high-intensity exercise lasting 1-7 minutes by buffering lactic acid accumulation.', true),
(15, 'Third-party supplement testing', 'Independent organizations (NSF Certified for Sport, Informed Sport, USP) test supplements for banned substances, label accuracy, and contaminants. Recommended for athletes and clients.', true),
(15, 'Omega-3 fatty acids', 'Essential polyunsaturated fats (EPA and DHA) found in fish oil. Associated with reduced inflammation, improved cardiovascular health, and potential benefits for joint health.', true),
(15, 'Multivitamin/mineral supplement', 'A general supplement providing a range of essential vitamins and minerals. May help fill dietary gaps but is not a substitute for a balanced diet.', true),
-- Chapter 16: Behavioral Coaching
(16, 'Transtheoretical model (Stages of Change)', 'A behavior change model with five stages: precontemplation, contemplation, preparation, action, and maintenance. Helps trainers tailor strategies to a client''s readiness.', true),
(16, 'Precontemplation stage', 'The person is not yet considering change and may be unaware of the need. They have no intention to take action within the next 6 months.', true),
(16, 'Contemplation stage', 'The person acknowledges a problem and is thinking about change but has not committed. Intends to take action within the next 6 months.', true),
(16, 'Preparation stage', 'The person intends to take action soon (within the next month) and may begin taking small steps, such as joining a gym.', true),
(16, 'Action stage', 'The person has made specific, overt lifestyle modifications within the last 6 months but the behavior is not yet habitual.', true),
(16, 'Maintenance stage', 'The person has sustained the behavior change for more than 6 months and is working to prevent relapse.', true),
(16, 'SMART goals', 'Goals that are Specific, Measurable, Attainable, Realistic, and Time-bound. Help clients create clear, achievable objectives.', true),
(16, 'Self-efficacy', 'A person''s belief in their ability to succeed in a specific situation or accomplish a task. Higher self-efficacy correlates with greater adherence to exercise programs.', true),
(16, 'Motivational interviewing', 'A client-centered counseling style that helps resolve ambivalence about change by exploring and enhancing the client''s own motivation and reasons for change.', true),
(16, 'Decisional balance', 'A cognitive process of weighing the pros and cons of behavior change. Used in the contemplation stage to help clients see that benefits outweigh costs.', true),
(16, 'Relapse', 'A return to previous unhealthy behaviors after a period of change. It is a normal part of the change process, not a failure. Trainers should help clients re-enter the cycle.', true),
(16, 'Cognitive strategies', 'Mental techniques such as visualization, positive self-talk, and psyching up that help clients stay motivated and overcome barriers to exercise.', true),
(16, 'Extrinsic vs. intrinsic motivation', 'Extrinsic motivation comes from external rewards (praise, appearance). Intrinsic motivation comes from internal satisfaction (enjoyment, sense of accomplishment). Long-term adherence is driven more by intrinsic motivation.', true),
(16, 'Social support', 'Encouragement from friends, family, or training partners that improves exercise adherence. Trainers can build this through group settings and accountability.', true),
(16, 'Rapport', 'A trusting, respectful relationship between trainer and client. Built through active listening, empathy, professionalism, and genuine interest in the client''s goals.', true),
-- Chapter 17: Special Populations
(17, 'Special populations', 'Groups requiring modified exercise programming: youth, older adults, pregnant women, those with obesity, diabetes, hypertension, or other conditions.', true),
(17, 'Diabetes considerations', 'For diabetic clients: monitor blood glucose before/during/after exercise, carry fast-acting carbs, avoid exercise during peak insulin activity.', true),
(17, 'Youth training guidelines', 'Emphasize proper technique, body-weight exercises, and fun. Avoid maximal lifts. Use higher reps (12-20), lighter loads, and focus on neuromuscular control and movement competency.', true),
(17, 'Senior training guidelines', 'Focus on functional capacity, balance, and fall prevention. Start with Phase 1 (Stabilization Endurance). Emphasize proper breathing (no Valsalva), controlled tempo, and joint-friendly exercises.', true),
(17, 'Prenatal exercise guidelines', 'Moderate-intensity exercise is generally safe and recommended. Avoid supine positions after the first trimester, high-impact activities, and exercises with fall risk. Monitor heart rate and perceived exertion.', true),
(17, 'Postnatal exercise guidelines', 'Gradually return to exercise after medical clearance (typically 4-6 weeks postpartum). Focus on core stabilization, pelvic floor strengthening, and rebuilding aerobic fitness progressively.', true),
(17, 'Obesity training guidelines', 'Begin with low-to-moderate intensity, longer-duration cardio. Emphasize non-weight-bearing activities initially (cycling, swimming). Progress slowly. Combine with nutritional guidance within scope.', true),
(17, 'Sarcopenia', 'The age-related loss of skeletal muscle mass, strength, and function. Resistance training is one of the most effective interventions to slow or reverse sarcopenia.', true),
(17, 'Osteopenia', 'A condition of reduced bone mineral density that precedes osteoporosis. Weight-bearing and resistance exercises help maintain and increase bone density.', true),
(17, 'BMI (Body Mass Index)', 'A screening tool calculated as weight (kg) / height (m²). Categories: underweight < 18.5, normal 18.5-24.9, overweight 25-29.9, obese ≥ 30. Does not distinguish fat from muscle.', true),
(17, 'Valsalva maneuver', 'Holding breath and bearing down during exertion. Can dangerously increase blood pressure. Should be avoided, especially in senior and hypertensive populations.', true),
(17, 'Balance training for seniors', 'Single-leg stands, tandem stance, and stability ball exercises reduce fall risk. Progress from stable surfaces to unstable surfaces as competency increases.', true),
(17, 'Youth resistance training misconceptions', 'Properly supervised resistance training does NOT stunt growth. It improves bone density, motor skills, and self-confidence when age-appropriate guidelines are followed.', true),
(17, 'Rating of Perceived Exertion (RPE)', 'A subjective 1-10 scale used to gauge exercise intensity. Especially useful for special populations where heart rate monitoring may be unreliable.', true),
(17, 'Thermoregulation in special populations', 'Youth and seniors have impaired thermoregulation. Extra precautions needed in hot/cold environments: adequate hydration, appropriate clothing, shorter outdoor sessions.', true),
(17, 'Exercise and gestational diabetes', 'Regular moderate exercise during pregnancy can help regulate blood glucose and reduce the risk of gestational diabetes mellitus.', true),
(17, 'Progressive overload for obese clients', 'Increase duration before intensity. Start with 10-20 minutes and build to 30-60 minutes per session. Reduce joint stress with non-impact modalities.', true),
-- Chapter 18: Chronic Conditions
(18, 'Diabetes mellitus (Type 1 vs. Type 2)', 'Type 1: autoimmune destruction of pancreatic beta cells, requiring insulin. Type 2: insulin resistance, often linked to obesity and inactivity. Exercise improves insulin sensitivity in both types.', true),
(18, 'Hypertension', 'Chronically elevated blood pressure (≥ 130/80 mmHg per current guidelines). Exercise reduces resting blood pressure by approximately 5-7 mmHg. Avoid heavy lifting and Valsalva.', true),
(18, 'Coronary heart disease (CHD)', 'A condition caused by plaque buildup in the coronary arteries, reducing blood flow to the heart. Risk factors include hypertension, dyslipidemia, diabetes, smoking, obesity, and inactivity.', true),
(18, 'Osteoporosis', 'A disease characterized by low bone mass and deterioration of bone tissue, increasing fracture risk. Weight-bearing exercise and resistance training help maintain bone density.', true),
(18, 'Arthritis (osteoarthritis vs. rheumatoid)', 'Osteoarthritis: degenerative joint disease from wear and tear. Rheumatoid: autoimmune condition causing joint inflammation. Both benefit from low-impact exercise; avoid training during acute flare-ups.', true),
(18, 'Chronic obstructive pulmonary disease (COPD)', 'A group of progressive lung diseases (emphysema, chronic bronchitis) that limit airflow. Exercise improves functional capacity and quality of life; use RPE to monitor intensity.', true),
(18, 'Hypoglycemia during exercise (diabetes)', 'Dangerously low blood glucose that can occur during exercise in diabetic clients, especially those on insulin. Signs: dizziness, shakiness, confusion. Have fast-acting carbohydrates available.', true),
(18, 'Dyslipidemia', 'Abnormal blood lipid levels (elevated LDL, elevated triglycerides, low HDL). Regular aerobic exercise can improve lipid profiles by raising HDL and lowering LDL and triglycerides.', true),
(18, 'Peripheral artery disease (PAD)', 'Narrowing of peripheral arteries reducing blood flow to the extremities. Walking programs can improve claudication symptoms and functional capacity.', true),
(18, 'Exercise and blood glucose monitoring', 'Diabetic clients should check blood glucose before, during, and after exercise. Avoid exercise if glucose is above 250 mg/dL with ketones or below 100 mg/dL without a snack.', true),
(18, 'Metabolic syndrome', 'A cluster of conditions — elevated waist circumference, high triglycerides, low HDL, high blood pressure, and high fasting glucose — that increase risk for CHD and Type 2 diabetes.', true),
(18, 'Physician clearance', 'Medical approval required before beginning an exercise program for clients with known chronic conditions. The PAR-Q+ and health history questionnaire help identify those who need clearance.', true),
(18, 'Exercise guidelines for hypertension', 'Moderate-intensity aerobic exercise most days of the week. Avoid isometric exercises and heavy resistance. Keep intensity moderate and monitor blood pressure response.', true),
(18, 'Osteoporosis exercise contraindications', 'Avoid excessive spinal flexion, high-impact activities, and explosive movements that increase fracture risk. Focus on weight-bearing, resistance, and balance exercises.', true),
(18, 'Cardiac rehabilitation', 'A medically supervised program for individuals recovering from cardiac events. Trainers may work with post-rehab clients with physician clearance, starting conservatively.', true),
-- Chapter 19: Professional Development
(19, 'Scope of practice', 'The boundaries of what a personal trainer is qualified to do. Trainers CANNOT diagnose conditions, prescribe diets, or provide therapy.', true),
(19, 'PAR-Q', 'Physical Activity Readiness Questionnaire. A screening tool used before starting an exercise program to identify potential health risks.', true),
(19, 'Scope of practice', 'The legal and professional boundaries that define the services a personal trainer can provide. Trainers should not diagnose injuries, prescribe diets, or provide therapy.', true),
(19, 'Professional liability insurance', 'Insurance that protects personal trainers from financial loss due to claims of negligence or injury. All trainers should carry their own policy regardless of employer coverage.', true),
(19, 'Negligence', 'The failure to act with reasonable care, resulting in harm. Four elements: duty, breach of duty, cause, and damages. Proper documentation and certifications reduce negligence risk.', true),
(19, 'Informed consent', 'A document that explains the risks, benefits, and procedures of an exercise program. Must be signed by the client before beginning training. Does not waive the trainer''s duty of care.', true),
(19, 'Confidentiality (HIPAA)', 'Personal trainers must protect all client health information. Sharing medical or personal data without consent is both unethical and potentially illegal.', true),
(19, 'Active listening', 'A communication skill where the trainer fully concentrates on what the client is saying, reflects back, and asks clarifying questions. Builds trust and rapport.', true),
(19, 'Continuing education (CEUs)', 'Ongoing education credits required to maintain NASM certification. Ensures trainers stay current with evolving science, techniques, and best practices.', true),
(19, 'Ethics in personal training', 'Professional conduct standards including honesty, integrity, respecting client boundaries, maintaining confidentiality, avoiding dual relationships, and staying within scope of practice.', true),
(19, 'Assumption of risk / waiver', 'A legal document in which the client acknowledges the inherent risks of exercise. Provides some legal protection but does not protect against trainer negligence.', true),
(19, 'Proper documentation', 'Trainers should maintain records of assessments, programs, progress, incident reports, and client communications. Protects both the trainer and client legally.', true),
(19, 'Emergency action plan', 'A written plan that outlines procedures for responding to emergencies in a fitness facility, including roles, communication, and equipment locations.', true),
(19, 'Professional appearance and conduct', 'Maintaining a clean, professional appearance, being punctual, using appropriate language, and demonstrating competence all contribute to client trust and retention.', true),
(19, 'Referral network', 'A network of allied health professionals (physicians, dietitians, physical therapists, psychologists) to whom trainers can refer clients for services outside their scope.', true),
(19, 'Dual relationship', 'A situation where a trainer has both a professional and personal relationship with a client (e.g., romantic, business). Should be avoided as it compromises professional judgment.', true),
(19, 'CPR/AED certification', 'A required certification for personal trainers that ensures competency in performing cardiopulmonary resuscitation and using an automated external defibrillator in emergencies.', true),
-- Chapter 20: Business Development
(20, 'Client acquisition', 'The process of attracting and securing new clients through marketing, networking, referrals, complimentary sessions, and community engagement.', true),
(20, 'Client retention', 'Strategies for keeping clients long-term, including delivering results, building rapport, providing excellent customer service, tracking progress, and maintaining consistent communication.', true),
(20, 'Sales process for personal training', 'A systematic approach: build rapport → identify needs/goals → present solutions → handle objections → close → follow up. Focus on the client''s needs, not the product.', true),
(20, 'Elevator pitch', 'A brief (30-60 second) personal introduction that communicates who you are, what you do, and how you help clients. Should be clear, confident, and tailored to the audience.', true),
(20, 'Closing the sale', 'The step in the sales process where the trainer asks the client to commit. Techniques include the assumptive close, the direct close, and the choice close.', true),
(20, 'Handling objections', 'Responding to client concerns (cost, time, uncertainty) with empathy, reframing, and solution-focused responses. Listen first, then address the underlying concern.', true),
(20, 'Referral system', 'A structured strategy for encouraging existing clients to refer friends and family. Incentives, social proof, and delivering great results drive referrals.', true),
(20, 'Social media marketing', 'Using platforms (Instagram, Facebook, YouTube) to build brand awareness, share expertise, showcase client transformations, and attract potential clients.', true),
(20, 'Programming for client goals', 'Designing individualized exercise programs based on the client''s assessment results, goals, preferences, and lifestyle. Ensures relevance, safety, and adherence.', true),
(20, 'Revenue streams for trainers', 'Income sources including one-on-one training, small group training, online coaching, workshops, corporate wellness, and digital products (programs, e-books).', true),
(20, 'Professionalism in business', 'Treating personal training as a business: tracking finances, setting goals, managing time effectively, investing in continuing education, and maintaining high ethical standards.', true),
(20, 'Complimentary session', 'A free introductory training session used to demonstrate value, build rapport, perform initial assessments, and convert prospects into paying clients.', true),
(20, 'Tracking client progress', 'Regularly reassessing clients through body composition measurements, fitness assessments, and performance benchmarks. Demonstrates results and justifies continued investment.', true),
(20, 'Time management for trainers', 'Prioritizing income-producing activities (training, follow-ups, prospecting) and scheduling administrative tasks efficiently. Prevents burnout and maximizes revenue.', true),
(20, 'Building a personal brand', 'Establishing a unique professional identity through consistent messaging, specialization, visible expertise, and delivering a consistent client experience.', true);
