// Flashcards for Chapters 11-20 — NASM CPT 7th Edition
// Covers SAQ, resistance training, OPT model, nutrition, supplements,
// behavioral coaching, special populations, chronic conditions, and professional/business development

export const seedFlashcards2 = [
  // ── Chapter 11: SAQ Training ──────────────────────────────────────
  { chapter: 11, term: "Speed", definition: "The ability to move the body in one direction as fast as possible. Stride rate × stride length." },
  { chapter: 11, term: "Agility", definition: "The ability to accelerate, decelerate, stabilize, and change direction quickly while maintaining proper posture." },
  { chapter: 11, term: "Quickness", definition: "The ability to react and change body position with maximal rate of force production, in all planes of motion and from all body positions." },
  { chapter: 11, term: "Cone drills (pro agility / 5-10-5)", definition: "An agility drill where the athlete shuffles 5 yards to one side, 10 yards back the other way, and 5 yards to finish. Tests change-of-direction speed." },
  { chapter: 11, term: "Ladder drills", definition: "Speed and quickness drills performed through a floor ladder to improve foot speed, coordination, and neuromuscular efficiency." },
  { chapter: 11, term: "Stride length", definition: "The distance covered with each stride during sprinting. Increasing stride length (without over-striding) contributes to greater speed." },
  { chapter: 11, term: "Stride rate (frequency)", definition: "The number of strides taken per unit of time. Combined with stride length, it determines running speed." },
  { chapter: 11, term: "Backpedal", definition: "A linear SAQ drill where the athlete runs backward with short, quick steps while maintaining a slight forward lean at the hips." },
  { chapter: 11, term: "Reactive training for SAQ", definition: "SAQ drills that incorporate an unpredictable stimulus (e.g., coach pointing a direction) requiring the athlete to react and move quickly." },
  { chapter: 11, term: "T-drill", definition: "An agility drill performed in a T-shaped pattern combining forward sprint, lateral shuffles, and backpedaling. Tests multidirectional speed." },
  { chapter: 11, term: "SAQ programming in OPT", definition: "Phase 1-2: low intensity with limited complexity. Phase 3-4: moderate-to-high intensity. Phase 5: high intensity with maximum effort and sport specificity." },
  { chapter: 11, term: "Deceleration", definition: "The ability to reduce velocity. Requires eccentric strength and is essential for injury prevention during change-of-direction movements." },
  { chapter: 11, term: "Box drill", definition: "A four-corner agility drill that involves sprinting, shuffling, and backpedaling around a square or rectangular pattern." },
  { chapter: 11, term: "Linear speed", definition: "The rate of movement in a straight line, developed through proper sprint mechanics, arm drive, and leg drive." },
  { chapter: 11, term: "SAQ warm-up guidelines", definition: "SAQ training should follow a thorough dynamic warm-up and be performed before resistance training when the nervous system is fresh." },

  // ── Chapter 12: Resistance Training ───────────────────────────────
  { chapter: 12, term: "Repetition (rep)", definition: "One complete movement of a particular exercise through a full range of motion." },
  { chapter: 12, term: "Set", definition: "A group of consecutive repetitions performed without rest." },
  { chapter: 12, term: "Training volume", definition: "The total amount of work performed in a training session, often calculated as sets × reps × load." },
  { chapter: 12, term: "Training intensity", definition: "The level of effort or demand placed on the body during exercise. In resistance training, typically expressed as a percentage of one-repetition maximum (%1RM)." },
  { chapter: 12, term: "Tempo", definition: "The speed at which each rep is performed, expressed as a three- or four-digit code (eccentric/isometric hold/concentric/isometric hold). Example: 4/2/1 tempo." },
  { chapter: 12, term: "Rest interval", definition: "The time between sets or exercises. Stabilization: 0-90 sec; Strength: 0-60 sec; Hypertrophy: 0-60 sec; Max Strength: 3-5 min; Power: 3-5 min." },
  { chapter: 12, term: "Superset", definition: "A training system where two exercises are performed back-to-back with minimal rest, typically pairing opposing muscle groups or the same muscle group." },
  { chapter: 12, term: "Circuit training", definition: "A training system where a series of exercises (typically 5-10) are performed one after another with minimal rest between each. Effective for improving muscular endurance and cardiovascular fitness." },
  { chapter: 12, term: "Drop set", definition: "A training system where an exercise is performed to fatigue, then the weight is immediately reduced and the set continues for additional reps." },
  { chapter: 12, term: "Pyramid training", definition: "A training system that involves increasing weight with each set while decreasing reps (ascending), or decreasing weight while increasing reps (descending)." },
  { chapter: 12, term: "Split routine", definition: "A training program that divides body parts into different training days (e.g., upper/lower split, push/pull split) to allow targeted volume and adequate recovery." },
  { chapter: 12, term: "Periodization", definition: "A systematic plan that varies training variables (volume, intensity, exercise selection) over specific time periods to maximize adaptations and prevent overtraining." },
  { chapter: 12, term: "General Adaptation Syndrome (GAS)", definition: "Selye's model describing how the body responds to stress in three stages: alarm reaction, resistance development, and exhaustion. Underpins periodization." },
  { chapter: 12, term: "One-repetition maximum (1RM)", definition: "The maximum amount of weight that can be lifted for one complete repetition of an exercise with proper form. Used to prescribe training intensity." },
  { chapter: 12, term: "Mechanical specificity", definition: "The weight and movements placed on the body during exercise must mirror those experienced during sport or daily activity (SAID principle applied to resistance training)." },
  { chapter: 12, term: "Neuromuscular specificity", definition: "The speed of contraction during training must match the desired speed during functional performance." },

  // ── Chapter 13: The OPT Model ─────────────────────────────────────
  { chapter: 13, term: "OPT model", definition: "Optimum Performance Training — NASM's systematic training program that uses progressive, phase-based training across stabilization, strength, and power levels." },
  { chapter: 13, term: "Phase 1: Stabilization Endurance", definition: "High reps (12-20), low intensity (50-70% 1RM), slow tempo (4/2/1), unstable but controlled environments. Goal: improve muscular endurance, stability, and correct imbalances." },
  { chapter: 13, term: "Phase 2: Strength Endurance", definition: "Moderate reps (8-12), moderate intensity (70-80% 1RM). Supersets a stable exercise with a stabilization exercise for each body part." },
  { chapter: 13, term: "Phase 3: Muscular Development (Hypertrophy)", definition: "Moderate-to-high reps (6-12), high volume (3-5 sets), moderate-to-high intensity (75-85% 1RM), moderate tempo (2/0/2). Goal: maximal muscle growth." },
  { chapter: 13, term: "Phase 4: Maximal Strength", definition: "Low reps (1-5), high intensity (85-100% 1RM), longer rest (3-5 min). Goal: recruit the maximum number of motor units and increase maximal force production." },
  { chapter: 13, term: "Phase 5: Power", definition: "Supersets a heavy strength exercise (85-100% 1RM) with a power/explosive exercise (30-45% 1RM) performed as fast as possible. Goal: develop both high force and high velocity." },
  { chapter: 13, term: "Acute variables", definition: "Training program components that can be manipulated: reps, sets, intensity, tempo, rest interval, volume, frequency, duration, and exercise selection." },
  { chapter: 13, term: "Mesocycle", definition: "A training period lasting approximately 2-6 weeks, during which specific training goals and acute variables are emphasized. Each OPT phase is typically one mesocycle." },
  { chapter: 13, term: "Macrocycle", definition: "An overall training period, usually spanning an entire year or training season, encompassing all mesocycles." },
  { chapter: 13, term: "Microcycle", definition: "The shortest training period, typically one week, representing the day-to-day training plan." },
  { chapter: 13, term: "Undulating (nonlinear) periodization", definition: "A periodization method that varies training stimuli on a daily or weekly basis rather than in extended blocks. Can improve adherence and provide varied stimuli." },
  { chapter: 13, term: "Stabilization level", definition: "The first level of the OPT model containing Phase 1. Focuses on improving stability, correcting imbalances, and building an exercise foundation." },
  { chapter: 13, term: "Strength level", definition: "The second level of the OPT model containing Phases 2, 3, and 4. Focuses on building strength endurance, hypertrophy, and maximal strength." },
  { chapter: 13, term: "Power level", definition: "The third level of the OPT model containing Phase 5. Focuses on producing force at high velocities (rate of force production)." },
  { chapter: 13, term: "Phase 5 tempo", definition: "Strength exercise: slow/controlled; Power exercise: explosive (X/X/X — as fast as can be controlled). Rest 3-5 minutes between supersets." },
  { chapter: 13, term: "Progressive overload", definition: "The gradual and systematic increase of training stress over time, essential for continued adaptation. Achieved by manipulating acute variables." },

  // ── Chapter 14: Nutrition ─────────────────────────────────────────
  { chapter: 14, term: "Macronutrients", definition: "Nutrients required in large amounts that provide energy: carbohydrates (4 kcal/g), proteins (4 kcal/g), and fats (9 kcal/g)." },
  { chapter: 14, term: "Micronutrients", definition: "Vitamins and minerals required in small amounts that do not provide energy directly but are essential for metabolic processes, immune function, and bone health." },
  { chapter: 14, term: "Glycemic index (GI)", definition: "A scale (0-100) that ranks carbohydrates based on how quickly they raise blood glucose levels compared to pure glucose (GI = 100). Low GI < 55, High GI > 70." },
  { chapter: 14, term: "Recommended protein intake for active individuals", definition: "Approximately 1.2-2.0 g/kg of body weight per day, depending on activity type and intensity. Supports muscle repair and growth." },
  { chapter: 14, term: "Essential amino acids", definition: "Nine amino acids that cannot be synthesized by the body and must be obtained through diet: histidine, isoleucine, leucine, lysine, methionine, phenylalanine, threonine, tryptophan, valine." },
  { chapter: 14, term: "Hydration guidelines", definition: "Drink approximately 14-22 oz of water 2 hours before exercise. During exercise, drink 6-12 oz every 15-20 minutes. After exercise, drink 16-24 oz per pound of body weight lost." },
  { chapter: 14, term: "Total Daily Energy Expenditure (TDEE)", definition: "The total number of calories burned in a day, comprising resting metabolic rate (RMR), thermic effect of food (TEF), and thermic effect of physical activity (TEPA)." },
  { chapter: 14, term: "Resting metabolic rate (RMR)", definition: "The number of calories the body requires at rest to maintain normal physiological functions. Accounts for approximately 70% of TDEE." },
  { chapter: 14, term: "Thermic effect of food (TEF)", definition: "The energy expended during digestion, absorption, and metabolism of food. Accounts for approximately 10% of TDEE. Protein has the highest thermic effect." },
  { chapter: 14, term: "Saturated vs. unsaturated fat", definition: "Saturated fats (solid at room temperature, animal sources) may raise LDL cholesterol. Unsaturated fats (liquid at room temperature, plant/fish sources) support heart health." },
  { chapter: 14, term: "Fiber", definition: "An indigestible carbohydrate that supports digestive health, helps regulate blood sugar, and promotes satiety. Recommended intake: 25-38 g/day." },
  { chapter: 14, term: "Nutrient timing", definition: "Strategically consuming nutrients around exercise to optimize performance and recovery. A combination of protein and carbohydrates within 1-2 hours post-exercise supports glycogen replenishment and muscle repair." },
  { chapter: 14, term: "Caloric surplus and deficit", definition: "A surplus (consuming more calories than TDEE) promotes weight gain; a deficit (consuming fewer calories than TDEE) promotes weight loss. ~3,500 kcal ≈ 1 lb of body fat." },
  { chapter: 14, term: "Scope of practice for nutrition", definition: "Personal trainers can provide general nutritional information (MyPlate guidelines, food labels) but cannot prescribe specific diets or meal plans unless also a licensed/registered dietitian." },
  { chapter: 14, term: "Water functions in the body", definition: "Regulates body temperature, transports nutrients and oxygen, cushions organs and joints, removes waste products. The body is approximately 60% water." },

  // ── Chapter 15: Supplements ───────────────────────────────────────
  { chapter: 15, term: "Dietary supplement", definition: "A product taken by mouth intended to supplement the diet, including vitamins, minerals, herbs, amino acids, and enzymes. Regulated under DSHEA, not evaluated by the FDA for efficacy before sale." },
  { chapter: 15, term: "Creatine monohydrate", definition: "One of the most researched supplements; increases phosphocreatine stores in muscle, improving short-duration, high-intensity exercise performance. Typical dose: 3-5 g/day after loading." },
  { chapter: 15, term: "Whey protein", definition: "A fast-digesting, complete protein derived from milk. Rich in branched-chain amino acids (BCAAs), especially leucine. Commonly used post-exercise for muscle protein synthesis." },
  { chapter: 15, term: "Casein protein", definition: "A slow-digesting milk protein that provides a sustained release of amino acids. Often consumed before sleep to support overnight muscle recovery." },
  { chapter: 15, term: "Branched-chain amino acids (BCAAs)", definition: "Three essential amino acids — leucine, isoleucine, and valine — that play a key role in muscle protein synthesis. Leucine is the primary trigger for MPS." },
  { chapter: 15, term: "Caffeine as ergogenic aid", definition: "A stimulant that can improve endurance performance, increase alertness, and reduce perceived exertion. Effective dose: approximately 3-6 mg/kg body weight taken 30-60 min before exercise." },
  { chapter: 15, term: "Beta-alanine", definition: "An amino acid supplement that increases intramuscular carnosine levels, buffering hydrogen ions during high-intensity exercise. May reduce fatigue and improve performance in efforts lasting 1-4 minutes." },
  { chapter: 15, term: "Ergogenic aid", definition: "Any substance, device, or practice that enhances energy production, use, or recovery to improve physical performance." },
  { chapter: 15, term: "DSHEA (1994)", definition: "Dietary Supplement Health and Education Act — the federal law that regulates supplements as foods, not drugs. Manufacturers are responsible for safety; the FDA does not approve supplements before sale." },
  { chapter: 15, term: "Vitamin D", definition: "A fat-soluble vitamin essential for calcium absorption, bone health, and immune function. Deficiency is common, especially in those with limited sun exposure." },
  { chapter: 15, term: "Iron", definition: "A mineral essential for oxygen transport in hemoglobin and myoglobin. Deficiency can cause fatigue and impaired exercise performance, particularly in female athletes." },
  { chapter: 15, term: "Sodium bicarbonate", definition: "An extracellular buffer supplement that may improve performance in high-intensity exercise lasting 1-7 minutes by buffering lactic acid accumulation." },
  { chapter: 15, term: "Third-party supplement testing", definition: "Independent organizations (NSF Certified for Sport, Informed Sport, USP) test supplements for banned substances, label accuracy, and contaminants. Recommended for athletes and clients." },
  { chapter: 15, term: "Omega-3 fatty acids", definition: "Essential polyunsaturated fats (EPA and DHA) found in fish oil. Associated with reduced inflammation, improved cardiovascular health, and potential benefits for joint health." },
  { chapter: 15, term: "Multivitamin/mineral supplement", definition: "A general supplement providing a range of essential vitamins and minerals. May help fill dietary gaps but is not a substitute for a balanced diet." },

  // ── Chapter 16: Behavioral Coaching ───────────────────────────────
  { chapter: 16, term: "Transtheoretical model (Stages of Change)", definition: "A behavior change model with five stages: precontemplation, contemplation, preparation, action, and maintenance. Helps trainers tailor strategies to a client's readiness." },
  { chapter: 16, term: "Precontemplation stage", definition: "The person is not yet considering change and may be unaware of the need. They have no intention to take action within the next 6 months." },
  { chapter: 16, term: "Contemplation stage", definition: "The person acknowledges a problem and is thinking about change but has not committed. Intends to take action within the next 6 months." },
  { chapter: 16, term: "Preparation stage", definition: "The person intends to take action soon (within the next month) and may begin taking small steps, such as joining a gym." },
  { chapter: 16, term: "Action stage", definition: "The person has made specific, overt lifestyle modifications within the last 6 months but the behavior is not yet habitual." },
  { chapter: 16, term: "Maintenance stage", definition: "The person has sustained the behavior change for more than 6 months and is working to prevent relapse." },
  { chapter: 16, term: "SMART goals", definition: "Goals that are Specific, Measurable, Attainable, Realistic, and Time-bound. Help clients create clear, achievable objectives." },
  { chapter: 16, term: "Self-efficacy", definition: "A person's belief in their ability to succeed in a specific situation or accomplish a task. Higher self-efficacy correlates with greater adherence to exercise programs." },
  { chapter: 16, term: "Motivational interviewing", definition: "A client-centered counseling style that helps resolve ambivalence about change by exploring and enhancing the client's own motivation and reasons for change." },
  { chapter: 16, term: "Decisional balance", definition: "A cognitive process of weighing the pros and cons of behavior change. Used in the contemplation stage to help clients see that benefits outweigh costs." },
  { chapter: 16, term: "Relapse", definition: "A return to previous unhealthy behaviors after a period of change. It is a normal part of the change process, not a failure. Trainers should help clients re-enter the cycle." },
  { chapter: 16, term: "Cognitive strategies", definition: "Mental techniques such as visualization, positive self-talk, and psyching up that help clients stay motivated and overcome barriers to exercise." },
  { chapter: 16, term: "Extrinsic vs. intrinsic motivation", definition: "Extrinsic motivation comes from external rewards (praise, appearance). Intrinsic motivation comes from internal satisfaction (enjoyment, sense of accomplishment). Long-term adherence is driven more by intrinsic motivation." },
  { chapter: 16, term: "Social support", definition: "Encouragement from friends, family, or training partners that improves exercise adherence. Trainers can build this through group settings and accountability." },
  { chapter: 16, term: "Rapport", definition: "A trusting, respectful relationship between trainer and client. Built through active listening, empathy, professionalism, and genuine interest in the client's goals." },

  // ── Chapter 17: Special Populations ────────────────────────────────
  { chapter: 17, term: "Youth training guidelines", definition: "Emphasize proper technique, body-weight exercises, and fun. Avoid maximal lifts. Use higher reps (12-20), lighter loads, and focus on neuromuscular control and movement competency." },
  { chapter: 17, term: "Senior training guidelines", definition: "Focus on functional capacity, balance, and fall prevention. Start with Phase 1 (Stabilization Endurance). Emphasize proper breathing (no Valsalva), controlled tempo, and joint-friendly exercises." },
  { chapter: 17, term: "Prenatal exercise guidelines", definition: "Moderate-intensity exercise is generally safe and recommended. Avoid supine positions after the first trimester, high-impact activities, and exercises with fall risk. Monitor heart rate and perceived exertion." },
  { chapter: 17, term: "Postnatal exercise guidelines", definition: "Gradually return to exercise after medical clearance (typically 4-6 weeks postpartum). Focus on core stabilization, pelvic floor strengthening, and rebuilding aerobic fitness progressively." },
  { chapter: 17, term: "Obesity training guidelines", definition: "Begin with low-to-moderate intensity, longer-duration cardio. Emphasize non-weight-bearing activities initially (cycling, swimming). Progress slowly. Combine with nutritional guidance within scope." },
  { chapter: 17, term: "Sarcopenia", definition: "The age-related loss of skeletal muscle mass, strength, and function. Resistance training is one of the most effective interventions to slow or reverse sarcopenia." },
  { chapter: 17, term: "Osteopenia", definition: "A condition of reduced bone mineral density that precedes osteoporosis. Weight-bearing and resistance exercises help maintain and increase bone density." },
  { chapter: 17, term: "BMI (Body Mass Index)", definition: "A screening tool calculated as weight (kg) / height (m²). Categories: underweight < 18.5, normal 18.5-24.9, overweight 25-29.9, obese ≥ 30. Does not distinguish fat from muscle." },
  { chapter: 17, term: "Valsalva maneuver", definition: "Holding breath and bearing down during exertion. Can dangerously increase blood pressure. Should be avoided, especially in senior and hypertensive populations." },
  { chapter: 17, term: "Balance training for seniors", definition: "Single-leg stands, tandem stance, and stability ball exercises reduce fall risk. Progress from stable surfaces to unstable surfaces as competency increases." },
  { chapter: 17, term: "Youth resistance training misconceptions", definition: "Properly supervised resistance training does NOT stunt growth. It improves bone density, motor skills, and self-confidence when age-appropriate guidelines are followed." },
  { chapter: 17, term: "Rating of Perceived Exertion (RPE)", definition: "A subjective 1-10 scale used to gauge exercise intensity. Especially useful for special populations where heart rate monitoring may be unreliable." },
  { chapter: 17, term: "Thermoregulation in special populations", definition: "Youth and seniors have impaired thermoregulation. Extra precautions needed in hot/cold environments: adequate hydration, appropriate clothing, shorter outdoor sessions." },
  { chapter: 17, term: "Exercise and gestational diabetes", definition: "Regular moderate exercise during pregnancy can help regulate blood glucose and reduce the risk of gestational diabetes mellitus." },
  { chapter: 17, term: "Progressive overload for obese clients", definition: "Increase duration before intensity. Start with 10-20 minutes and build to 30-60 minutes per session. Reduce joint stress with non-impact modalities." },

  // ── Chapter 18: Chronic Conditions ────────────────────────────────
  { chapter: 18, term: "Diabetes mellitus (Type 1 vs. Type 2)", definition: "Type 1: autoimmune destruction of pancreatic beta cells, requiring insulin. Type 2: insulin resistance, often linked to obesity and inactivity. Exercise improves insulin sensitivity in both types." },
  { chapter: 18, term: "Hypertension", definition: "Chronically elevated blood pressure (≥ 130/80 mmHg per current guidelines). Exercise reduces resting blood pressure by approximately 5-7 mmHg. Avoid heavy lifting and Valsalva." },
  { chapter: 18, term: "Coronary heart disease (CHD)", definition: "A condition caused by plaque buildup in the coronary arteries, reducing blood flow to the heart. Risk factors include hypertension, dyslipidemia, diabetes, smoking, obesity, and inactivity." },
  { chapter: 18, term: "Osteoporosis", definition: "A disease characterized by low bone mass and deterioration of bone tissue, increasing fracture risk. Weight-bearing exercise and resistance training help maintain bone density." },
  { chapter: 18, term: "Arthritis (osteoarthritis vs. rheumatoid)", definition: "Osteoarthritis: degenerative joint disease from wear and tear. Rheumatoid: autoimmune condition causing joint inflammation. Both benefit from low-impact exercise; avoid training during acute flare-ups." },
  { chapter: 18, term: "Chronic obstructive pulmonary disease (COPD)", definition: "A group of progressive lung diseases (emphysema, chronic bronchitis) that limit airflow. Exercise improves functional capacity and quality of life; use RPE to monitor intensity." },
  { chapter: 18, term: "Hypoglycemia during exercise (diabetes)", definition: "Dangerously low blood glucose that can occur during exercise in diabetic clients, especially those on insulin. Signs: dizziness, shakiness, confusion. Have fast-acting carbohydrates available." },
  { chapter: 18, term: "Dyslipidemia", definition: "Abnormal blood lipid levels (elevated LDL, elevated triglycerides, low HDL). Regular aerobic exercise can improve lipid profiles by raising HDL and lowering LDL and triglycerides." },
  { chapter: 18, term: "Peripheral artery disease (PAD)", definition: "Narrowing of peripheral arteries reducing blood flow to the extremities. Walking programs can improve claudication symptoms and functional capacity." },
  { chapter: 18, term: "Exercise and blood glucose monitoring", definition: "Diabetic clients should check blood glucose before, during, and after exercise. Avoid exercise if glucose is above 250 mg/dL with ketones or below 100 mg/dL without a snack." },
  { chapter: 18, term: "Metabolic syndrome", definition: "A cluster of conditions — elevated waist circumference, high triglycerides, low HDL, high blood pressure, and high fasting glucose — that increase risk for CHD and Type 2 diabetes." },
  { chapter: 18, term: "Physician clearance", definition: "Medical approval required before beginning an exercise program for clients with known chronic conditions. The PAR-Q+ and health history questionnaire help identify those who need clearance." },
  { chapter: 18, term: "Exercise guidelines for hypertension", definition: "Moderate-intensity aerobic exercise most days of the week. Avoid isometric exercises and heavy resistance. Keep intensity moderate and monitor blood pressure response." },
  { chapter: 18, term: "Osteoporosis exercise contraindications", definition: "Avoid excessive spinal flexion, high-impact activities, and explosive movements that increase fracture risk. Focus on weight-bearing, resistance, and balance exercises." },
  { chapter: 18, term: "Cardiac rehabilitation", definition: "A medically supervised program for individuals recovering from cardiac events. Trainers may work with post-rehab clients with physician clearance, starting conservatively." },

  // ── Chapter 19: Professional Development ──────────────────────────
  { chapter: 19, term: "Scope of practice", definition: "The legal and professional boundaries that define the services a personal trainer can provide. Trainers should not diagnose injuries, prescribe diets, or provide therapy." },
  { chapter: 19, term: "Professional liability insurance", definition: "Insurance that protects personal trainers from financial loss due to claims of negligence or injury. All trainers should carry their own policy regardless of employer coverage." },
  { chapter: 19, term: "Negligence", definition: "The failure to act with reasonable care, resulting in harm. Four elements: duty, breach of duty, cause, and damages. Proper documentation and certifications reduce negligence risk." },
  { chapter: 19, term: "Informed consent", definition: "A document that explains the risks, benefits, and procedures of an exercise program. Must be signed by the client before beginning training. Does not waive the trainer's duty of care." },
  { chapter: 19, term: "Confidentiality (HIPAA)", definition: "Personal trainers must protect all client health information. Sharing medical or personal data without consent is both unethical and potentially illegal." },
  { chapter: 19, term: "Active listening", definition: "A communication skill where the trainer fully concentrates on what the client is saying, reflects back, and asks clarifying questions. Builds trust and rapport." },
  { chapter: 19, term: "Continuing education (CEUs)", definition: "Ongoing education credits required to maintain NASM certification. Ensures trainers stay current with evolving science, techniques, and best practices." },
  { chapter: 19, term: "Ethics in personal training", definition: "Professional conduct standards including honesty, integrity, respecting client boundaries, maintaining confidentiality, avoiding dual relationships, and staying within scope of practice." },
  { chapter: 19, term: "Assumption of risk / waiver", definition: "A legal document in which the client acknowledges the inherent risks of exercise. Provides some legal protection but does not protect against trainer negligence." },
  { chapter: 19, term: "Proper documentation", definition: "Trainers should maintain records of assessments, programs, progress, incident reports, and client communications. Protects both the trainer and client legally." },
  { chapter: 19, term: "Emergency action plan", definition: "A written plan that outlines procedures for responding to emergencies in a fitness facility, including roles, communication, and equipment locations." },
  { chapter: 19, term: "Professional appearance and conduct", definition: "Maintaining a clean, professional appearance, being punctual, using appropriate language, and demonstrating competence all contribute to client trust and retention." },
  { chapter: 19, term: "Referral network", definition: "A network of allied health professionals (physicians, dietitians, physical therapists, psychologists) to whom trainers can refer clients for services outside their scope." },
  { chapter: 19, term: "Dual relationship", definition: "A situation where a trainer has both a professional and personal relationship with a client (e.g., romantic, business). Should be avoided as it compromises professional judgment." },
  { chapter: 19, term: "CPR/AED certification", definition: "A required certification for personal trainers that ensures competency in performing cardiopulmonary resuscitation and using an automated external defibrillator in emergencies." },

  // ── Chapter 20: Business Development ──────────────────────────────
  { chapter: 20, term: "Client acquisition", definition: "The process of attracting and securing new clients through marketing, networking, referrals, complimentary sessions, and community engagement." },
  { chapter: 20, term: "Client retention", definition: "Strategies for keeping clients long-term, including delivering results, building rapport, providing excellent customer service, tracking progress, and maintaining consistent communication." },
  { chapter: 20, term: "Sales process for personal training", definition: "A systematic approach: build rapport → identify needs/goals → present solutions → handle objections → close → follow up. Focus on the client's needs, not the product." },
  { chapter: 20, term: "Elevator pitch", definition: "A brief (30-60 second) personal introduction that communicates who you are, what you do, and how you help clients. Should be clear, confident, and tailored to the audience." },
  { chapter: 20, term: "Closing the sale", definition: "The step in the sales process where the trainer asks the client to commit. Techniques include the assumptive close, the direct close, and the choice close." },
  { chapter: 20, term: "Handling objections", definition: "Responding to client concerns (cost, time, uncertainty) with empathy, reframing, and solution-focused responses. Listen first, then address the underlying concern." },
  { chapter: 20, term: "Referral system", definition: "A structured strategy for encouraging existing clients to refer friends and family. Incentives, social proof, and delivering great results drive referrals." },
  { chapter: 20, term: "Social media marketing", definition: "Using platforms (Instagram, Facebook, YouTube) to build brand awareness, share expertise, showcase client transformations, and attract potential clients." },
  { chapter: 20, term: "Programming for client goals", definition: "Designing individualized exercise programs based on the client's assessment results, goals, preferences, and lifestyle. Ensures relevance, safety, and adherence." },
  { chapter: 20, term: "Revenue streams for trainers", definition: "Income sources including one-on-one training, small group training, online coaching, workshops, corporate wellness, and digital products (programs, e-books)." },
  { chapter: 20, term: "Professionalism in business", definition: "Treating personal training as a business: tracking finances, setting goals, managing time effectively, investing in continuing education, and maintaining high ethical standards." },
  { chapter: 20, term: "Complimentary session", definition: "A free introductory training session used to demonstrate value, build rapport, perform initial assessments, and convert prospects into paying clients." },
  { chapter: 20, term: "Tracking client progress", definition: "Regularly reassessing clients through body composition measurements, fitness assessments, and performance benchmarks. Demonstrates results and justifies continued investment." },
  { chapter: 20, term: "Time management for trainers", definition: "Prioritizing income-producing activities (training, follow-ups, prospecting) and scheduling administrative tasks efficiently. Prevents burnout and maximizes revenue." },
  { chapter: 20, term: "Building a personal brand", definition: "Establishing a unique professional identity through consistent messaging, specialization, visible expertise, and delivering a consistent client experience." },
];
