export interface ChapterContext {
  title: string;
  keyConcepts: string[];
  commonMisconceptions: string[];
  examPatterns: string[];
  socraticStarters: string[];
}

const chapterContexts: Record<number, ChapterContext> = {
  1: {
    title: "The Scientific Rationale for Integrated Training",
    keyConcepts: [
      "The OPT model has 3 levels (Stabilization, Strength, Power) and 5 phases",
      "Evidence-based practice combines research, clinical expertise, and client values",
      "Integrated training addresses all components: flexibility, cardio, core, balance, plyometrics, SAQ, and resistance",
      "Periodization is the systematic planning of training over specific time periods",
      "The OPT model is designed for ANY client regardless of fitness level",
    ],
    commonMisconceptions: [
      "Thinking the OPT model is only for beginners — it applies to all fitness levels including athletes",
      "Believing clients must go through all 5 phases — some clients may cycle between phases based on goals",
      "Confusing the 3 levels with the 5 phases — levels are categories, phases are specific stages",
      "Assuming integrated training means doing everything every session — it means programming all modalities over time",
      "Thinking evidence-based practice means only following research — it also includes trainer expertise and client preferences",
    ],
    examPatterns: [
      "Which phase of the OPT model is appropriate for a new client? (Answer: Phase 1 - Stabilization Endurance)",
      "Questions asking you to match OPT phases to their correct level (Stabilization, Strength, or Power)",
      "Identifying the correct order of the 5 OPT phases",
      "Scenario questions about when to progress or regress a client within the OPT model",
    ],
    socraticStarters: [
      "Can you walk me through the 5 phases of the OPT model and explain why they're in that specific order?",
      "Why do you think NASM requires ALL clients to start in Phase 1, even if they're already fit?",
      "What does 'integrated training' actually mean, and how is it different from just doing a workout?",
      "If a client says they only want to lift heavy, how would you use the OPT model to explain your programming?",
      "What makes the OPT model 'evidence-based' rather than just another training system?",
    ],
  },
  2: {
    title: "Basic Exercise Science",
    keyConcepts: [
      "Motor unit = motor neuron + all muscle fibers it innervates",
      "Type I fibers: slow-twitch, fatigue-resistant, endurance. Type II: fast-twitch, powerful, fatigue quickly",
      "Sliding filament theory: actin and myosin slide past each other to produce contraction",
      "Size principle: smaller motor units (Type I) recruited first, Type II recruited as intensity increases",
      "Three contraction types: concentric (shortening), eccentric (lengthening), isometric (no change)",
      "Neuromuscular junction: where motor neuron meets muscle fiber via acetylcholine",
    ],
    commonMisconceptions: [
      "Thinking Type II fibers are 'better' than Type I — each type serves essential functions",
      "Believing eccentric contractions are less important — they actually produce more force than concentric",
      "Confusing motor units with muscle fibers — a motor unit includes the neuron AND its fibers",
      "Thinking all Type II fibers are the same — Type IIa are more oxidative, Type IIx are most powerful",
      "Assuming the nervous system and muscular system work independently — they are fully integrated",
    ],
    examPatterns: [
      "Which muscle fiber type is recruited first during low-intensity exercise? (Type I - size principle)",
      "What is the functional unit of the neuromuscular system? (Motor unit)",
      "During a bicep curl lowering phase, what type of contraction is occurring? (Eccentric)",
      "Which muscle is the antagonist during [specific exercise]?",
      "Questions about the sliding filament theory and the role of actin/myosin",
    ],
    socraticStarters: [
      "Can you explain what happens at the neuromuscular junction when your brain decides to move your arm?",
      "If Type I fibers are recruited first, what does that tell us about how we should warm up?",
      "What's actually happening inside a muscle fiber when it contracts — can you walk through the sliding filament theory?",
      "Why do you think eccentric contractions can produce more force than concentric ones?",
      "How does the size principle affect the way we design training programs for different goals?",
    ],
  },
  3: {
    title: "The Cardiorespiratory System",
    keyConcepts: [
      "Cardiac output = Heart Rate x Stroke Volume (Q = HR x SV)",
      "VO2 max is the gold standard measure of cardiorespiratory fitness (mL/kg/min)",
      "Karvonen formula: THR = ((HRmax - HRrest) x %intensity) + HRrest",
      "Three energy systems: ATP-PC (immediate), glycolysis (short-term), oxidative (long-term)",
      "Heart rate training zones: Zone 1 (65-75%), Zone 2 (76-85%), Zone 3 (86-95% HRmax)",
      "Blood pressure = cardiac output x peripheral resistance",
    ],
    commonMisconceptions: [
      "Thinking HRmax = 220 - age is perfectly accurate — it's an estimate with significant individual variation",
      "Confusing stroke volume with cardiac output — SV is per beat, CO is per minute",
      "Believing the 'fat-burning zone' means low intensity burns more total fat — higher intensity burns more total calories",
      "Thinking VO2 max and HRmax are the same thing — VO2 max is oxygen consumption, HRmax is heart rate",
      "Assuming ventilatory threshold and lactate threshold are identical — they're related but measured differently",
    ],
    examPatterns: [
      "Calculate target heart rate using the Karvonen formula given HRmax, HRrest, and desired intensity",
      "What is the formula for cardiac output? (Q = HR x SV)",
      "Which energy system is predominant during a 30-second sprint? (Anaerobic glycolysis)",
      "A client with a resting HR of 70 and HRmax of 190 wants to train at 70% intensity. What is their THR?",
    ],
    socraticStarters: [
      "If cardiac output equals heart rate times stroke volume, what happens to each variable when you start exercising?",
      "Why does NASM use the Karvonen formula instead of just a percentage of max heart rate?",
      "Can you explain why someone with a higher VO2 max would have better endurance?",
      "What determines which energy system your body primarily uses during exercise?",
      "How does blood pressure respond during resistance training versus cardio, and why does that matter for program design?",
    ],
  },
  4: {
    title: "Exercise Metabolism and Bioenergetics",
    keyConcepts: [
      "ATP is the universal energy currency of cells",
      "ATP-PC system: immediate energy for 0-15 seconds of high-intensity work",
      "Anaerobic glycolysis: 30 seconds to 2 minutes, produces lactate",
      "Oxidative system: sustained activity over 2-3 minutes, uses carbs/fats/proteins",
      "All three systems are always active — predominance depends on intensity and duration",
      "EPOC (excess post-exercise oxygen consumption) is greater after high-intensity exercise",
    ],
    commonMisconceptions: [
      "Thinking only one energy system works at a time — all three are always contributing",
      "Believing lactate causes muscle soreness — DOMS is from eccentric muscle damage, not lactate",
      "Assuming fat burning only happens during low-intensity exercise — fat is also used at higher intensities",
      "Confusing the ATP-PC system with glycolysis — ATP-PC doesn't use glucose",
      "Thinking EPOC means you burn tons of calories after exercise — the effect is real but often exaggerated",
    ],
    examPatterns: [
      "During a 10-second maximal sprint, which energy system is predominant? (ATP-PC/phosphagen)",
      "Which macronutrient provides the most ATP per molecule? (Fat)",
      "A client performs a 60-second high-intensity interval. Which energy system is primary? (Glycolysis)",
      "What is the byproduct of anaerobic glycolysis? (Lactate)",
      "Which system requires oxygen to produce ATP? (Oxidative system)",
    ],
    socraticStarters: [
      "If all three energy systems are always active, what determines which one is 'in charge' at any moment?",
      "Why do you think short, intense exercises like sprints make you breathe hard AFTER you stop?",
      "Can you trace the path of a glucose molecule from digestion to becoming ATP in a muscle cell?",
      "Why does fat provide more ATP per molecule than carbohydrate, but carbs are preferred for high-intensity work?",
      "How would understanding energy systems change the way you design rest intervals for a client?",
    ],
  },
  5: {
    title: "Human Movement Science",
    keyConcepts: [
      "Kinetic chain: body is an interconnected system — dysfunction at one link affects the whole chain",
      "Muscle roles: agonist (prime mover), antagonist (opposes), synergist (assists), stabilizer (supports)",
      "Three planes of motion: sagittal (flexion/extension), frontal (abduction/adduction), transverse (rotation)",
      "Length-tension relationship: muscles produce max force at optimal resting length",
      "Force-couple: muscles working together around a joint to produce movement",
      "Altered length-tension relationships lead to dysfunctional movement patterns",
    ],
    commonMisconceptions: [
      "Thinking agonist/antagonist relationships are fixed — they change depending on the movement",
      "Believing frontal plane only means side-to-side — it includes any abduction/adduction movement",
      "Confusing synergists with stabilizers — synergists help produce movement, stabilizers prevent unwanted movement",
      "Thinking muscle imbalances are always obvious — subclinical imbalances cause subtle compensations",
      "Assuming the kinetic chain only applies during exercise — it affects all daily movement patterns",
    ],
    examPatterns: [
      "During a bicep curl, which muscle is the antagonist? (Triceps)",
      "A squat occurs primarily in which plane of motion? (Sagittal)",
      "Which type of muscle action is the hamstring performing during the lowering phase of a leg curl? (Eccentric)",
      "What happens to force production when a muscle is chronically shortened? (Decreased — altered length-tension)",
      "Identify the agonist, antagonist, and synergist for a given exercise",
    ],
    socraticStarters: [
      "If I asked you to identify all the muscle roles during a push-up, where would you start?",
      "Why does a tight hip flexor often lead to low back pain — can you trace that through the kinetic chain?",
      "What's the practical difference between a synergist and a stabilizer during a bench press?",
      "How does the length-tension relationship explain why posture affects strength?",
      "Can you give me an example of a force-couple and explain why both muscles need to work together?",
    ],
  },
  6: {
    title: "Fitness Assessment",
    keyConcepts: [
      "Overhead squat assessment (OHSA) evaluates dynamic flexibility, core strength, and neuromuscular control",
      "OHSA is observed from anterior, lateral, and posterior views",
      "Common compensations: feet turn out, knees move inward (valgus), excessive forward lean, arms fall forward",
      "Subjective assessments (PAR-Q, health history) come BEFORE objective assessments",
      "Reassessment every 4 weeks to track progress",
      "Movement compensations indicate specific overactive and underactive muscles",
    ],
    commonMisconceptions: [
      "Thinking knee valgus only means weak glutes — it involves overactive adductors/TFL and underactive glute med/VMO",
      "Believing the overhead squat assessment diagnoses injuries — it identifies movement compensations, not pathology",
      "Assuming all compensations need to be fixed before training — you program around them while addressing them",
      "Thinking body composition is the most important assessment — movement quality is the priority",
      "Confusing overactive with strong and underactive with weak — overactive muscles are often tight AND weak",
    ],
    examPatterns: [
      "During an overhead squat, the client's knees move inward. Which muscles are likely overactive? (Adductors, TFL, lateral gastrocnemius)",
      "During an overhead squat, the client's low back arges excessively. Which muscles are likely underactive? (Core stabilizers, gluteus maximus)",
      "Which assessment should be performed first? (Subjective — PAR-Q, health history)",
      "A client's feet turn out during the OHSA. Which muscles should be foam rolled? (Lateral gastrocnemius, soleus, biceps femoris)",
      "What does excessive forward lean during the OHSA indicate? (Overactive hip flexors/soleus, underactive glute max/erector spinae)",
    ],
    socraticStarters: [
      "If you see a client's knees cave inward during an overhead squat, can you trace what's happening muscularly?",
      "Why do we observe the overhead squat from three different views instead of just one?",
      "What's the difference between a compensation and an injury, and why does that matter for a trainer?",
      "If a client shows excessive forward lean in the OHSA, what would your corrective strategy look like?",
      "Why does NASM insist on subjective assessments before any physical testing?",
    ],
  },
  7: {
    title: "Flexibility Training Concepts",
    keyConcepts: [
      "Three flexibility techniques in OPT: SMR (foam rolling), static stretching, dynamic stretching",
      "Autogenic inhibition: GTO stimulation causes muscle relaxation (mechanism behind SMR)",
      "Reciprocal inhibition: contracting agonist causes antagonist to relax",
      "Corrective flexibility (Phase 1): SMR + static stretching for overactive muscles",
      "Active flexibility (Phases 2-4): SMR + dynamic stretching",
      "SMR held 30-90 seconds; static stretches held 30 seconds",
    ],
    commonMisconceptions: [
      "Thinking foam rolling breaks up scar tissue or fascia — it works through neurological mechanisms (autogenic inhibition)",
      "Believing static stretching before exercise improves performance — it can temporarily reduce force production",
      "Confusing autogenic and reciprocal inhibition — autogenic is same muscle relaxing, reciprocal is opposite muscle relaxing",
      "Assuming flexibility training is optional — it's integral to every OPT phase",
      "Thinking more stretching is always better — overstretching can decrease joint stability",
    ],
    examPatterns: [
      "Which flexibility technique is used in Phase 1 of the OPT model? (Corrective: SMR + static stretching)",
      "What neurological mechanism makes foam rolling effective? (Autogenic inhibition via GTO)",
      "How long should a static stretch be held? (30 seconds)",
      "A client has overactive calves identified in the OHSA. What flexibility techniques should be applied? (SMR calves + static stretch calves)",
      "What is the principle behind reciprocal inhibition? (Contracting one muscle causes the opposing muscle to relax)",
    ],
    socraticStarters: [
      "Can you explain the difference between autogenic inhibition and reciprocal inhibition using a real example?",
      "Why does NASM pair SMR with static stretching in Phase 1 but switch to dynamic stretching in later phases?",
      "If foam rolling doesn't physically break up tissue, how does it actually reduce muscle tension?",
      "When would static stretching be counterproductive, and why?",
      "How would you design a flexibility warm-up for a client in Phase 3 of the OPT model?",
    ],
  },
  8: {
    title: "Cardiorespiratory Fitness Training",
    keyConcepts: [
      "Stage I: base training, Zone 1 (65-75% HRmax), for deconditioned clients",
      "Stage II: aerobic efficiency, alternating Zone 1 and Zone 2 (76-85% HRmax)",
      "Stage III: anaerobic training, incorporating Zone 3 (86-95% HRmax) intervals",
      "FITTE-VP: Frequency, Intensity, Time, Type, Enjoyment, Volume, Progression",
      "150 min/week moderate OR 75 min/week vigorous cardio recommended",
      "Talk test: comfortable conversation = Zone 1, short sentences = Zone 2, can't talk = Zone 3",
    ],
    commonMisconceptions: [
      "Thinking HIIT is appropriate for all clients — beginners should start with Stage I steady-state",
      "Believing more cardio always equals more fat loss — intensity, duration, and nutrition all matter",
      "Confusing heart rate zones with training stages — zones are intensity ranges, stages are programming progressions",
      "Assuming the talk test is not a valid intensity measure — it correlates well with ventilatory threshold",
      "Thinking cardio training should be separate from resistance training — NASM integrates both in the OPT model",
    ],
    examPatterns: [
      "A sedentary client begins a cardio program. Which stage should they start in? (Stage I)",
      "What heart rate zone is associated with Stage II training? (Zones 1 and 2)",
      "Calculate a client's Zone 1 heart rate range given their age and resting heart rate",
      "What does FITTE-VP stand for?",
      "Which stage of cardiorespiratory training uses Zone 3 intervals? (Stage III)",
    ],
    socraticStarters: [
      "Why does NASM start deconditioned clients in Stage I instead of jumping to intervals?",
      "How would you explain heart rate zones to a client who has never used a heart rate monitor?",
      "What's the relationship between the three cardio stages and the OPT model phases?",
      "If a client can hold a conversation during their workout, what does that tell you about their training zone?",
      "How would you progress a client from Stage I to Stage II — what markers would you look for?",
    ],
  },
  9: {
    title: "Core Training Concepts",
    keyConcepts: [
      "Core = LPHC (lumbo-pelvic-hip complex), thoracic spine, and cervical spine",
      "Drawing-in maneuver activates deep stabilizers (transverse abdominis, multifidus, pelvic floor)",
      "Bracing = co-contraction of global muscles for heavy lifting",
      "Local stabilization system: deep muscles for intervertebral stability",
      "Global stabilization system: pelvis-to-spine muscles for LPHC stability",
      "Core progression: stabilization (planks) -> strength (ball crunches) -> power (med ball throws)",
    ],
    commonMisconceptions: [
      "Thinking 'core' means just the abs — it includes the entire LPHC, thoracic, and cervical spine",
      "Believing crunches are the best core exercise — stabilization exercises are foundational",
      "Confusing the drawing-in maneuver with sucking in your stomach — it's a subtle activation of deep muscles",
      "Thinking core power exercises should come first — stabilization must be established before power",
      "Assuming a strong core means a visible six-pack — core function is about stability and force transfer",
    ],
    examPatterns: [
      "Which muscles are activated during the drawing-in maneuver? (Transverse abdominis, multifidus, pelvic floor)",
      "In which OPT phase would you program a plank? (Phase 1 — core stabilization)",
      "What is the difference between drawing-in and bracing?",
      "A medicine ball rotation throw is an example of which type of core exercise? (Core power — Phase 5)",
      "Which system provides intervertebral stability? (Local stabilization system)",
    ],
    socraticStarters: [
      "Why does NASM define the core as more than just the abdominal muscles?",
      "Can you explain the difference between the drawing-in maneuver and bracing — when would you use each?",
      "Why is core stabilization the foundation before adding core strength or power exercises?",
      "How does a weak core affect movements in the upper and lower body?",
      "If a client can hold a plank for 2 minutes, does that mean their core is 'strong enough' to progress?",
    ],
  },
  10: {
    title: "Balance Training Concepts",
    keyConcepts: [
      "Balance = maintaining center of gravity over base of support",
      "Three sensory systems: visual, vestibular (inner ear), somatosensory (proprioceptors)",
      "Balance stabilization (Phase 1): static holds on unstable surfaces",
      "Balance strength (Phases 2-4): dynamic movements through full ROM",
      "Balance power (Phase 5): explosive movements with controlled landings",
      "Progress by reducing base of support, changing surfaces, or removing visual input",
    ],
    commonMisconceptions: [
      "Thinking balance training is only for elderly clients — it benefits all populations",
      "Believing unstable surface training always improves performance — it's specific to the training phase",
      "Confusing proprioception with balance — proprioception is one component of balance",
      "Assuming balance can't be trained — it improves significantly with progressive training",
      "Thinking balance exercises are too easy for athletic clients — they can be highly challenging when progressed",
    ],
    examPatterns: [
      "Which three sensory systems contribute to balance? (Visual, vestibular, somatosensory)",
      "A single-leg balance on a foam pad is an example of which type of balance training? (Balance stabilization)",
      "How should balance exercises be progressed? (Reduce base of support, change surface, remove visual input)",
      "A hop to stabilization drill is an example of which balance phase? (Balance power — Phase 5)",
      "What is the center of gravity approximately located? (Second sacral vertebra)",
    ],
    socraticStarters: [
      "Why does NASM include balance training for all clients, not just older adults?",
      "How do the visual, vestibular, and somatosensory systems work together to maintain balance?",
      "What happens to your balance if you close your eyes — and what does that tell us about sensory reliance?",
      "How would you progress a balance exercise for a client who has mastered single-leg stance?",
      "Why is a hop-to-stabilization considered a power balance exercise rather than a plyometric exercise?",
    ],
  },
  11: {
    title: "Plyometric (Reactive) Training Concepts",
    keyConcepts: [
      "Stretch-shortening cycle: eccentric loading -> amortization (transition) -> concentric unloading",
      "Shorter amortization phase = more powerful movement",
      "Stabilization reactive (Phase 1): hold landings 3-5 seconds",
      "Strength reactive (Phases 2-4): repeated jumps without extended holds",
      "Power reactive (Phase 5): maximal force and velocity",
      "Rate of force production: speed at which muscle produces force",
    ],
    commonMisconceptions: [
      "Thinking plyometrics are just jumping — it's specifically about the stretch-shortening cycle",
      "Believing plyometrics are only for athletes — all clients can benefit from properly progressed reactive training",
      "Skipping stabilization reactive training — landing mechanics must be established first",
      "Confusing amortization with rest — amortization is the brief transition between eccentric and concentric phases",
      "Assuming more height/distance always means better — quality of movement and landing mechanics are priorities",
    ],
    examPatterns: [
      "What are the three phases of the stretch-shortening cycle? (Eccentric, amortization, concentric)",
      "In Phase 1 reactive training, how long should a landing be held? (3-5 seconds)",
      "What happens if the amortization phase is too long? (Elastic energy is lost as heat, reducing power)",
      "A box jump with a hold landing is an example of which reactive training level? (Stabilization reactive)",
      "What is rate of force production? (The speed at which a muscle can produce force)",
    ],
    socraticStarters: [
      "Can you explain the stretch-shortening cycle using the example of jumping as high as you can?",
      "Why does a longer amortization phase reduce power output — what's happening to the stored energy?",
      "Why does NASM require clients to master landing mechanics before progressing plyometric intensity?",
      "How is reactive stabilization training different from just doing a jump?",
      "What's the connection between plyometric training and real-world activities like catching yourself from a trip?",
    ],
  },
  12: {
    title: "Speed, Agility, and Quickness Training",
    keyConcepts: [
      "Speed = stride rate x stride length",
      "Agility = ability to accelerate, decelerate, stabilize, and change direction quickly",
      "Quickness = reaction time and rapid change of body position",
      "SAQ follows OPT progression: controlled drills -> increased speed -> maximal effort",
      "Deceleration mechanics are critical for injury prevention (especially ACL)",
      "SAQ training is appropriate for all populations when properly progressed",
    ],
    commonMisconceptions: [
      "Thinking SAQ is only for athletes — it applies to all populations for daily functional movement",
      "Confusing speed with agility — speed is linear, agility involves direction changes",
      "Believing agility is purely physical — it has a significant cognitive/reactive component",
      "Ignoring deceleration training — most non-contact injuries happen during deceleration",
      "Assuming faster always means better — quality of movement patterns must precede speed increases",
    ],
    examPatterns: [
      "What two factors determine running speed? (Stride rate and stride length)",
      "SAQ drills in Phase 1 should be performed at what intensity? (Low speed with proper form and extended rest)",
      "Why is deceleration training important for ACL injury prevention?",
      "What is the difference between agility and quickness?",
      "A client performing ladder drills at moderate speed with moderate rest is in which SAQ phase? (Phases 2-4)",
    ],
    socraticStarters: [
      "What's the practical difference between speed, agility, and quickness — can you give a real-world example of each?",
      "Why does NASM emphasize deceleration training before acceleration training?",
      "How would you make a case to a non-athlete client about why SAQ training matters for them?",
      "If speed equals stride rate times stride length, how would you train each component?",
      "Why do most non-contact ACL injuries happen during deceleration or direction change?",
    ],
  },
  13: {
    title: "Resistance Training Concepts",
    keyConcepts: [
      "SAID principle: Specific Adaptation to Imposed Demands",
      "GAS: alarm reaction -> resistance development -> exhaustion (if overreached)",
      "Phase 1: 12-20 reps, 1-3 sets, 4/2/1 tempo, 0-90s rest",
      "Phase 2: 8-12 reps, 2-4 sets, superset stable + unstable exercises",
      "Phase 3: 6-12 reps, 3-5 sets, 2/0/2 tempo, 75-85% 1RM",
      "Phase 4: 1-5 reps, 4-6 sets, explosive tempo, 85-100% 1RM, 3-5 min rest",
      "Phase 5: strength superset with power exercises",
    ],
    commonMisconceptions: [
      "Clients should skip Phase 1 if they're already strong — stabilization is foundational regardless of strength",
      "Thinking more weight always means more progress — tempo, volume, and rest are equally important",
      "Confusing hypertrophy (Phase 3) with maximal strength (Phase 4) — different rep ranges and goals",
      "Believing GAS only applies to overtraining — it explains ALL adaptation to training stress",
      "Assuming 4/2/1 tempo is just 'going slow' — it specifically targets stabilization and neuromuscular control",
    ],
    examPatterns: [
      "A new client with poor scapular stability should start in which phase? (Phase 1 — Stabilization Endurance)",
      "What is the rep range for Phase 3 (Hypertrophy)? (6-12 reps at 75-85% 1RM)",
      "What tempo is used in Phase 1 stabilization training? (4/2/1 — 4 sec eccentric, 2 sec isometric, 1 sec concentric)",
      "How much rest between sets in Phase 4 (Maximal Strength)? (3-5 minutes)",
      "What does SAID stand for? (Specific Adaptation to Imposed Demands)",
      "What are the three stages of GAS? (Alarm, resistance, exhaustion)",
    ],
    socraticStarters: [
      "Why does Phase 1 use a 4/2/1 tempo — what adaptation is that specifically targeting?",
      "Can you explain why a client who can bench press 300 lbs still needs stabilization training?",
      "How does the SAID principle guide your exercise selection for different client goals?",
      "Walk me through how GAS explains why periodization is necessary",
      "What's the difference between training for hypertrophy versus maximal strength in terms of programming variables?",
    ],
  },
  14: {
    title: "Exercise Technique and Spotting",
    keyConcepts: [
      "Five primary movement patterns: squat, hinge, push, pull, rotation",
      "Spotting required for barbell bench, barbell squat, overhead press with heavy loads",
      "Breathing: exhale during concentric (exertion), inhale during eccentric",
      "Compound exercises before isolation exercises in a session",
      "Machines provide more stability for beginners; free weights require more stabilization",
      "Valsalva maneuver generally discouraged for most populations",
    ],
    commonMisconceptions: [
      "Thinking machines are inferior to free weights — they serve specific purposes in the OPT model",
      "Believing spotters should lift the weight for the client — spotters provide minimal assistance",
      "Assuming holding your breath (Valsalva) is always dangerous — it can be appropriate for trained lifters in Phase 4",
      "Thinking all exercises need a spotter — many exercises are safely performed without one",
      "Confusing compound and isolation exercise order — compounds first because they require more energy and coordination",
    ],
    examPatterns: [
      "Which exercises always require a spotter? (Barbell bench press, barbell squat, heavy overhead press)",
      "What is the correct breathing pattern during resistance training? (Exhale concentric, inhale eccentric)",
      "Should compound or isolation exercises be performed first? (Compound exercises first)",
      "What is the Valsalva maneuver and when is it contraindicated?",
      "A lat pulldown is an example of which movement pattern? (Pull)",
    ],
    socraticStarters: [
      "Why does NASM recommend performing compound exercises before isolation exercises in a session?",
      "What are the key things a spotter should communicate before a set begins?",
      "Can you explain why breathing mechanics matter during resistance training?",
      "When might the Valsalva maneuver actually be appropriate, and why is it usually discouraged?",
      "How would you decide whether to use a machine or free weight version of an exercise for a specific client?",
    ],
  },
  15: {
    title: "Program Design Concepts",
    keyConcepts: [
      "Session order: SMR -> stretching -> core -> balance -> reactive/plyo -> SAQ -> resistance -> cool-down",
      "Clients should spend approximately 4 weeks per OPT phase",
      "Total body splits recommended for beginners and Phase 1",
      "Acute variables: sets, reps, intensity, tempo, rest, volume, frequency, exercise selection",
      "Linear periodization: progressive increase in intensity, decrease in volume",
      "Undulating periodization: varies intensity and volume within each week",
    ],
    commonMisconceptions: [
      "Thinking program design is just picking exercises — it's systematic manipulation of all acute variables",
      "Believing 4 weeks per phase is a strict rule — it's a guideline adjusted to client response",
      "Assuming advanced clients need body-part splits — total body and upper/lower splits can be effective at all levels",
      "Confusing exercise order within a session — there's a specific sequence for warm-up through cool-down",
      "Thinking linear periodization is always best — undulating may be superior for trained individuals",
    ],
    examPatterns: [
      "What is the correct order of components in a training session? (SMR, stretch, core, balance, reactive, SAQ, resistance, cool-down)",
      "How long should a client typically remain in each OPT phase? (Approximately 4 weeks)",
      "Which periodization strategy varies intensity within a single training week? (Undulating periodization)",
      "What training split is recommended for a beginner client? (Total body)",
      "How should exercise intensity be determined? (Percentage of estimated 1RM or rep max testing)",
    ],
    socraticStarters: [
      "Why does NASM prescribe a specific order of components within a single training session?",
      "How would you modify a Phase 1 program for a client who only has 30 minutes to train?",
      "What factors would make you keep a client in a phase longer than 4 weeks?",
      "What's the practical difference between linear and undulating periodization for a client's weekly training?",
      "How do assessment results directly influence your program design decisions?",
    ],
  },
  16: {
    title: "Nutrition",
    keyConcepts: [
      "Macros: carbs (4 cal/g), protein (4 cal/g), fat (9 cal/g)",
      "RMR accounts for ~70% of total daily energy expenditure",
      "Protein for active individuals: 1.2-2.0 g/kg/day",
      "Hydration: 14-22 oz 2 hours before exercise, 6-12 oz every 15-20 min during",
      "500 calorie/day deficit = ~1 lb fat loss/week",
      "Trainers must stay within scope of practice — no prescribing diets for medical conditions",
    ],
    commonMisconceptions: [
      "Thinking trainers can prescribe specific meal plans — that's outside scope of practice unless also a dietitian",
      "Believing protein timing matters more than total daily intake — total daily amount is the priority",
      "Assuming fat is bad — dietary fat is essential for hormones, cell membranes, and vitamin absorption",
      "Thinking all calories are equal for body composition — macronutrient distribution matters",
      "Believing supplements can replace whole foods — food first, supplements to fill gaps",
    ],
    examPatterns: [
      "How many calories per gram does fat provide? (9 cal/g)",
      "What percentage of total daily energy expenditure does RMR account for? (~70%)",
      "A client asks you to create a meal plan for their diabetes. What should you do? (Refer to a registered dietitian)",
      "What is the recommended protein intake for active individuals? (1.2-2.0 g/kg/day)",
      "Which vitamins are fat-soluble? (A, D, E, K)",
    ],
    socraticStarters: [
      "Why does NASM place such strong emphasis on scope of practice when it comes to nutrition?",
      "How would you explain the concept of energy balance to a client who just wants to 'lose weight'?",
      "Why is dietary fat essential even for clients trying to lose body fat?",
      "If a client asks you to recommend a specific diet, how would you handle that conversation?",
      "How does understanding RMR help you have realistic conversations about caloric needs with clients?",
    ],
  },
  17: {
    title: "Supplementation",
    keyConcepts: [
      "Supplements are regulated as food, not drugs (DSHEA 1994)",
      "Creatine monohydrate is one of the most well-researched performance supplements",
      "Caffeine improves endurance at 3-6 mg/kg body weight",
      "Third-party testing (NSF, Informed Sport) ensures quality and safety",
      "Protein supplements are not superior to whole food protein",
      "Trainers must stay within scope when recommending supplements",
    ],
    commonMisconceptions: [
      "Thinking supplements are FDA-approved like drugs — they don't require pre-market approval",
      "Believing creatine is a steroid or harmful to kidneys — it's well-researched and safe for healthy individuals",
      "Assuming all supplements work as advertised — most lack strong evidence",
      "Thinking trainers can recommend supplements for medical conditions — that's outside scope of practice",
      "Believing more supplements equals better results — whole food nutrition is the foundation",
    ],
    examPatterns: [
      "Under DSHEA, supplements are regulated as what? (Food products, not drugs)",
      "Which supplement has the strongest evidence for improving high-intensity performance? (Creatine monohydrate)",
      "What organizations provide third-party testing for supplements? (NSF International, Informed Sport)",
      "A client asks if they should take a supplement to treat their high blood pressure. What should you do? (Refer to physician)",
      "What is an ergogenic aid? (Any substance or technique used to enhance performance)",
    ],
    socraticStarters: [
      "Why is it important for trainers to understand that supplements aren't regulated like drugs?",
      "What evidence would you look for before recommending any supplement to a client?",
      "How would you explain to a client why creatine is one of the few supplements NASM considers well-supported?",
      "What's the significance of third-party testing certifications on supplement labels?",
      "If a client brings in a new supplement and asks your opinion, how would you evaluate it?",
    ],
  },
  18: {
    title: "Lifestyle Modification and Behavioral Coaching",
    keyConcepts: [
      "Stages of Change: precontemplation, contemplation, preparation, action, maintenance",
      "Self-efficacy: belief in one's ability to succeed — key predictor of behavior change",
      "SMART goals: Specific, Measurable, Attainable, Realistic, Time-bound",
      "Motivational interviewing uses OARS: Open questions, Affirmations, Reflective listening, Summarizing",
      "Relapse is normal, not failure — trainers help with relapse prevention",
      "Communication skills are as important as technical knowledge",
    ],
    commonMisconceptions: [
      "Thinking motivation is the client's problem — trainers actively build self-efficacy",
      "Believing all clients are in the 'action' stage — many are in contemplation or preparation",
      "Assuming relapse means the program failed — it's a normal part of behavior change",
      "Thinking SMART goals are just for exercise — they apply to all behavior change targets",
      "Confusing motivational interviewing with giving motivational speeches — MI is about asking and listening",
    ],
    examPatterns: [
      "A client says 'I know I should exercise but I keep making excuses.' What stage of change are they in? (Contemplation)",
      "What does OARS stand for in motivational interviewing? (Open questions, Affirmations, Reflective listening, Summarizing)",
      "Which factor is the strongest predictor of behavior change? (Self-efficacy)",
      "A client has been exercising consistently for 8 months. What stage of change are they in? (Maintenance)",
      "What are the components of a SMART goal?",
    ],
    socraticStarters: [
      "How would you approach a client who says they want to get fit but has failed to start three times before?",
      "Can you identify which stage of change a client is in based on what they say during an initial consultation?",
      "What's the difference between motivational interviewing and just telling someone to 'stay motivated'?",
      "How would you build self-efficacy in a client who doesn't believe they can stick with an exercise program?",
      "Why does NASM consider relapse a normal part of behavior change rather than a failure?",
    ],
  },
  19: {
    title: "Special Populations",
    keyConcepts: [
      "Youth: emphasize movement quality, avoid maximal lifting until physically mature",
      "Older adults: resistance + balance training to combat sarcopenia and falls",
      "Hypertension: avoid heavy isometrics and Valsalva; moderate cardio is beneficial",
      "Diabetes: monitor blood glucose; avoid exercise if >250 mg/dL with ketones",
      "Pregnancy: no supine exercises after 1st trimester, avoid overheating, moderate intensity",
      "Osteoporosis: weight-bearing exercise, avoid high-impact and excessive spinal flexion",
    ],
    commonMisconceptions: [
      "Thinking older adults should avoid resistance training — it's actually the most effective intervention for sarcopenia",
      "Believing children should train like small adults — youth programming has unique considerations",
      "Assuming all exercise is beneficial for diabetic clients — blood glucose must be monitored",
      "Thinking pregnant women should avoid exercise entirely — moderate exercise is generally beneficial and recommended",
      "Believing clients with hypertension can't do resistance training — they can with appropriate modifications",
    ],
    examPatterns: [
      "After which trimester should supine exercises be avoided during pregnancy? (After the first trimester)",
      "What is sarcopenia? (Age-related loss of muscle mass and function)",
      "A client with Type 2 diabetes has a blood glucose of 280 mg/dL with ketones. Should they exercise? (No)",
      "Which type of exercise is most effective for combating osteoporosis? (Weight-bearing and resistance exercises)",
      "What exercises should be avoided for clients with hypertension? (Heavy isometrics and Valsalva maneuver)",
    ],
    socraticStarters: [
      "Why does NASM recommend resistance training for older adults when many people think they should 'take it easy'?",
      "What special considerations do you need to think about when training a pregnant client?",
      "How would you modify a standard OPT Phase 1 program for a client with hypertension?",
      "Why is blood glucose monitoring so important when training clients with diabetes?",
      "What's different about training youth compared to adults — and why can't you just scale down adult programs?",
    ],
  },
  20: {
    title: "Professional Development and Responsibility",
    keyConcepts: [
      "Scope of practice: don't diagnose, prescribe diets, recommend supplements for medical conditions, or provide counseling",
      "Professional liability insurance is essential for all trainers",
      "Informed consent and health history must be completed before training",
      "Independent contractor vs. employee: different tax and legal implications",
      "Continuing education required to maintain certification",
      "Document all sessions and incidents; follow emergency action plans",
    ],
    commonMisconceptions: [
      "Thinking scope of practice only matters in extreme cases — daily interactions regularly approach boundaries",
      "Believing liability insurance is optional if you work at a gym — personal coverage is still recommended",
      "Assuming informed consent is just a formality — it's a legal requirement and protects both parties",
      "Thinking business skills are separate from being a good trainer — they're essential for career sustainability",
      "Confusing independent contractor with employee status — the distinction has significant legal and financial implications",
    ],
    examPatterns: [
      "A client asks you to diagnose their knee pain. What should you do? (Refer to a qualified healthcare professional)",
      "What documents should be completed before a client's first training session? (Informed consent, health history/PAR-Q)",
      "What type of insurance should all personal trainers carry? (Professional liability insurance)",
      "What is negligence in the context of personal training? (Failure to act with reasonable care)",
      "An independent contractor is responsible for which of the following? (Own taxes, insurance, business expenses)",
    ],
    socraticStarters: [
      "Where exactly is the line between general nutrition guidance and prescribing a diet?",
      "Why is informed consent more than just a piece of paper — what does it actually protect?",
      "How would you handle a situation where a client asks you to help with something outside your scope of practice?",
      "What's the practical difference between being an independent contractor and an employee as a trainer?",
      "Why does NASM emphasize business skills alongside technical training knowledge?",
    ],
  },
};

export function getChapterContext(chapter: number): ChapterContext | undefined {
  return chapterContexts[chapter];
}

export function getAllChapterTitles(): { number: number; title: string }[] {
  return Object.entries(chapterContexts).map(([num, ctx]) => ({
    number: parseInt(num),
    title: ctx.title,
  }));
}
