// Quiz questions for chapters 11-20
// Covers SAQ, resistance training, OPT model, nutrition, supplements,
// behavioral coaching, special populations, chronic conditions, scope of practice, and business

export const seedQuestions2 = [
  // ─── Chapter 11: SAQ Training ───────────────────────────────────────

  {
    chapter: 11,
    question: "What is the primary goal of speed, agility, and quickness (SAQ) training?",
    options: ["Increase maximal strength", "Improve the rate of force production and neuromuscular efficiency", "Build muscular hypertrophy", "Reduce body fat percentage"],
    correct_answer: 1,
    explanation: "SAQ training is designed to improve the rate of force production and neuromuscular efficiency, enhancing the body's ability to react and move quickly in all planes of motion.",
    difficulty: "easy",
  },
  {
    chapter: 11,
    question: "A client performing cone drills with rapid changes of direction at various angles is primarily training which component?",
    options: ["Speed", "Quickness", "Agility", "Muscular endurance"],
    correct_answer: 2,
    explanation: "Agility is the ability to accelerate, decelerate, stabilize, and change direction quickly while maintaining proper posture. Cone drills with directional changes are a classic agility exercise.",
    difficulty: "medium",
  },
  {
    chapter: 11,
    question: "Which drill is most appropriate for improving quickness?",
    options: ["400-meter sprint", "Pro agility shuttle", "Dot drill", "Tempo run"],
    correct_answer: 2,
    explanation: "Quickness refers to the ability to react and change body position with maximal rate of force production. Dot drills emphasize rapid foot movements and reaction time, making them ideal for quickness training.",
    difficulty: "medium",
  },
  {
    chapter: 11,
    question: "In the OPT model, at which phase should a trainer first introduce SAQ drills?",
    options: ["Phase 1 only", "Phase 2 and above", "Phase 5 only", "SAQ can be incorporated at all phases with appropriate progressions"],
    correct_answer: 3,
    explanation: "SAQ training can be incorporated at all OPT model phases. In Phase 1, drills focus on stabilization with low intensity, while higher phases use more complex, reactive drills with greater intensity.",
    difficulty: "hard",
  },
  {
    chapter: 11,
    question: "A ladder drill where a client must react to a verbal command to change footwork pattern is training:",
    options: ["Straight-line speed", "Reactive agility", "Maximal strength", "Flexibility"],
    correct_answer: 1,
    explanation: "Reactive agility involves responding to an unpredictable stimulus (like a verbal cue) while performing movement drills. This trains both cognitive processing and physical agility simultaneously.",
    difficulty: "medium",
  },
  {
    chapter: 11,
    question: "Stride length and stride frequency are the two primary components of:",
    options: ["Agility", "Quickness", "Speed", "Balance"],
    correct_answer: 2,
    explanation: "Speed is determined by stride length (distance covered per step) and stride frequency (rate of steps). Improving either or both will increase overall speed.",
    difficulty: "easy",
  },
  {
    chapter: 11,
    question: "Which of the following is NOT a recommended progression for SAQ training?",
    options: ["Moving from stable to unstable surfaces", "Increasing complexity of drills", "Performing SAQ drills in a fatigued state to build toughness", "Adding sport-specific movement patterns"],
    correct_answer: 2,
    explanation: "SAQ drills should be performed when the client is fresh and not fatigued, typically early in the workout after the warm-up. Fatigue compromises form, neuromuscular efficiency, and increases injury risk.",
    difficulty: "hard",
  },
  {
    chapter: 11,
    question: "What type of base drill would be most appropriate for a Phase 1 (Stabilization Endurance) client?",
    options: ["Reactive box jumps", "Tuck jumps for height", "Lateral shuffles at controlled tempo", "Barbell power cleans"],
    correct_answer: 2,
    explanation: "In Phase 1, SAQ drills should be low intensity with controlled tempos to develop movement quality and stabilization. Lateral shuffles at a controlled tempo build foundational movement patterns safely.",
    difficulty: "medium",
  },
  {
    chapter: 11,
    question: "During a speed drill, a client consistently has excessive forward lean and limited arm drive. What should the trainer address first?",
    options: ["Have the client sprint faster to build momentum", "Add weighted sprints to increase force output", "Correct running mechanics by cueing upright posture and coordinated arm swing", "Switch to agility training instead"],
    correct_answer: 2,
    explanation: "Proper running mechanics are foundational for speed development. Excessive forward lean and poor arm drive are form issues that should be corrected with technique coaching before increasing intensity.",
    difficulty: "medium",
  },
  {
    chapter: 11,
    question: "The backpedal is classified as a drill for which component of SAQ?",
    options: ["Speed only", "Quickness only", "Agility", "Flexibility"],
    correct_answer: 2,
    explanation: "The backpedal is an agility drill because it involves deceleration, body control, and the ability to transition to other movements. It trains multi-directional movement competency.",
    difficulty: "easy",
  },

  // ─── Chapter 12: Resistance Training ────────────────────────────────

  {
    chapter: 12,
    question: "Which acute variable refers to the speed at which each repetition is performed?",
    options: ["Training intensity", "Rest interval", "Repetition tempo", "Training volume"],
    correct_answer: 2,
    explanation: "Repetition tempo is the speed at which a repetition is performed, typically expressed as a four-digit code (e.g., 4/2/1 for eccentric/isometric/concentric phases). It directly affects time under tension.",
    difficulty: "easy",
  },
  {
    chapter: 12,
    question: "A personal trainer designs a workout using 3 sets of 12 reps at 70% 1RM with 60 seconds rest. Which acute variable was NOT mentioned?",
    options: ["Sets", "Repetitions", "Intensity", "Tempo"],
    correct_answer: 3,
    explanation: "The workout describes sets (3), reps (12), intensity (70% 1RM), and rest intervals (60 seconds). Tempo (the speed of each repetition) was not specified in this program design.",
    difficulty: "medium",
  },
  {
    chapter: 12,
    question: "Training volume is calculated by:",
    options: ["Sets x reps", "Sets x reps x weight", "Weight x rest period", "Reps x tempo"],
    correct_answer: 1,
    explanation: "Training volume is calculated as sets multiplied by repetitions multiplied by weight (load). This provides a measure of total work performed during a training session.",
    difficulty: "easy",
  },
  {
    chapter: 12,
    question: "A client who can perform 10 reps of bench press at 150 lbs but fails at the 11th rep is working at approximately what percentage of their 1RM?",
    options: ["65%", "75%", "85%", "95%"],
    correct_answer: 1,
    explanation: "According to the repetition-percentage chart, 10 repetitions corresponds to approximately 75% of 1RM. This relationship helps trainers prescribe appropriate loads without direct 1RM testing.",
    difficulty: "medium",
  },
  {
    chapter: 12,
    question: "Which training system involves performing two exercises back-to-back for opposing muscle groups with no rest between them?",
    options: ["Drop set", "Superset", "Circuit training", "Pyramid"],
    correct_answer: 1,
    explanation: "A superset involves performing two exercises back-to-back with minimal rest, typically targeting opposing muscle groups (e.g., biceps curl followed immediately by triceps extension).",
    difficulty: "easy",
  },
  {
    chapter: 12,
    question: "A peripheral heart action (PHA) training system is best described as:",
    options: ["Performing only upper body exercises", "Alternating upper and lower body exercises in a circuit to maximize blood flow", "Resting 3-5 minutes between every set", "Training one body part per day"],
    correct_answer: 1,
    explanation: "PHA training alternates upper and lower body exercises in a circuit format, forcing blood to be distributed throughout the body. This maximizes caloric expenditure and cardiovascular demand.",
    difficulty: "hard",
  },
  {
    chapter: 12,
    question: "Which resistance training system uses a progressively heavier load while decreasing reps across sets?",
    options: ["Drop set", "Circuit training", "Ascending pyramid", "Superset"],
    correct_answer: 2,
    explanation: "An ascending pyramid involves increasing the weight and decreasing the repetitions with each successive set (e.g., set 1: 12 reps at 65%, set 2: 10 reps at 75%, set 3: 8 reps at 85%).",
    difficulty: "medium",
  },
  {
    chapter: 12,
    question: "What is the recommended rest interval for a client training for maximal strength?",
    options: ["0-30 seconds", "30-60 seconds", "1-2 minutes", "3-5 minutes"],
    correct_answer: 3,
    explanation: "Maximal strength training requires rest intervals of 3-5 minutes to allow the phosphagen (ATP-PC) energy system to fully recover, enabling the client to maintain high force output across sets.",
    difficulty: "medium",
  },
  {
    chapter: 12,
    question: "A drop set is performed by:",
    options: ["Increasing weight after each set", "Performing a set to failure, then immediately reducing weight and continuing reps", "Alternating between two exercises", "Performing only eccentric contractions"],
    correct_answer: 1,
    explanation: "A drop set involves performing an exercise to failure, then immediately reducing the weight and continuing to perform repetitions. This extends the set beyond normal failure to increase metabolic stress.",
    difficulty: "easy",
  },
  {
    chapter: 12,
    question: "A client new to resistance training should begin with which type of exercises?",
    options: ["Olympic lifts with maximal loads", "Isolation exercises with heavy resistance", "Machine-based and stabilization exercises at lower intensities", "Plyometric supersets"],
    correct_answer: 2,
    explanation: "New clients should begin with machine-based and stabilization exercises at lower intensities to develop proper movement patterns, neuromuscular control, and connective tissue tolerance before progressing to more complex movements.",
    difficulty: "easy",
  },
  {
    chapter: 12,
    question: "If a client's goal is muscular hypertrophy, which rep range and rest interval combination is most appropriate?",
    options: ["1-5 reps, 3-5 minutes rest", "6-12 reps, 60-90 seconds rest", "15-25 reps, 0-30 seconds rest", "1-3 reps, 5-7 minutes rest"],
    correct_answer: 1,
    explanation: "Hypertrophy is best achieved with moderate repetitions (6-12) and moderate rest intervals (60-90 seconds), which optimize metabolic stress and mechanical tension for muscle growth.",
    difficulty: "medium",
  },

  // ─── Chapter 13: The OPT Model ─────────────────────────────────────

  {
    chapter: 13,
    question: "Phase 1 of the OPT model is called:",
    options: ["Strength Endurance", "Stabilization Endurance", "Muscular Development", "Power"],
    correct_answer: 1,
    explanation: "Phase 1 of the OPT (Optimum Performance Training) model is Stabilization Endurance, which focuses on improving muscular endurance, stability, flexibility, and neuromuscular efficiency.",
    difficulty: "easy",
  },
  {
    chapter: 13,
    question: "Which phases of the OPT model make up the Strength level?",
    options: ["Phases 1 and 2", "Phases 2, 3, and 4", "Phases 3, 4, and 5", "Phases 1 through 5"],
    correct_answer: 1,
    explanation: "The Strength level includes Phase 2 (Strength Endurance), Phase 3 (Muscular Development/Hypertrophy), and Phase 4 (Maximal Strength). Each progressively increases intensity and load.",
    difficulty: "medium",
  },
  {
    chapter: 13,
    question: "A client performing a chest press on a stability ball followed immediately by a barbell bench press is using which OPT phase training strategy?",
    options: ["Phase 1 — Stabilization Endurance", "Phase 2 — Strength Endurance", "Phase 3 — Hypertrophy", "Phase 5 — Power"],
    correct_answer: 1,
    explanation: "Phase 2 (Strength Endurance) uses a superset strategy pairing a stabilization exercise with a strength exercise. A stability ball chest press (stabilization) followed by barbell bench press (strength) is a classic Phase 2 approach.",
    difficulty: "hard",
  },
  {
    chapter: 13,
    question: "What is the recommended rep range for Phase 3 (Muscular Development/Hypertrophy)?",
    options: ["12-20 reps", "6-12 reps", "1-5 reps", "15-25 reps"],
    correct_answer: 1,
    explanation: "Phase 3 (Muscular Development) prescribes 6-12 repetitions at 75-85% of 1RM to maximize mechanical tension and metabolic stress, the primary drivers of hypertrophy.",
    difficulty: "easy",
  },
  {
    chapter: 13,
    question: "Periodization in the OPT model refers to:",
    options: ["Training only during certain times of the year", "A systematic approach to varying training variables over time to prevent plateaus", "Alternating between cardio and resistance training days", "Performing the same workout every session for consistency"],
    correct_answer: 1,
    explanation: "Periodization is the systematic variation of acute training variables (intensity, volume, rest, tempo) over specific time periods to optimize adaptations and prevent overtraining or plateaus.",
    difficulty: "easy",
  },
  {
    chapter: 13,
    question: "A competitive athlete preparing for a season would most benefit from training through which OPT model phase?",
    options: ["Phase 1 only", "Phase 3 only", "Phase 5 — Power", "Phase 2 only"],
    correct_answer: 2,
    explanation: "Phase 5 (Power) trains the neuromuscular system to produce the greatest force in the shortest time. This is most beneficial for competitive athletes who need explosive power for sport performance.",
    difficulty: "medium",
  },
  {
    chapter: 13,
    question: "In Phase 5 (Power), the recommended tempo for power exercises is:",
    options: ["4/2/1 (slow eccentric, pause, slow concentric)", "3/1/3 (moderate across all phases)", "Explosive as fast as can be controlled", "10/5/5 (very slow tempo)"],
    correct_answer: 2,
    explanation: "Phase 5 power exercises use an explosive tempo to maximize rate of force production. The concentric phase should be performed as fast as can be controlled while maintaining proper form.",
    difficulty: "medium",
  },
  {
    chapter: 13,
    question: "A mesocycle in periodization typically lasts:",
    options: ["1 day", "1 week", "2-6 weeks", "1 year"],
    correct_answer: 2,
    explanation: "A mesocycle typically lasts 2-6 weeks and represents one phase or block of training. Multiple mesocycles make up a macrocycle (the entire training plan, often spanning months to a year).",
    difficulty: "medium",
  },
  {
    chapter: 13,
    question: "The acute variables for Phase 1 (Stabilization Endurance) include:",
    options: ["1-5 reps, 3-5 min rest, 85-100% intensity", "12-20 reps, 0-90 sec rest, 50-70% intensity", "6-12 reps, 60-90 sec rest, 75-85% intensity", "8-12 reps, 2-4 min rest, 80-90% intensity"],
    correct_answer: 1,
    explanation: "Phase 1 uses high reps (12-20), short rest periods (0-90 seconds), and low to moderate intensity (50-70% 1RM) to develop muscular endurance, proprioception, and joint stability.",
    difficulty: "medium",
  },
  {
    chapter: 13,
    question: "Which OPT phase uses the heaviest loads relative to 1RM?",
    options: ["Phase 1", "Phase 2", "Phase 3", "Phase 4"],
    correct_answer: 3,
    explanation: "Phase 4 (Maximal Strength) uses the heaviest loads, typically 85-100% of 1RM with 1-5 reps, to recruit the highest threshold motor units and maximize force production.",
    difficulty: "easy",
  },
  {
    chapter: 13,
    question: "A personal trainer transitions a client from Phase 2 back to Phase 1 after a two-week vacation. This is an example of:",
    options: ["Linear periodization failure", "Undulating periodization", "Appropriate regression based on the client's current status", "Poor program design"],
    correct_answer: 2,
    explanation: "Returning to Phase 1 after a training break is appropriate regression. After time off, clients lose some neuromuscular adaptations and need to re-establish stabilization and movement quality before progressing again.",
    difficulty: "hard",
  },

  // ─── Chapter 14: Nutrition ──────────────────────────────────────────

  {
    chapter: 14,
    question: "How many calories are in one gram of protein?",
    options: ["2 calories", "4 calories", "7 calories", "9 calories"],
    correct_answer: 1,
    explanation: "Protein provides 4 calories per gram. For reference, carbohydrates also provide 4 cal/g, fat provides 9 cal/g, and alcohol provides 7 cal/g.",
    difficulty: "easy",
  },
  {
    chapter: 14,
    question: "A client weighing 180 lbs wants to consume 1 gram of protein per pound of body weight. How many calories from protein will they consume daily?",
    options: ["180 calories", "540 calories", "720 calories", "1620 calories"],
    correct_answer: 2,
    explanation: "180 lbs x 1 g/lb = 180 g protein. At 4 calories per gram, 180 g x 4 = 720 calories from protein daily.",
    difficulty: "medium",
  },
  {
    chapter: 14,
    question: "Which macronutrient provides the most calories per gram?",
    options: ["Protein", "Carbohydrate", "Fat", "Fiber"],
    correct_answer: 2,
    explanation: "Fat provides 9 calories per gram, making it the most calorie-dense macronutrient. Protein and carbohydrates each provide 4 calories per gram.",
    difficulty: "easy",
  },
  {
    chapter: 14,
    question: "The glycemic index (GI) measures:",
    options: ["Total calories in a food", "How quickly a food raises blood sugar levels", "The protein content of a food", "How much fat a food contains"],
    correct_answer: 1,
    explanation: "The glycemic index measures how quickly a carbohydrate-containing food raises blood glucose levels compared to a reference food (usually pure glucose). High-GI foods cause rapid blood sugar spikes.",
    difficulty: "easy",
  },
  {
    chapter: 14,
    question: "A client reports feeling dizzy and having dark-colored urine during a workout. What should the trainer suspect first?",
    options: ["Overtraining syndrome", "Dehydration", "Hypoglycemia", "Iron deficiency"],
    correct_answer: 1,
    explanation: "Dark-colored urine and dizziness during exercise are classic signs of dehydration. The trainer should stop exercise, have the client hydrate, and monitor symptoms before continuing.",
    difficulty: "medium",
  },
  {
    chapter: 14,
    question: "What is the general recommended daily water intake guideline for active individuals?",
    options: ["2-4 cups per day", "Approximately half their body weight in ounces", "1 gallon regardless of body size", "Only when thirsty"],
    correct_answer: 1,
    explanation: "A general guideline is to consume approximately half of body weight (in pounds) in ounces of water daily. Active individuals and those in hot climates may need more.",
    difficulty: "medium",
  },
  {
    chapter: 14,
    question: "Which of the following is a function of carbohydrates in the body?",
    options: ["Primary building block for muscle tissue", "Preferred energy source for the brain and high-intensity exercise", "Primary structural component of cell membranes", "Production of bile acids"],
    correct_answer: 1,
    explanation: "Carbohydrates are the body's preferred energy source, especially for the brain and during high-intensity exercise. They are stored as glycogen in muscles and the liver.",
    difficulty: "easy",
  },
  {
    chapter: 14,
    question: "A personal trainer should refer a client to a registered dietitian when:",
    options: ["The client asks about general healthy eating", "The client has a diagnosed medical condition requiring a specific diet plan", "The client wants to know about pre-workout meals", "The client asks about hydration strategies"],
    correct_answer: 1,
    explanation: "Personal trainers should refer clients to registered dietitians when medical nutrition therapy is needed, such as for diabetes, eating disorders, kidney disease, or other conditions requiring specific dietary prescriptions.",
    difficulty: "medium",
  },
  {
    chapter: 14,
    question: "To lose approximately one pound of body fat per week, a client must create a weekly caloric deficit of approximately:",
    options: ["1,000 calories", "2,000 calories", "3,500 calories", "5,000 calories"],
    correct_answer: 2,
    explanation: "One pound of body fat contains approximately 3,500 calories. A deficit of 500 calories per day (500 x 7 = 3,500) results in roughly one pound of fat loss per week.",
    difficulty: "easy",
  },
  {
    chapter: 14,
    question: "A food with a glycemic index below 55 is considered:",
    options: ["High glycemic", "Moderate glycemic", "Low glycemic", "Zero glycemic"],
    correct_answer: 2,
    explanation: "Foods with a GI below 55 are classified as low glycemic. They produce a slower, more gradual rise in blood sugar. Examples include most vegetables, legumes, and whole grains.",
    difficulty: "medium",
  },
  {
    chapter: 14,
    question: "Trans fats are associated with increased risk of:",
    options: ["Improved cholesterol levels", "Heart disease and elevated LDL cholesterol", "Better insulin sensitivity", "Enhanced recovery from exercise"],
    correct_answer: 1,
    explanation: "Trans fats raise LDL (bad) cholesterol, lower HDL (good) cholesterol, and increase the risk of heart disease, stroke, and type 2 diabetes. They should be minimized or eliminated from the diet.",
    difficulty: "easy",
  },

  // ─── Chapter 15: Supplements ────────────────────────────────────────

  {
    chapter: 15,
    question: "Which supplement has the most scientific evidence supporting its effectiveness for increasing strength and power?",
    options: ["Branched-chain amino acids (BCAAs)", "Creatine monohydrate", "Glutamine", "Conjugated linoleic acid (CLA)"],
    correct_answer: 1,
    explanation: "Creatine monohydrate is the most extensively researched and evidence-supported supplement for increasing strength, power, and lean body mass. It works by increasing phosphocreatine stores in muscle.",
    difficulty: "easy",
  },
  {
    chapter: 15,
    question: "An ergogenic aid is defined as:",
    options: ["A prescription medication for athletes", "Any substance or method that enhances performance", "A supplement only sold in health food stores", "A banned substance in sports"],
    correct_answer: 1,
    explanation: "An ergogenic aid is any substance, device, or practice that enhances energy use, production, or recovery to improve performance. They can be nutritional, pharmacological, physiological, or psychological.",
    difficulty: "easy",
  },
  {
    chapter: 15,
    question: "A client asks about taking a fat-burning supplement. The trainer's BEST response is:",
    options: ["Recommend the most popular brand", "Explain that supplements are not regulated the same as drugs and results vary; suggest focusing on nutrition and exercise first", "Tell them all supplements are unsafe", "Prescribe a specific dosage protocol"],
    correct_answer: 1,
    explanation: "Trainers should educate clients that supplements are not regulated as strictly as pharmaceuticals by the FDA. The foundation of any body composition change should be proper nutrition and consistent exercise.",
    difficulty: "medium",
  },
  {
    chapter: 15,
    question: "Which of the following is TRUE about dietary supplements in the United States?",
    options: ["The FDA must approve them before they are sold", "They are regulated under DSHEA and do not require pre-market approval", "They must contain exactly what is listed on the label", "They undergo clinical trials like prescription drugs"],
    correct_answer: 1,
    explanation: "Under the Dietary Supplement Health and Education Act (DSHEA) of 1994, supplements do not require FDA pre-market approval. Manufacturers are responsible for safety and labeling, but oversight is limited.",
    difficulty: "medium",
  },
  {
    chapter: 15,
    question: "Caffeine is classified as which type of ergogenic aid?",
    options: ["Mechanical", "Psychological only", "Pharmacological/nutritional", "Physiological"],
    correct_answer: 2,
    explanation: "Caffeine is a pharmacological/nutritional ergogenic aid. It has been shown to improve endurance performance, increase alertness, and reduce perceived exertion during exercise.",
    difficulty: "medium",
  },
  {
    chapter: 15,
    question: "A client is taking a supplement that lists a 'proprietary blend' on the label. This means:",
    options: ["The exact amounts of each ingredient are clearly listed", "The individual ingredient amounts are not disclosed", "The product has been FDA-approved", "It contains no active ingredients"],
    correct_answer: 1,
    explanation: "A proprietary blend lists the ingredients but does not disclose the specific amount of each individual ingredient. This makes it difficult to evaluate effectiveness or safety of the product.",
    difficulty: "medium",
  },
  {
    chapter: 15,
    question: "Which third-party certification helps verify that a supplement contains what its label claims?",
    options: ["OSHA certification", "NSF Certified for Sport or Informed Sport", "HIPAA compliance", "ADA approval"],
    correct_answer: 1,
    explanation: "NSF Certified for Sport and Informed Sport are third-party testing programs that verify supplements contain what they claim, are free of banned substances, and meet quality standards.",
    difficulty: "medium",
  },
  {
    chapter: 15,
    question: "Whey protein is considered a 'fast-digesting' protein because:",
    options: ["It is made from plants", "It is rapidly absorbed by the body, causing a quick rise in amino acids", "It takes 8 hours to digest", "It contains no essential amino acids"],
    correct_answer: 1,
    explanation: "Whey protein is rapidly digested and absorbed, causing a quick spike in blood amino acid levels. This makes it popular for post-workout consumption to support muscle protein synthesis.",
    difficulty: "easy",
  },
  {
    chapter: 15,
    question: "A personal trainer should NEVER:",
    options: ["Discuss general supplement information with clients", "Recommend a client speak with their doctor about supplements", "Prescribe or diagnose supplement needs for medical conditions", "Share evidence-based research about common supplements"],
    correct_answer: 2,
    explanation: "Personal trainers must not prescribe supplements for medical conditions or diagnose deficiencies, as this falls outside their scope of practice. They can share general information and refer clients to qualified healthcare professionals.",
    difficulty: "easy",
  },
  {
    chapter: 15,
    question: "Beta-alanine supplementation is most associated with:",
    options: ["Increased maximal strength", "Buffering lactic acid to delay fatigue during high-intensity exercise", "Improved flexibility", "Reduced inflammation"],
    correct_answer: 1,
    explanation: "Beta-alanine increases intramuscular carnosine levels, which buffers hydrogen ions produced during high-intensity exercise. This can delay the onset of muscular fatigue and improve performance in activities lasting 1-4 minutes.",
    difficulty: "hard",
  },

  // ─── Chapter 16: Behavioral Coaching ────────────────────────────────

  {
    chapter: 16,
    question: "According to the Transtheoretical Model, a client who is exercising regularly but has been doing so for less than 6 months is in which stage of change?",
    options: ["Preparation", "Action", "Maintenance", "Contemplation"],
    correct_answer: 1,
    explanation: "The Action stage is when an individual has been actively engaging in the new behavior (regular exercise) for less than 6 months. After 6 months of consistent behavior, they move to the Maintenance stage.",
    difficulty: "medium",
  },
  {
    chapter: 16,
    question: "A SMART goal must be all of the following EXCEPT:",
    options: ["Specific", "Measurable", "Aggressive", "Time-bound"],
    correct_answer: 2,
    explanation: "SMART goals are Specific, Measurable, Attainable, Realistic, and Time-bound. 'Aggressive' is not a SMART component. Goals should be challenging yet achievable, not recklessly ambitious.",
    difficulty: "easy",
  },
  {
    chapter: 16,
    question: "A client says, 'I know I should exercise, but I just don't have time.' This client is most likely in which stage of change?",
    options: ["Precontemplation", "Contemplation", "Preparation", "Action"],
    correct_answer: 1,
    explanation: "The Contemplation stage is characterized by awareness that a problem exists and thinking about making a change, but not yet committing. The client acknowledges exercise is important but identifies barriers.",
    difficulty: "medium",
  },
  {
    chapter: 16,
    question: "Which motivational interviewing technique involves the trainer restating what the client has said to show understanding?",
    options: ["Open-ended questioning", "Reflective listening", "Summarizing", "Affirmation"],
    correct_answer: 1,
    explanation: "Reflective listening involves restating or paraphrasing the client's words to demonstrate understanding and empathy. It helps build rapport and encourages the client to elaborate on their thoughts and feelings.",
    difficulty: "easy",
  },
  {
    chapter: 16,
    question: "Self-efficacy refers to:",
    options: ["A client's actual physical abilities", "A client's belief in their own ability to succeed in a specific situation", "A trainer's confidence in their programming", "The number of sessions completed"],
    correct_answer: 1,
    explanation: "Self-efficacy is an individual's belief in their capacity to execute behaviors necessary to produce specific outcomes. High self-efficacy increases motivation, effort, and persistence with exercise.",
    difficulty: "easy",
  },
  {
    chapter: 16,
    question: "A client in the Precontemplation stage would BEST be supported by:",
    options: ["Immediately starting an intense workout program", "Providing education about the benefits of exercise without pressuring them", "Setting a 5-day-per-week training schedule", "Signing them up for a fitness competition"],
    correct_answer: 1,
    explanation: "In Precontemplation, clients are not yet considering change. The best approach is gentle education about exercise benefits, raising awareness, and building rapport without pressure or demanding commitment.",
    difficulty: "medium",
  },
  {
    chapter: 16,
    question: "Extrinsic motivation comes from:",
    options: ["Personal enjoyment of the activity", "External rewards or pressures such as appearance or social approval", "An innate desire for self-improvement", "Flow state during exercise"],
    correct_answer: 1,
    explanation: "Extrinsic motivation is driven by external factors such as rewards, recognition, social pressure, or avoiding negative consequences. While effective short-term, building intrinsic motivation leads to longer adherence.",
    difficulty: "easy",
  },
  {
    chapter: 16,
    question: "A client who has maintained a consistent exercise routine for over one year is in which stage of change?",
    options: ["Action", "Maintenance", "Termination", "Preparation"],
    correct_answer: 1,
    explanation: "The Maintenance stage begins after 6 months of consistent behavior change. A client exercising regularly for over a year is solidly in Maintenance, working to prevent relapse.",
    difficulty: "easy",
  },
  {
    chapter: 16,
    question: "Which of the following is an example of a SMART goal?",
    options: ["I want to get fit this year", "I will lose 10 pounds of body fat in 12 weeks by exercising 4 days per week and following a nutrition plan", "I want to be stronger", "I will exercise more often"],
    correct_answer: 1,
    explanation: "This goal is Specific (lose 10 lbs of fat), Measurable (10 lbs), Attainable/Realistic (12 weeks, 4 days/week with nutrition), and Time-bound (12 weeks). The other options are vague and unmeasurable.",
    difficulty: "medium",
  },
  {
    chapter: 16,
    question: "Cognitive distortions such as 'all-or-nothing' thinking in a fitness context might look like:",
    options: ["'I'll try to exercise three times this week'", "'I missed Monday's workout, so the whole week is ruined and I might as well quit'", "'I'll adjust my plan and train tomorrow instead'", "'Some exercise is better than none'"],
    correct_answer: 1,
    explanation: "All-or-nothing thinking is a cognitive distortion where a person sees things in black and white. Missing one session becomes total failure. Trainers can help reframe this by emphasizing progress over perfection.",
    difficulty: "hard",
  },

  // ─── Chapter 17: Special Populations ────────────────────────────────

  {
    chapter: 17,
    question: "When training youth clients (ages 6-13), the primary focus should be on:",
    options: ["Maximal strength development", "Fun, fundamental movement skills, and proper technique", "Bodybuilding-style hypertrophy programs", "High-intensity interval training"],
    correct_answer: 1,
    explanation: "Youth training should emphasize enjoyment, fundamental movement skills, coordination, and proper exercise technique. Heavy loading and advanced training methods are not appropriate for this developmental stage.",
    difficulty: "easy",
  },
  {
    chapter: 17,
    question: "For a pregnant client in her second trimester with no complications, which exercise modification is recommended?",
    options: ["Continue training at pre-pregnancy intensity", "Avoid supine (lying face-up) exercises after the first trimester", "Only perform seated exercises", "Stop all exercise until after delivery"],
    correct_answer: 1,
    explanation: "After the first trimester, supine exercises should be avoided because the weight of the uterus can compress the vena cava, reducing blood flow to the heart and fetus. Standing, seated, or side-lying positions are safer alternatives.",
    difficulty: "medium",
  },
  {
    chapter: 17,
    question: "Sarcopenia refers to:",
    options: ["Excessive joint flexibility in young athletes", "Age-related loss of muscle mass and strength", "A type of bone disease", "Increased fat storage during pregnancy"],
    correct_answer: 1,
    explanation: "Sarcopenia is the age-related progressive loss of muscle mass, strength, and function. Resistance training is one of the most effective interventions to slow or reverse sarcopenia in older adults.",
    difficulty: "easy",
  },
  {
    chapter: 17,
    question: "An obese client (BMI > 30) beginning an exercise program should:",
    options: ["Start with high-impact plyometrics", "Begin with low-impact, moderate-intensity activities and progress gradually", "Immediately train 6 days per week", "Focus exclusively on maximal strength"],
    correct_answer: 1,
    explanation: "Obese clients should begin with low-impact activities (walking, cycling, swimming) at moderate intensity to reduce joint stress and injury risk. Gradual progression in frequency, duration, and intensity is essential.",
    difficulty: "easy",
  },
  {
    chapter: 17,
    question: "Which is a key consideration when training older adults (65+)?",
    options: ["They cannot benefit from resistance training", "Balance and fall prevention exercises should be prioritized", "Only stretching is appropriate", "High-intensity plyometrics are the best option"],
    correct_answer: 1,
    explanation: "Older adults are at increased risk for falls and fractures. Balance training, along with resistance and flexibility exercises, should be prioritized to improve stability, bone density, and functional independence.",
    difficulty: "easy",
  },
  {
    chapter: 17,
    question: "A 70-year-old client with physician clearance wants to start resistance training. An appropriate starting point would be:",
    options: ["Phase 4 maximal strength training", "Phase 1 stabilization endurance with light loads and higher reps", "Olympic lifting program", "Competitive powerlifting routine"],
    correct_answer: 1,
    explanation: "Older adults should begin in Phase 1 (Stabilization Endurance) with light loads, higher reps, and controlled tempos to build neuromuscular control, joint stability, and movement confidence before progressing.",
    difficulty: "medium",
  },
  {
    chapter: 17,
    question: "During pregnancy, which of the following is a warning sign to stop exercise immediately?",
    options: ["Mild fatigue", "Slight increase in heart rate", "Vaginal bleeding or fluid leakage", "Feeling warm during exercise"],
    correct_answer: 2,
    explanation: "Vaginal bleeding, fluid leakage, dizziness, chest pain, calf swelling, and preterm labor symptoms are absolute contraindications requiring immediate cessation of exercise and medical evaluation.",
    difficulty: "medium",
  },
  {
    chapter: 17,
    question: "Resistance training in youth has been shown to:",
    options: ["Stunt growth", "Improve strength, bone density, and self-esteem when properly supervised", "Be unsafe under all circumstances", "Only benefit children over 16"],
    correct_answer: 1,
    explanation: "When properly designed and supervised, resistance training is safe and beneficial for youth. It can improve strength, bone density, body composition, motor performance, and psychological well-being.",
    difficulty: "medium",
  },
  {
    chapter: 17,
    question: "A postnatal client cleared by her physician to exercise should initially focus on:",
    options: ["Heavy barbell squats", "Restoring core and pelvic floor stability", "High-intensity sprint training", "Training for a marathon"],
    correct_answer: 1,
    explanation: "Postnatal clients should prioritize rebuilding core and pelvic floor strength, which are compromised during pregnancy and delivery. Low-intensity stabilization exercises are the appropriate starting point.",
    difficulty: "medium",
  },
  {
    chapter: 17,
    question: "Which of the following exercises should be AVOIDED for an obese client with knee pain?",
    options: ["Seated leg press", "Deep jump squats", "Recumbent cycling", "Aquatic walking"],
    correct_answer: 1,
    explanation: "Deep jump squats place excessive stress on the knee joints and are high-impact. For an obese client with knee pain, low-impact alternatives like cycling, aquatic exercise, or machine-based movements are more appropriate.",
    difficulty: "easy",
  },

  // ─── Chapter 18: Chronic Conditions ─────────────────────────────────

  {
    chapter: 18,
    question: "For a client with controlled hypertension, which exercise guideline is most important?",
    options: ["Always train to muscular failure", "Avoid the Valsalva maneuver and monitor blood pressure", "Use maximal loads to build strength quickly", "Only perform isometric exercises"],
    correct_answer: 1,
    explanation: "Clients with hypertension should avoid the Valsalva maneuver (holding breath during exertion) as it causes dangerous spikes in blood pressure. Continuous breathing and moderate intensities are essential.",
    difficulty: "medium",
  },
  {
    chapter: 18,
    question: "A client with Type 2 diabetes should be monitored for which condition during exercise?",
    options: ["Hyperflexibility", "Hypoglycemia (low blood sugar)", "Excessive muscle growth", "Elevated flexibility"],
    correct_answer: 1,
    explanation: "Exercise increases glucose uptake by muscles. Clients with Type 2 diabetes, especially those on insulin or oral medications, are at risk of hypoglycemia during and after exercise. Blood glucose should be monitored.",
    difficulty: "medium",
  },
  {
    chapter: 18,
    question: "Osteoporosis is characterized by:",
    options: ["Excessive bone density", "Decreased bone density and increased fracture risk", "Inflammation of the joints", "Muscle wasting"],
    correct_answer: 1,
    explanation: "Osteoporosis involves a decrease in bone mineral density, making bones porous and fragile with increased fracture risk. Weight-bearing and resistance exercises help maintain and potentially improve bone density.",
    difficulty: "easy",
  },
  {
    chapter: 18,
    question: "Which type of exercise is MOST beneficial for improving bone density in a client with osteoporosis?",
    options: ["Swimming", "Weight-bearing and resistance exercise", "Seated stretching only", "Aqua aerobics"],
    correct_answer: 1,
    explanation: "Weight-bearing exercises (walking, jogging) and resistance training apply mechanical stress to bones, stimulating bone remodeling and increasing density. Non-weight-bearing exercises like swimming, while beneficial cardiovascularly, are less effective for bone health.",
    difficulty: "medium",
  },
  {
    chapter: 18,
    question: "A client with coronary artery disease has been cleared for exercise. Which guideline should the trainer follow?",
    options: ["Begin with maximal exertion testing", "Use moderate intensity (40-80% HRR), monitor for signs and symptoms, and follow physician guidelines", "Avoid all cardiovascular exercise", "Train only with heavy resistance"],
    correct_answer: 1,
    explanation: "Clients with coronary artery disease should train at moderate, physician-recommended intensities while being monitored for symptoms such as chest pain, dizziness, or unusual shortness of breath.",
    difficulty: "medium",
  },
  {
    chapter: 18,
    question: "A client with diabetes arrives for a session and reports their blood glucose is 70 mg/dL. The trainer should:",
    options: ["Begin the workout as planned", "Have the client consume a fast-acting carbohydrate and recheck before exercising", "Increase exercise intensity to use more glucose", "Send the client home without exercise"],
    correct_answer: 1,
    explanation: "Blood glucose below 100 mg/dL before exercise increases hypoglycemia risk. The client should consume 15-20g of fast-acting carbohydrate, wait 15 minutes, and recheck. Exercise should not begin until glucose is in a safe range.",
    difficulty: "hard",
  },
  {
    chapter: 18,
    question: "For a client with osteoporosis, which exercise should be AVOIDED?",
    options: ["Standing dumbbell press", "Walking lunges", "Loaded spinal flexion exercises like weighted sit-ups", "Wall push-ups"],
    correct_answer: 2,
    explanation: "Loaded spinal flexion (bending forward under load) significantly increases fracture risk in the vertebrae of clients with osteoporosis. Exercises that maintain a neutral spine are safer.",
    difficulty: "hard",
  },
  {
    chapter: 18,
    question: "Regular exercise has been shown to help manage hypertension by:",
    options: ["Permanently eliminating the need for medication", "Reducing resting blood pressure by approximately 5-7 mmHg", "Increasing peripheral vascular resistance", "Raising resting heart rate"],
    correct_answer: 1,
    explanation: "Regular aerobic exercise can reduce systolic blood pressure by approximately 5-7 mmHg in individuals with hypertension. While beneficial, exercise may complement but does not necessarily replace medication.",
    difficulty: "medium",
  },
  {
    chapter: 18,
    question: "Which is an absolute contraindication to exercise?",
    options: ["Controlled Type 2 diabetes", "Mild obesity", "Unstable angina or uncontrolled cardiac arrhythmias", "Mild hypertension managed with medication"],
    correct_answer: 2,
    explanation: "Unstable angina and uncontrolled cardiac arrhythmias are absolute contraindications to exercise, meaning exercise should NOT be performed until the condition is medically stabilized.",
    difficulty: "medium",
  },
  {
    chapter: 18,
    question: "A client with asthma should be advised to:",
    options: ["Avoid all exercise", "Carry their rescue inhaler and perform a gradual warm-up before exercise", "Only exercise outdoors in cold weather", "Skip the warm-up to save time for training"],
    correct_answer: 1,
    explanation: "Clients with asthma should always have their rescue inhaler accessible. A proper warm-up (10-15 minutes) can reduce the likelihood of exercise-induced bronchoconstriction. Cold, dry air may trigger symptoms.",
    difficulty: "easy",
  },

  // ─── Chapter 19: Scope of Practice & Professionalism ────────────────

  {
    chapter: 19,
    question: "A personal trainer's scope of practice INCLUDES:",
    options: ["Diagnosing injuries", "Prescribing specific diets for medical conditions", "Designing exercise programs and providing general wellness information", "Recommending clients stop taking prescribed medications"],
    correct_answer: 2,
    explanation: "Personal trainers are qualified to design exercise programs, provide general wellness and nutritional guidance, and motivate clients. Diagnosing injuries, prescribing medical diets, or making medication recommendations falls outside their scope.",
    difficulty: "easy",
  },
  {
    chapter: 19,
    question: "A client tells their trainer they have been experiencing sharp chest pain during exercise. The trainer should:",
    options: ["Continue the session at a lower intensity", "Diagnose the issue and modify exercises accordingly", "Stop the session and refer the client to a medical professional immediately", "Ignore it if the client wants to continue"],
    correct_answer: 2,
    explanation: "Chest pain during exercise is a potential medical emergency. The trainer should stop the session immediately and refer the client to a medical professional. Continuing exercise could be life-threatening.",
    difficulty: "easy",
  },
  {
    chapter: 19,
    question: "Professional liability insurance protects a personal trainer against:",
    options: ["Loss of personal property", "Claims of negligence or injury arising from professional services", "Losing clients to competitors", "Equipment malfunction at a gym"],
    correct_answer: 1,
    explanation: "Professional liability (malpractice) insurance protects trainers against legal claims alleging negligence, injury, or harm resulting from their professional services and advice.",
    difficulty: "easy",
  },
  {
    chapter: 19,
    question: "An informed consent form serves to:",
    options: ["Replace the need for a PAR-Q", "Ensure the client understands the risks of exercise and agrees to participate", "Eliminate all legal liability for the trainer", "Diagnose pre-existing conditions"],
    correct_answer: 1,
    explanation: "An informed consent form documents that the client has been educated about the potential risks and benefits of exercise and voluntarily agrees to participate. It does not eliminate all liability.",
    difficulty: "medium",
  },
  {
    chapter: 19,
    question: "A trainer observes another trainer at their gym performing exercises with a client that appear unsafe. The most professional course of action is:",
    options: ["Post about it on social media", "Confront the other trainer in front of their client", "Report the concern to the fitness manager or supervisor privately", "Ignore it because it's not their client"],
    correct_answer: 2,
    explanation: "Professional conduct requires addressing safety concerns through proper channels. Reporting to a supervisor privately protects client safety while maintaining professional respect and appropriate boundaries.",
    difficulty: "medium",
  },
  {
    chapter: 19,
    question: "Which document should a new client complete BEFORE starting any exercise program?",
    options: ["A workout journal", "A Physical Activity Readiness Questionnaire (PAR-Q) and health history form", "A supplement order form", "A body composition goal sheet only"],
    correct_answer: 1,
    explanation: "The PAR-Q and health history form help identify contraindications, risk factors, and medical conditions that may require physician clearance before exercise. This is a mandatory pre-participation step.",
    difficulty: "easy",
  },
  {
    chapter: 19,
    question: "Client confidentiality means a trainer should:",
    options: ["Share client progress photos on social media without permission", "Discuss a client's health conditions with other trainers casually", "Protect all personal health and fitness information and only share with written consent", "Only keep records for one week"],
    correct_answer: 2,
    explanation: "Client confidentiality requires protecting all personal health information. Sharing any details requires written consent from the client. This builds trust and is a legal and ethical obligation.",
    difficulty: "easy",
  },
  {
    chapter: 19,
    question: "A personal trainer who provides a specific meal plan for a client with Crohn's disease is:",
    options: ["Demonstrating advanced knowledge", "Operating outside their scope of practice", "Following best practices", "Meeting the client's needs appropriately"],
    correct_answer: 1,
    explanation: "Providing specific meal plans for medical conditions like Crohn's disease is medical nutrition therapy, which requires a registered dietitian or other qualified healthcare provider. This is outside a trainer's scope of practice.",
    difficulty: "medium",
  },
  {
    chapter: 19,
    question: "Maintaining current CPR/AED certification is:",
    options: ["Optional for certified personal trainers", "Required by most certification organizations and facilities", "Only needed for trainers working with seniors", "Not related to scope of practice"],
    correct_answer: 1,
    explanation: "Current CPR/AED certification is required by NASM and most fitness facilities. Trainers must be prepared to respond to cardiac emergencies, and keeping this certification current is a professional obligation.",
    difficulty: "easy",
  },
  {
    chapter: 19,
    question: "A trainer develops a romantic relationship with a current client. This is considered:",
    options: ["Acceptable if both parties agree", "A violation of professional boundaries and ethical guidelines", "Normal in the fitness industry", "Acceptable with written consent"],
    correct_answer: 1,
    explanation: "Romantic relationships with current clients violate professional boundaries and ethical guidelines. The power dynamic between trainer and client can compromise professional judgment, safety, and the client's best interests.",
    difficulty: "medium",
  },

  // ─── Chapter 20: Business & Sales ───────────────────────────────────

  {
    chapter: 20,
    question: "Client retention is MOST influenced by:",
    options: ["Offering the lowest prices", "Building rapport, delivering results, and providing a positive experience", "Having the newest equipment", "Training every client the same way"],
    correct_answer: 1,
    explanation: "Client retention is driven by the relationship between trainer and client, consistent results, and positive training experiences. Personalization, communication, and genuine care are more influential than price alone.",
    difficulty: "easy",
  },
  {
    chapter: 20,
    question: "During a sales consultation, a prospective client says, 'I'm not sure I can afford personal training.' The best response is:",
    options: ["Offer to train them for free", "Ignore the objection and push for a sale", "Acknowledge the concern, discuss the value and investment in their health, and explore flexible options", "Tell them they can't afford NOT to train"],
    correct_answer: 2,
    explanation: "Handling price objections effectively involves acknowledging the concern empathetically, reframing the cost as an investment in health, and presenting flexible payment or package options that fit their budget.",
    difficulty: "medium",
  },
  {
    chapter: 20,
    question: "The most effective way to generate new personal training clients is through:",
    options: ["Cold calling random people", "Referrals from satisfied current clients", "Posting flyers only", "Waiting for clients to approach you"],
    correct_answer: 1,
    explanation: "Referrals from satisfied clients are the most effective and cost-efficient way to generate new business. Happy clients become advocates and provide credible, trust-based recommendations.",
    difficulty: "easy",
  },
  {
    chapter: 20,
    question: "A personal trainer's 'elevator pitch' should:",
    options: ["Be 10 minutes long and highly detailed", "Concisely communicate who they help, what problem they solve, and the results they deliver in under 60 seconds", "Only include pricing information", "Focus entirely on their certifications and credentials"],
    correct_answer: 1,
    explanation: "An elevator pitch is a brief, compelling introduction that communicates your value proposition — who you help, what problem you solve, and the outcomes you deliver — in approximately 30-60 seconds.",
    difficulty: "medium",
  },
  {
    chapter: 20,
    question: "Which of the following is a key component of a successful first session with a new client?",
    options: ["Pushing them to complete failure to show your training style", "Building rapport, reviewing goals, conducting assessments, and creating a positive experience", "Spending the entire session on paperwork", "Showing them every machine in the gym"],
    correct_answer: 1,
    explanation: "The first session should build rapport, review goals, conduct initial assessments, introduce basic exercises with proper form, and create an overall positive experience that motivates the client to return.",
    difficulty: "easy",
  },
  {
    chapter: 20,
    question: "Net promoter score (NPS) in a fitness business context measures:",
    options: ["Monthly revenue", "How likely clients are to recommend your services to others", "The number of new memberships sold", "Total social media followers"],
    correct_answer: 1,
    explanation: "Net Promoter Score measures customer loyalty by asking how likely someone is to recommend your services. High NPS indicates strong client satisfaction and predicts referral-based growth.",
    difficulty: "hard",
  },
  {
    chapter: 20,
    question: "A personal trainer who tracks session completion rates, renewal rates, and client outcomes is practicing:",
    options: ["Micromanagement", "Evidence-based business management using key performance indicators (KPIs)", "Unnecessary administrative work", "Obsessive behavior"],
    correct_answer: 1,
    explanation: "Tracking KPIs like session completion rates, renewal rates, and client outcomes allows trainers to evaluate business health, identify areas for improvement, and make data-driven decisions.",
    difficulty: "medium",
  },
  {
    chapter: 20,
    question: "Social media marketing for personal trainers is most effective when:",
    options: ["Posting only selfies and personal content", "Providing consistent value through educational content, client success stories, and genuine engagement", "Buying followers to appear popular", "Posting once per year"],
    correct_answer: 1,
    explanation: "Effective social media marketing provides value through educational content, demonstrates expertise, shares authentic client success stories, and builds genuine community engagement.",
    difficulty: "easy",
  },
  {
    chapter: 20,
    question: "During a client consultation, 'active listening' involves:",
    options: ["Planning your response while the client speaks", "Focusing on the sale rather than the client's needs", "Giving full attention, asking clarifying questions, and reflecting back what was heard", "Interrupting to share your expertise"],
    correct_answer: 2,
    explanation: "Active listening requires full attention to the speaker, asking clarifying questions to deepen understanding, and reflecting or paraphrasing to confirm comprehension. It builds trust and helps identify true client needs.",
    difficulty: "easy",
  },
  {
    chapter: 20,
    question: "A trainer who offers a free introductory session is using which marketing strategy?",
    options: ["Loss leader / trial offer", "Bait and switch", "Hard selling", "Price gouging"],
    correct_answer: 0,
    explanation: "A free introductory session is a loss leader or trial offer strategy. It allows potential clients to experience the trainer's service with no risk, building trust and demonstrating value before asking for commitment.",
    difficulty: "medium",
  },
  {
    chapter: 20,
    question: "Which approach is MOST effective for handling a client who is considering canceling their training package?",
    options: ["Let them cancel without discussion", "Guilt-trip them into staying", "Have an open conversation to understand their concerns, address objections, and explore solutions", "Offer a full refund immediately"],
    correct_answer: 2,
    explanation: "Open communication helps uncover the real reasons behind cancellation. Understanding concerns (financial, scheduling, results) allows the trainer to collaboratively find solutions and demonstrate ongoing value.",
    difficulty: "medium",
  },
];
