// Starter quiz questions — enough for initial studying
// Full content seeding happens in Phase 9

export const seedQuestions = [
  // ============================================================
  // Chapter 1: Evidence-Based Practice & Integrated Training
  // ============================================================
  {
    chapter: 1,
    question: "What is the primary goal of NASM's integrated training approach?",
    options: ["Maximize muscle size", "Improve all functional abilities simultaneously", "Focus exclusively on strength", "Train only cardiovascular endurance"],
    correct_answer: 1,
    explanation: "NASM's integrated training combines flexibility, core, balance, reactive, resistance, and cardio training to improve all functional abilities — not just one area in isolation.",
    difficulty: "easy",
  },
  {
    chapter: 1,
    question: "Evidence-based practice in personal training relies on which three components?",
    options: ["Cost, availability, popularity", "Scientific evidence, clinical experience, client values", "Equipment, facility, schedule", "Certification, insurance, marketing"],
    correct_answer: 1,
    explanation: "Evidence-based practice integrates the best available scientific evidence with clinical expertise and individual client values/preferences to guide training decisions.",
    difficulty: "medium",
  },
  {
    chapter: 1,
    question: "Which of the following best describes the kinetic chain concept?",
    options: ["A sequence of exercises in a workout", "The interrelation of the nervous, muscular, and skeletal systems", "A type of resistance training equipment", "The order of energy system activation during exercise"],
    correct_answer: 1,
    explanation: "The human movement system (kinetic chain) describes how the nervous, muscular, and skeletal systems work together interdependently. Dysfunction in one component affects the others.",
    difficulty: "easy",
  },
  {
    chapter: 1,
    question: "A personal trainer notices a new research study contradicts their current programming approach. According to evidence-based practice, what should they do?",
    options: ["Ignore the study and continue current methods", "Immediately change all client programs", "Evaluate the study quality, consider clinical experience, and adapt as appropriate", "Wait for at least five confirming studies before making changes"],
    correct_answer: 2,
    explanation: "Evidence-based practice requires critically evaluating research quality while integrating it with professional experience and client needs — not blindly following or ignoring any single study.",
    difficulty: "hard",
  },
  {
    chapter: 1,
    question: "What does the NASM OPT model stand for?",
    options: ["Optimal Power Training", "Optimum Performance Training", "Overhead Press Technique", "Organized Physical Therapy"],
    correct_answer: 1,
    explanation: "The OPT model stands for Optimum Performance Training. It is NASM's systematic approach to program design that progresses clients through stabilization, strength, and power levels.",
    difficulty: "easy",
  },
  {
    chapter: 1,
    question: "Which of the following is the most significant barrier to physical activity in the general population?",
    options: ["Lack of equipment", "Perceived lack of time", "Absence of a training partner", "High cost of gym membership"],
    correct_answer: 1,
    explanation: "Research consistently shows that perceived lack of time is the most commonly cited barrier to physical activity. Effective trainers help clients overcome this through efficient programming and scheduling strategies.",
    difficulty: "medium",
  },
  {
    chapter: 1,
    question: "What percentage of American adults meet the recommended physical activity guidelines?",
    options: ["About 75%", "About 50%", "Less than 25%", "Over 90%"],
    correct_answer: 2,
    explanation: "Fewer than 25% of American adults meet the recommended physical activity guidelines, contributing to the high rates of chronic disease and obesity. This highlights the critical role of fitness professionals.",
    difficulty: "medium",
  },
  {
    chapter: 1,
    question: "A client states they want to 'get toned.' Using evidence-based practice, the trainer should:",
    options: ["Design a program using only light weights and high reps", "Clarify the client's specific goals and design a program based on scientific principles of body composition change", "Tell the client that 'toning' is not a real fitness concept", "Recommend only cardiovascular exercise"],
    correct_answer: 1,
    explanation: "Evidence-based practice requires understanding client values (their goal of 'toning') and translating that into a scientifically sound program that addresses body composition through resistance training, cardio, and nutrition guidance.",
    difficulty: "medium",
  },
  {
    chapter: 1,
    question: "Which chronic disease is most directly linked to physical inactivity?",
    options: ["Skin cancer", "Type 2 diabetes", "Allergies", "Cataracts"],
    correct_answer: 1,
    explanation: "Type 2 diabetes is strongly linked to physical inactivity and poor diet. Regular exercise improves insulin sensitivity and helps manage blood glucose levels.",
    difficulty: "easy",
  },
  {
    chapter: 1,
    question: "The integrated training approach differs from traditional training primarily because it:",
    options: ["Uses heavier weights", "Addresses multiple components of fitness in each workout", "Eliminates the need for cardiovascular exercise", "Focuses on one muscle group per session"],
    correct_answer: 1,
    explanation: "Integrated training incorporates flexibility, cardiorespiratory, core, balance, reactive, and resistance training into each session, rather than isolating single components as traditional approaches often do.",
    difficulty: "easy",
  },
  {
    chapter: 1,
    question: "When a personal trainer encounters a client with a medical condition outside their scope, they should:",
    options: ["Attempt to treat the condition with exercise", "Refer the client to an appropriate healthcare professional", "Refuse to train the client entirely", "Research the condition online and proceed independently"],
    correct_answer: 1,
    explanation: "Trainers must recognize the limits of their scope of practice and refer clients to qualified healthcare professionals when medical conditions are present. They can still train the client within their scope after medical clearance.",
    difficulty: "easy",
  },
  {
    chapter: 1,
    question: "Which of the following represents a modifiable risk factor for chronic disease?",
    options: ["Age", "Gender", "Physical inactivity", "Family history"],
    correct_answer: 2,
    explanation: "Physical inactivity is a modifiable risk factor — it can be changed through behavior. Age, gender, and family history are non-modifiable risk factors that cannot be altered.",
    difficulty: "medium",
  },

  // ============================================================
  // Chapter 2: Anatomy, Muscle Types, Nervous System, Proprioceptors
  // ============================================================
  {
    chapter: 2,
    question: "Which type of muscle fiber is best suited for endurance activities?",
    options: ["Type II (fast-twitch)", "Type I (slow-twitch)", "Type IIx (fast-twitch glycolytic)", "Type III (super fast-twitch)"],
    correct_answer: 1,
    explanation: "Type I (slow-twitch) fibers are fatigue-resistant and well-suited for sustained, endurance-based activities. They use aerobic metabolism primarily.",
    difficulty: "easy",
  },
  {
    chapter: 2,
    question: "What is the role of the Golgi tendon organ (GTO)?",
    options: ["Detect changes in muscle length", "Sense changes in muscular tension and cause relaxation", "Increase muscle contraction speed", "Store elastic energy"],
    correct_answer: 1,
    explanation: "The GTO is a sensory receptor in tendons that senses changes in muscular tension. When stimulated (like during a sustained stretch), it causes the muscle to relax — this is called autogenic inhibition.",
    difficulty: "medium",
  },
  {
    chapter: 2,
    question: "What is the function of a synergist muscle?",
    options: ["Oppose the primary mover", "Assist the primary mover in performing a movement", "Stabilize joints not directly involved", "Generate maximum force independently"],
    correct_answer: 1,
    explanation: "A synergist assists the agonist (primary mover) in producing a desired movement. For example, the brachialis is a synergist to the biceps during elbow flexion.",
    difficulty: "easy",
  },
  {
    chapter: 2,
    question: "Muscle spindles are sensitive to changes in:",
    options: ["Muscular tension", "Muscle length and rate of length change", "Blood pressure within the muscle", "Muscle temperature"],
    correct_answer: 1,
    explanation: "Muscle spindles are proprioceptors located within the muscle belly that detect changes in muscle length and the rate of that change. When a muscle is stretched quickly, muscle spindles trigger the stretch reflex to prevent overstretching.",
    difficulty: "medium",
  },
  {
    chapter: 2,
    question: "The three components of the nervous system that control human movement are:",
    options: ["Brain, heart, lungs", "Central, peripheral, and autonomic nervous systems", "Sensory, integrating, and motor functions", "Cerebrum, cerebellum, and brainstem"],
    correct_answer: 2,
    explanation: "The nervous system controls movement through three basic functions: sensing (sensory input from the environment), integrating (processing and interpreting the sensory information), and responding (motor output to muscles).",
    difficulty: "medium",
  },
  {
    chapter: 2,
    question: "Which connective tissue directly surrounds individual muscle fibers?",
    options: ["Epimysium", "Perimysium", "Endomysium", "Fascia"],
    correct_answer: 2,
    explanation: "The endomysium is the innermost layer of connective tissue that surrounds individual muscle fibers. The perimysium surrounds bundles of fibers (fascicles), and the epimysium surrounds the entire muscle.",
    difficulty: "medium",
  },
  {
    chapter: 2,
    question: "A client rapidly stretches their hamstring and feels it immediately contract. This response is caused by:",
    options: ["The Golgi tendon organ", "The muscle spindle activating the stretch reflex", "Voluntary muscle contraction", "Autogenic inhibition"],
    correct_answer: 1,
    explanation: "The muscle spindle detects rapid changes in muscle length and triggers the stretch reflex (myotatic reflex), causing the muscle to contract to protect itself from being overstretched.",
    difficulty: "hard",
  },
  {
    chapter: 2,
    question: "The sliding filament theory describes:",
    options: ["How bones glide over each other at joints", "The mechanism of muscular contraction at the sarcomere level", "The movement of fascia during stretching", "How nerve impulses travel along axons"],
    correct_answer: 1,
    explanation: "The sliding filament theory explains how actin and myosin filaments slide past each other within the sarcomere to produce muscle contraction. The filaments don't shorten themselves — they overlap more.",
    difficulty: "medium",
  },
  {
    chapter: 2,
    question: "Which division of the nervous system is responsible for the 'fight or flight' response?",
    options: ["Parasympathetic nervous system", "Somatic nervous system", "Sympathetic nervous system", "Central nervous system"],
    correct_answer: 2,
    explanation: "The sympathetic nervous system activates the fight-or-flight response, increasing heart rate, blood pressure, and energy mobilization. The parasympathetic system promotes rest and recovery.",
    difficulty: "easy",
  },
  {
    chapter: 2,
    question: "The point where a motor neuron meets a muscle fiber is called the:",
    options: ["Synapse", "Neuromuscular junction", "Motor cortex", "Proprioceptor"],
    correct_answer: 1,
    explanation: "The neuromuscular junction is the specialized synapse where a motor neuron communicates with a muscle fiber, triggering contraction through the release of acetylcholine.",
    difficulty: "easy",
  },
  {
    chapter: 2,
    question: "Type II muscle fibers are characterized by:",
    options: ["High oxidative capacity and slow contraction speed", "Low force production and high endurance", "High force production and fast contraction speed", "High mitochondrial density and slow fatigue"],
    correct_answer: 2,
    explanation: "Type II (fast-twitch) fibers produce high force, contract quickly, but fatigue faster than Type I fibers. They rely more on anaerobic metabolism and are recruited for powerful, explosive movements.",
    difficulty: "easy",
  },
  {
    chapter: 2,
    question: "Autogenic inhibition occurs when:",
    options: ["Muscle spindles cause a muscle to contract", "The GTO senses excessive tension and causes the muscle to relax", "An antagonist muscle overrides the agonist", "The brain consciously relaxes a muscle"],
    correct_answer: 1,
    explanation: "Autogenic inhibition is the process by which the GTO, sensing excessive tension in a muscle-tendon unit, causes that same muscle to relax. This protective mechanism is the basis for static stretching and SMR techniques.",
    difficulty: "medium",
  },
  {
    chapter: 2,
    question: "A motor unit consists of:",
    options: ["A single muscle fiber and all its nuclei", "A motor neuron and all the muscle fibers it innervates", "The entire muscle and its nerve supply", "Two antagonistic muscles working together"],
    correct_answer: 1,
    explanation: "A motor unit is a motor neuron and all the muscle fibers it controls. When the motor neuron fires, all fibers in that motor unit contract simultaneously (all-or-nothing principle).",
    difficulty: "medium",
  },
  {
    chapter: 2,
    question: "During a 30-second sustained static stretch, which proprioceptor is primarily responsible for the gradual relaxation felt in the muscle?",
    options: ["Muscle spindle", "Golgi tendon organ", "Pacinian corpuscle", "Ruffini ending"],
    correct_answer: 1,
    explanation: "During a sustained stretch, the GTO detects the prolonged tension in the tendon and triggers autogenic inhibition, causing the muscle to relax gradually. This is why holding a stretch for 30 seconds is recommended.",
    difficulty: "hard",
  },

  // ============================================================
  // Chapter 3: Cardiorespiratory System
  // ============================================================
  {
    chapter: 3,
    question: "What is the primary function of the cardiorespiratory system?",
    options: ["Produce hormones for muscle growth", "Transport oxygen and nutrients to tissues and remove waste products", "Generate body heat exclusively", "Maintain skeletal alignment"],
    correct_answer: 1,
    explanation: "The cardiorespiratory system's primary function is to deliver oxygen and nutrients to working tissues while removing metabolic waste products like carbon dioxide and lactic acid.",
    difficulty: "easy",
  },
  {
    chapter: 3,
    question: "Stroke volume is defined as:",
    options: ["The total volume of blood in the body", "The amount of blood pumped per heartbeat", "The number of heartbeats per minute", "The blood pressure during contraction"],
    correct_answer: 1,
    explanation: "Stroke volume is the amount of blood ejected from the left ventricle with each heartbeat. Cardiac output equals stroke volume multiplied by heart rate (Q = SV x HR).",
    difficulty: "easy",
  },
  {
    chapter: 3,
    question: "VO2 max represents:",
    options: ["The maximum heart rate a person can achieve", "The maximum amount of oxygen the body can use during exercise", "The volume of air in the lungs at rest", "The maximum blood pressure during exercise"],
    correct_answer: 1,
    explanation: "VO2 max is the maximum rate of oxygen consumption during incremental exercise. It is considered the best indicator of cardiorespiratory fitness and aerobic endurance capacity.",
    difficulty: "easy",
  },
  {
    chapter: 3,
    question: "As a result of chronic aerobic training, resting heart rate typically:",
    options: ["Increases due to cardiac stress", "Remains unchanged", "Decreases because stroke volume increases", "Becomes irregular"],
    correct_answer: 2,
    explanation: "Chronic aerobic training increases stroke volume (the heart pumps more blood per beat), so fewer beats per minute are needed to maintain the same cardiac output at rest, resulting in a lower resting heart rate.",
    difficulty: "medium",
  },
  {
    chapter: 3,
    question: "Normal resting blood pressure is classified as:",
    options: ["140/90 mmHg", "120/80 mmHg or less", "130/85 mmHg", "100/60 mmHg"],
    correct_answer: 1,
    explanation: "Normal resting blood pressure is classified as systolic less than 120 mmHg and diastolic less than 80 mmHg. Values above 130/80 are now considered hypertensive by current guidelines.",
    difficulty: "easy",
  },
  {
    chapter: 3,
    question: "The Valsalva maneuver during resistance training is dangerous primarily because it:",
    options: ["Reduces muscle force production", "Causes a dramatic spike in blood pressure", "Decreases oxygen delivery to muscles", "Reduces core stability"],
    correct_answer: 1,
    explanation: "The Valsalva maneuver (holding breath against a closed glottis) causes a dramatic spike in blood pressure, which can be dangerous especially for clients with hypertension or cardiovascular conditions.",
    difficulty: "medium",
  },
  {
    chapter: 3,
    question: "Which chamber of the heart pumps oxygenated blood to the body?",
    options: ["Right atrium", "Right ventricle", "Left atrium", "Left ventricle"],
    correct_answer: 3,
    explanation: "The left ventricle pumps oxygenated blood through the aorta to the systemic circulation. It has the thickest walls of all four chambers because it must generate enough pressure to push blood throughout the entire body.",
    difficulty: "easy",
  },
  {
    chapter: 3,
    question: "During exercise, blood flow is redistributed primarily to:",
    options: ["The digestive organs", "The brain only", "Working skeletal muscles", "The kidneys"],
    correct_answer: 2,
    explanation: "During exercise, blood is redirected away from non-essential organs (like the digestive system) to working skeletal muscles, which may receive up to 80-85% of cardiac output during intense exercise.",
    difficulty: "easy",
  },
  {
    chapter: 3,
    question: "A client's resting heart rate is 85 bpm. This is considered:",
    options: ["Bradycardic (low)", "Normal", "Elevated/above optimal", "Dangerous and requiring immediate referral"],
    correct_answer: 2,
    explanation: "Normal resting heart rate is 60-100 bpm, but optimal is typically 60-80 bpm. A resting heart rate of 85 bpm, while technically normal, is above optimal and suggests room for improved cardiovascular fitness.",
    difficulty: "medium",
  },
  {
    chapter: 3,
    question: "The ventilatory threshold represents the point during exercise where:",
    options: ["Breathing rate decreases", "The body shifts from primarily aerobic to anaerobic metabolism", "Heart rate reaches its maximum", "Blood pressure normalizes"],
    correct_answer: 1,
    explanation: "The ventilatory threshold is the point during increasing exercise intensity where ventilation increases disproportionately to oxygen consumption, indicating a shift toward greater anaerobic metabolism and increased lactate production.",
    difficulty: "hard",
  },
  {
    chapter: 3,
    question: "Cardiac output is calculated by:",
    options: ["Blood pressure x heart rate", "Stroke volume x heart rate", "Tidal volume x respiratory rate", "VO2 max x body weight"],
    correct_answer: 1,
    explanation: "Cardiac output (Q) = Stroke Volume (SV) x Heart Rate (HR). It represents the total volume of blood pumped by the heart per minute and increases during exercise through increases in both SV and HR.",
    difficulty: "medium",
  },
  {
    chapter: 3,
    question: "A trained endurance athlete would most likely have which of the following adaptations?",
    options: ["Smaller left ventricle and faster resting heart rate", "Larger stroke volume and lower resting heart rate", "Higher resting blood pressure and reduced VO2 max", "Decreased capillary density in muscles"],
    correct_answer: 1,
    explanation: "Chronic endurance training leads to cardiac hypertrophy (larger left ventricle), increased stroke volume, lower resting heart rate, increased capillary density, and higher VO2 max.",
    difficulty: "medium",
  },
  {
    chapter: 3,
    question: "The systolic blood pressure reading represents:",
    options: ["The pressure when the heart is at rest between beats", "The pressure when the left ventricle contracts", "The average pressure during a full cardiac cycle", "The pressure in the pulmonary arteries"],
    correct_answer: 1,
    explanation: "Systolic pressure is the peak pressure in the arteries during ventricular contraction (systole). Diastolic pressure is the pressure during the relaxation phase (diastole) between beats.",
    difficulty: "easy",
  },

  // ============================================================
  // Chapter 4: Assessments
  // ============================================================
  {
    chapter: 4,
    question: "During an overhead squat assessment, the knees moving inward (valgus) indicates:",
    options: ["Strong adductors", "Overactive adductors and underactive gluteus medius", "Proper movement mechanics", "Excessive hamstring flexibility"],
    correct_answer: 1,
    explanation: "Knee valgus (knees caving inward) during a squat indicates overactive adductors/IT band and underactive gluteus medius/maximus. This is a common compensation pattern.",
    difficulty: "medium",
  },
  {
    chapter: 4,
    question: "What are the five kinetic chain checkpoints observed during movement assessments?",
    options: ["Hands, elbows, shoulders, hips, knees", "Feet/ankles, knees, LPHC, shoulders, head", "Wrists, shoulders, spine, hips, feet", "Neck, chest, core, thighs, calves"],
    correct_answer: 1,
    explanation: "The five kinetic chain checkpoints are: feet and ankles, knees, lumbo-pelvic-hip complex (LPHC), shoulders, and head/cervical spine. These are observed from anterior, lateral, and posterior views.",
    difficulty: "medium",
  },
  {
    chapter: 4,
    question: "The PAR-Q is used to:",
    options: ["Measure maximal strength", "Identify individuals who need medical clearance before exercise", "Determine body fat percentage", "Assess cardiorespiratory endurance"],
    correct_answer: 1,
    explanation: "The Physical Activity Readiness Questionnaire (PAR-Q) is a pre-participation health screening tool that identifies individuals who may have contraindications to exercise and need physician clearance.",
    difficulty: "easy",
  },
  {
    chapter: 4,
    question: "During the overhead squat assessment, the arms falling forward indicates:",
    options: ["Strong anterior deltoids", "Overactive latissimus dorsi and underactive middle/lower trapezius", "Good shoulder mobility", "Underactive pectorals"],
    correct_answer: 1,
    explanation: "Arms falling forward suggests overactive latissimus dorsi, teres major, and pectorals, with underactive middle and lower trapezius and rhomboids. This indicates poor thoracic spine extension and shoulder mobility.",
    difficulty: "hard",
  },
  {
    chapter: 4,
    question: "Which body composition assessment method uses skinfold measurements?",
    options: ["Bioelectrical impedance", "Durnin-Womersley method", "Hydrostatic weighing", "DEXA scan"],
    correct_answer: 1,
    explanation: "The Durnin-Womersley method uses skinfold calipers to measure subcutaneous fat at specific body sites. It is a practical and accessible method for personal trainers to estimate body fat percentage.",
    difficulty: "medium",
  },
  {
    chapter: 4,
    question: "A client's feet turn out excessively during the overhead squat. Which muscles are likely overactive?",
    options: ["Tibialis anterior and gluteus medius", "Soleus, lateral gastrocnemius, and biceps femoris (short head)", "Adductors and medial hamstrings", "Quadriceps and hip flexors"],
    correct_answer: 1,
    explanation: "Feet turning out indicates overactive soleus, lateral gastrocnemius, and biceps femoris (short head), with underactive medial gastrocnemius, medial hamstrings, gracilis, and popliteus.",
    difficulty: "hard",
  },
  {
    chapter: 4,
    question: "The YMCA 3-minute step test is used to assess:",
    options: ["Muscular endurance", "Flexibility", "Cardiorespiratory fitness", "Balance"],
    correct_answer: 2,
    explanation: "The YMCA 3-minute step test is a submaximal cardiorespiratory assessment that estimates aerobic fitness by measuring heart rate recovery after stepping on and off a 12-inch bench at a set cadence.",
    difficulty: "easy",
  },
  {
    chapter: 4,
    question: "During the overhead squat, an excessive forward lean of the torso most likely indicates:",
    options: ["Strong core musculature", "Overactive soleus/gastrocnemius and underactive gluteus maximus/erector spinae", "Tight hamstrings only", "Weak quadriceps only"],
    correct_answer: 1,
    explanation: "An excessive forward lean suggests overactive soleus, gastrocnemius, hip flexors, and abdominals, with underactive gluteus maximus, erector spinae, and anterior tibialis.",
    difficulty: "hard",
  },
  {
    chapter: 4,
    question: "What is the recommended order for conducting fitness assessments?",
    options: ["Strength tests, cardio tests, flexibility tests", "Health history, resting vitals, body composition, movement assessments, performance tests", "Movement assessments first, then health history", "Any order is equally effective"],
    correct_answer: 1,
    explanation: "The proper assessment order ensures safety: start with health history/PAR-Q, then resting vitals (HR, BP), body composition, postural/movement assessments, and finally performance tests if appropriate.",
    difficulty: "medium",
  },
  {
    chapter: 4,
    question: "A client has a resting blood pressure of 142/94 mmHg. The trainer should:",
    options: ["Begin a vigorous exercise program to lower it", "Refer the client to their physician before starting exercise", "Ignore it since the client feels fine", "Have the client do only upper body exercises"],
    correct_answer: 1,
    explanation: "A reading of 142/94 mmHg is classified as hypertensive. The trainer should refer the client to a physician for medical clearance before beginning an exercise program. This is outside the trainer's scope to manage.",
    difficulty: "medium",
  },
  {
    chapter: 4,
    question: "The single-leg squat assessment is primarily used to observe:",
    options: ["Maximal lower body strength", "Dynamic lower extremity alignment and control", "Hamstring flexibility", "Cardiovascular endurance"],
    correct_answer: 1,
    explanation: "The single-leg squat assesses dynamic lower extremity alignment, looking at the same checkpoints as the overhead squat but with the added challenge of single-leg stability to identify asymmetries.",
    difficulty: "medium",
  },
  {
    chapter: 4,
    question: "Waist-to-hip ratio is a measurement used to assess:",
    options: ["Muscular endurance", "Body fat distribution and associated health risk", "Cardiovascular fitness", "Flexibility"],
    correct_answer: 1,
    explanation: "Waist-to-hip ratio assesses body fat distribution. A higher ratio (more abdominal fat) is associated with greater risk of cardiovascular disease, diabetes, and metabolic syndrome.",
    difficulty: "easy",
  },

  // ============================================================
  // Chapter 5: Biomechanics
  // ============================================================
  {
    chapter: 5,
    question: "During the lowering phase of a push-up, the chest muscles are performing which type of contraction?",
    options: ["Concentric", "Isometric", "Eccentric", "Isokinetic"],
    correct_answer: 2,
    explanation: "During the lowering phase, the chest muscles lengthen under tension to control the descent — this is an eccentric contraction. The pushing-up phase is concentric.",
    difficulty: "easy",
  },
  {
    chapter: 5,
    question: "According to the force-velocity curve, what happens as concentric contraction velocity increases?",
    options: ["Force production increases", "Force production decreases", "Force stays the same", "Force becomes unpredictable"],
    correct_answer: 1,
    explanation: "The force-velocity relationship shows that as the speed of a concentric contraction increases, the force the muscle can produce decreases. This is why you can lift heavier weights slowly than quickly.",
    difficulty: "hard",
  },
  {
    chapter: 5,
    question: "The length-tension relationship states that a muscle generates the greatest force when:",
    options: ["It is fully shortened", "It is at its optimal resting length", "It is maximally stretched", "It is in a state of fatigue"],
    correct_answer: 1,
    explanation: "At the optimal resting length, there is the greatest overlap between actin and myosin filaments, allowing maximum cross-bridge formation and therefore maximum force production.",
    difficulty: "medium",
  },
  {
    chapter: 5,
    question: "An isometric contraction occurs when:",
    options: ["The muscle shortens while producing force", "The muscle lengthens while producing force", "The muscle produces force without changing length", "The muscle relaxes completely"],
    correct_answer: 2,
    explanation: "During an isometric contraction, the muscle produces force but does not change length. An example is holding a plank position or pushing against an immovable wall.",
    difficulty: "easy",
  },
  {
    chapter: 5,
    question: "A first-class lever in the human body is exemplified by:",
    options: ["A bicep curl (elbow flexion)", "Calf raise (plantar flexion)", "Nodding the head (atlanto-occipital joint)", "Shoulder abduction"],
    correct_answer: 2,
    explanation: "A first-class lever has the fulcrum between the effort and the load. The atlanto-occipital joint (nodding) is an example: the joint is between the neck muscles (effort) and the weight of the face (load).",
    difficulty: "hard",
  },
  {
    chapter: 5,
    question: "If a client has a shortened (tight) hip flexor, what effect does this have on the force-couple relationship at the pelvis?",
    options: ["It has no effect on pelvic position", "It causes a posterior pelvic tilt", "It causes an anterior pelvic tilt", "It causes lateral pelvic tilt only"],
    correct_answer: 2,
    explanation: "Tight hip flexors pull the front of the pelvis downward, creating an anterior pelvic tilt. This disrupts the force-couple relationship between the hip flexors, glutes, hamstrings, and abdominals.",
    difficulty: "medium",
  },
  {
    chapter: 5,
    question: "During a bicep curl, the biceps brachii is the:",
    options: ["Antagonist", "Stabilizer", "Agonist", "Synergist"],
    correct_answer: 2,
    explanation: "The agonist (prime mover) is the muscle primarily responsible for producing the desired movement. During a bicep curl, the biceps brachii is the agonist performing elbow flexion.",
    difficulty: "easy",
  },
  {
    chapter: 5,
    question: "The rotary component of muscle force is greatest when the angle of pull on the bone is:",
    options: ["0 degrees", "45 degrees", "90 degrees", "180 degrees"],
    correct_answer: 2,
    explanation: "The rotary component of muscle force (the component that actually produces joint rotation) is greatest when the muscle pulls at 90 degrees to the bone. At other angles, more force is directed into the joint (stabilizing component) or away from it.",
    difficulty: "hard",
  },
  {
    chapter: 5,
    question: "Reciprocal inhibition describes:",
    options: ["A muscle relaxing after sustained contraction", "The simultaneous contraction of agonist and antagonist", "The relaxation of an antagonist muscle when the agonist is activated", "The GTO causing a muscle to relax"],
    correct_answer: 2,
    explanation: "Reciprocal inhibition is the process by which activation of a muscle (agonist) causes reflexive relaxation of the opposing muscle (antagonist). For example, when the biceps contracts, the triceps is inhibited.",
    difficulty: "medium",
  },
  {
    chapter: 5,
    question: "A client performing a wall sit is primarily using which type of muscle action?",
    options: ["Concentric", "Eccentric", "Isometric", "Isokinetic"],
    correct_answer: 2,
    explanation: "During a wall sit, the quadriceps are producing force to hold the position against gravity, but the joint angle is not changing. This is an isometric (same length) contraction.",
    difficulty: "easy",
  },
  {
    chapter: 5,
    question: "Synergistic dominance occurs when:",
    options: ["The agonist and antagonist contract equally", "A synergist muscle takes over the function of a weak or inhibited prime mover", "Two muscles work together at the same intensity", "The stabilizer muscles become the prime movers in all exercises"],
    correct_answer: 1,
    explanation: "Synergistic dominance occurs when a synergist compensates for a weak or inhibited prime mover. For example, the hamstrings or erector spinae may compensate for an inhibited gluteus maximus during hip extension.",
    difficulty: "medium",
  },
  {
    chapter: 5,
    question: "During the eccentric phase of a squat, the quadriceps are:",
    options: ["Shortening to push the body up", "Lengthening while controlling the rate of descent", "Completely relaxed", "Contracting isometrically"],
    correct_answer: 1,
    explanation: "During the descent (eccentric phase) of a squat, the quadriceps lengthen under tension to control the rate at which the knees flex and the body lowers. This is a decelerating action.",
    difficulty: "easy",
  },

  // ============================================================
  // Chapter 6: Flexibility Training
  // ============================================================
  {
    chapter: 6,
    question: "What is the primary mechanism by which foam rolling (SMR) improves flexibility?",
    options: ["Stretching the muscle fibers", "Autogenic inhibition via GTO stimulation", "Increasing blood flow only", "Breaking down scar tissue"],
    correct_answer: 1,
    explanation: "Self-myofascial release (foam rolling) applies sustained pressure to soft tissue, stimulating the GTO which triggers autogenic inhibition — causing the muscle to relax and allowing greater range of motion.",
    difficulty: "medium",
  },
  {
    chapter: 6,
    question: "Static stretching is most appropriate during which phase of a workout?",
    options: ["Before any warm-up activity", "As the only warm-up method", "After the workout as part of the cool-down", "Between sets of heavy resistance training"],
    correct_answer: 2,
    explanation: "Static stretching is most appropriate during the cool-down phase. Research suggests that static stretching before activity may temporarily reduce power and strength output. It is effective post-workout for improving flexibility.",
    difficulty: "medium",
  },
  {
    chapter: 6,
    question: "How long should a static stretch be held for optimal results?",
    options: ["5-10 seconds", "15-20 seconds", "30 seconds", "2-3 minutes"],
    correct_answer: 2,
    explanation: "A static stretch should be held for approximately 30 seconds to allow the GTO to override the muscle spindle, triggering autogenic inhibition and allowing the muscle to relax and lengthen.",
    difficulty: "easy",
  },
  {
    chapter: 6,
    question: "Active-isolated stretching involves:",
    options: ["Holding a stretch for 30+ seconds with no movement", "Using a foam roller on tight muscles", "Using the agonist to actively move the limb through a range of motion, holding for 1-2 seconds", "Bouncing at the end range of motion"],
    correct_answer: 2,
    explanation: "Active-isolated stretching uses reciprocal inhibition by contracting the agonist to move the limb through a range of motion, holding for 1-2 seconds, and repeating for 5-10 reps. This inhibits the antagonist being stretched.",
    difficulty: "medium",
  },
  {
    chapter: 6,
    question: "A client who sits at a desk all day is likely to have shortened:",
    options: ["Gluteus maximus and hamstrings", "Hip flexors and pectorals", "Rhomboids and middle trapezius", "Posterior deltoids and external rotators"],
    correct_answer: 1,
    explanation: "Prolonged sitting typically leads to shortened (overactive) hip flexors, pectorals, and upper trapezius, with lengthened (underactive) glutes, deep cervical flexors, and mid/lower trapezius.",
    difficulty: "easy",
  },
  {
    chapter: 6,
    question: "Dynamic stretching is characterized by:",
    options: ["Holding a position for 30 seconds", "Applying pressure with a foam roller", "Using controlled movement through an active range of motion", "Passive partner-assisted stretching"],
    correct_answer: 2,
    explanation: "Dynamic stretching uses active movements to take joints and muscles through their full range of motion in a controlled manner. It is ideal as part of a warm-up to prepare the body for activity.",
    difficulty: "easy",
  },
  {
    chapter: 6,
    question: "When foam rolling a tender spot, the client should:",
    options: ["Roll quickly back and forth over it", "Avoid the area completely", "Hold pressure on the tender spot for at least 30 seconds", "Only foam roll areas that are not tender"],
    correct_answer: 2,
    explanation: "When a tender spot (trigger point/adhesion) is found during foam rolling, the client should hold sustained pressure on that spot for at least 30 seconds to allow the GTO to relax the tissue.",
    difficulty: "easy",
  },
  {
    chapter: 6,
    question: "The corrective flexibility strategy in the OPT model uses which combination?",
    options: ["Dynamic stretching and active-isolated stretching", "SMR and static stretching", "Ballistic stretching and PNF stretching", "Active stretching only"],
    correct_answer: 1,
    explanation: "Corrective flexibility (used in Phase 1 Stabilization) combines self-myofascial release (SMR) to inhibit overactive muscles, followed by static stretching to lengthen them. This addresses muscle imbalances.",
    difficulty: "medium",
  },
  {
    chapter: 6,
    question: "A client has overactive calves causing their heels to rise during squats. Which flexibility technique combination should be applied first?",
    options: ["Dynamic stretching of the calves", "SMR on the calves followed by static calf stretching", "Active-isolated stretching of the tibialis anterior", "Ballistic stretching of the Achilles tendon"],
    correct_answer: 1,
    explanation: "For overactive muscles causing compensation, the corrective strategy is to first foam roll (SMR) the overactive calves to reduce tension via autogenic inhibition, then statically stretch them to improve length.",
    difficulty: "medium",
  },
  {
    chapter: 6,
    question: "Which type of flexibility training uses reciprocal inhibition as its primary mechanism?",
    options: ["Static stretching", "SMR/foam rolling", "Active-isolated stretching", "Passive stretching"],
    correct_answer: 2,
    explanation: "Active-isolated stretching primarily uses reciprocal inhibition. By actively contracting the agonist (opposing muscle), the antagonist (muscle being stretched) is reflexively relaxed, allowing greater range of motion.",
    difficulty: "hard",
  },
  {
    chapter: 6,
    question: "Davis's Law states that:",
    options: ["Muscles only grow when loaded progressively", "Soft tissue remodels along the lines of stress placed upon it", "Flexibility cannot be improved after age 40", "Stretching always reduces injury risk"],
    correct_answer: 1,
    explanation: "Davis's Law describes how soft tissue (muscles, tendons, ligaments, fascia) remodels according to the stresses and demands placed upon it. This is why consistent flexibility training produces lasting tissue changes.",
    difficulty: "hard",
  },
  {
    chapter: 6,
    question: "The active flexibility strategy in the OPT model is appropriate for which training level?",
    options: ["Phase 1 — Stabilization", "Phases 2-4 — Strength", "Phase 5 — Power only", "Only for rehabilitation settings"],
    correct_answer: 1,
    explanation: "Active flexibility (SMR combined with active-isolated stretching) is used in Phases 2-4 (Strength Level) of the OPT model. It builds on corrective flexibility by incorporating more active neuromuscular control.",
    difficulty: "medium",
  },

  // ============================================================
  // Chapter 7: Cardiorespiratory Training
  // ============================================================
  {
    chapter: 7,
    question: "The FITTE factors for cardiorespiratory programming stand for:",
    options: ["Force, Intensity, Time, Type, Effort", "Frequency, Intensity, Time, Type, Enjoyment", "Flexibility, Intensity, Tempo, Training, Endurance", "Frequency, Intervals, Threshold, Type, Energy"],
    correct_answer: 1,
    explanation: "FITTE stands for Frequency (how often), Intensity (how hard), Time (duration), Type (mode of exercise), and Enjoyment (client preference). Enjoyment is key for long-term adherence.",
    difficulty: "easy",
  },
  {
    chapter: 7,
    question: "In NASM's Stage I cardiorespiratory training, the primary goal is to:",
    options: ["Maximize VO2 max", "Build an aerobic base using steady-state training at moderate intensity", "Perform high-intensity interval training", "Train at anaerobic threshold exclusively"],
    correct_answer: 1,
    explanation: "Stage I focuses on building an aerobic base with steady-state, moderate-intensity cardio (65-75% HRmax). This establishes cardiovascular fitness foundations before introducing higher intensities.",
    difficulty: "medium",
  },
  {
    chapter: 7,
    question: "The Talk Test is a simple way to estimate:",
    options: ["Maximum heart rate", "Exercise intensity relative to ventilatory threshold", "Resting metabolic rate", "Blood lactate levels"],
    correct_answer: 1,
    explanation: "The Talk Test estimates exercise intensity by whether a person can carry on a conversation. If they can talk comfortably, they are likely below the ventilatory threshold. If they cannot, they have likely exceeded it.",
    difficulty: "easy",
  },
  {
    chapter: 7,
    question: "A new client with no exercise history should begin cardio training in which NASM stage?",
    options: ["Stage III with interval training", "Stage II with moderate intervals", "Stage I with steady-state training", "Any stage based on client preference"],
    correct_answer: 2,
    explanation: "Beginners should start in Stage I to build an aerobic base with moderate, steady-state cardio. This develops foundational cardiovascular fitness and allows safe progression to higher intensities.",
    difficulty: "easy",
  },
  {
    chapter: 7,
    question: "Heart rate reserve (HRR) is calculated by:",
    options: ["Maximum heart rate minus age", "Maximum heart rate minus resting heart rate", "Resting heart rate plus age", "VO2 max divided by body weight"],
    correct_answer: 1,
    explanation: "Heart rate reserve = HRmax - HRrest. It represents the range of heart rate available for exercise. The Karvonen formula uses HRR to calculate target heart rate zones that account for individual fitness levels.",
    difficulty: "medium",
  },
  {
    chapter: 7,
    question: "Stage II of NASM's cardiorespiratory training introduces:",
    options: ["Steady-state training only", "Interval training with alternating higher and lower intensities", "Maximal sprint intervals", "Only low-intensity recovery sessions"],
    correct_answer: 1,
    explanation: "Stage II introduces interval training, alternating between higher-intensity work intervals and lower-intensity recovery intervals. This begins to challenge the anaerobic system while maintaining an aerobic base.",
    difficulty: "medium",
  },
  {
    chapter: 7,
    question: "Using the age-predicted formula, the estimated maximum heart rate for a 40-year-old is:",
    options: ["160 bpm", "180 bpm", "200 bpm", "170 bpm"],
    correct_answer: 1,
    explanation: "The age-predicted HRmax formula is 220 - age. For a 40-year-old: 220 - 40 = 180 bpm. This is an estimate with a standard deviation of about 10-12 bpm.",
    difficulty: "easy",
  },
  {
    chapter: 7,
    question: "Which of the following is a benefit of high-intensity interval training (HIIT)?",
    options: ["It only burns calories during the workout", "It produces excess post-exercise oxygen consumption (EPOC)", "It is safer than moderate-intensity exercise for beginners", "It requires no recovery between sessions"],
    correct_answer: 1,
    explanation: "HIIT produces significant EPOC (the 'afterburn effect'), meaning the body continues to burn additional calories after the workout as it restores itself to homeostasis. However, it requires adequate fitness levels and recovery time.",
    difficulty: "medium",
  },
  {
    chapter: 7,
    question: "A client exercising at 60-70% of their HRmax is training in which zone?",
    options: ["Zone 1 (recovery)", "Zone 2 (aerobic base/fat burning)", "Zone 3 (anaerobic threshold)", "Zone 4 (near maximal)"],
    correct_answer: 1,
    explanation: "Training at 60-70% HRmax falls in Zone 2, which builds the aerobic base and uses a higher proportion of fat as fuel. This zone is appropriate for building endurance and is sustainable for longer durations.",
    difficulty: "medium",
  },
  {
    chapter: 7,
    question: "Stage III of NASM's cardiorespiratory training is characterized by:",
    options: ["Low-intensity steady-state only", "Moderate interval training", "High-intensity interval training pushing near VO2 max", "Exclusively recovery-paced sessions"],
    correct_answer: 2,
    explanation: "Stage III uses high-intensity intervals that push near or at VO2 max with recovery periods. This stage is for well-conditioned clients and aims to maximize cardiorespiratory performance.",
    difficulty: "medium",
  },
  {
    chapter: 7,
    question: "A client can speak in full sentences during their cardio workout but with some difficulty. They are likely training:",
    options: ["Well below their ventilatory threshold", "Near their first ventilatory threshold", "Above their second ventilatory threshold", "At maximum intensity"],
    correct_answer: 1,
    explanation: "Being able to speak with some difficulty suggests the client is near the first ventilatory threshold — the point where breathing starts to increase disproportionately. This indicates moderate-to-vigorous intensity.",
    difficulty: "hard",
  },

  // ============================================================
  // Chapter 8: Core Training
  // ============================================================
  {
    chapter: 8,
    question: "The drawing-in maneuver activates which core muscle?",
    options: ["Rectus abdominis", "External obliques", "Transverse abdominis", "Erector spinae"],
    correct_answer: 2,
    explanation: "The drawing-in maneuver (pulling the navel toward the spine) specifically activates the transverse abdominis, the deepest core muscle that acts like a natural weight belt to stabilize the spine.",
    difficulty: "easy",
  },
  {
    chapter: 8,
    question: "The local stabilization system of the core includes which of the following muscles?",
    options: ["Rectus abdominis and external obliques", "Transverse abdominis, multifidus, and pelvic floor muscles", "Latissimus dorsi and quadratus lumborum", "Hip flexors and gluteus maximus"],
    correct_answer: 1,
    explanation: "The local stabilization system consists of muscles that attach directly to the vertebrae: transverse abdominis, multifidus, internal obliques, pelvic floor, and diaphragm. They provide intersegmental stability.",
    difficulty: "medium",
  },
  {
    chapter: 8,
    question: "The bracing maneuver differs from the drawing-in maneuver by:",
    options: ["Activating only the rectus abdominis", "Co-contracting the global muscles including the rectus abdominis, obliques, and erector spinae", "Relaxing the core entirely", "Focusing solely on the pelvic floor"],
    correct_answer: 1,
    explanation: "Bracing involves co-contracting the global core muscles (rectus abdominis, external obliques, erector spinae) as if preparing to be punched, creating a rigid cylinder of support. It is used during heavier loading.",
    difficulty: "medium",
  },
  {
    chapter: 8,
    question: "Core stabilization exercises in Phase 1 of the OPT model should involve:",
    options: ["Heavy loaded movements like barbell squats", "Exercises with little motion through the spine and pelvis", "Fast, explosive rotational movements", "Maximum repetitions of sit-ups and crunches"],
    correct_answer: 1,
    explanation: "Phase 1 core stabilization exercises involve minimal spinal motion to train the core to stabilize and resist forces. Examples include planks, bridges, and ball exercises that challenge stability without excessive movement.",
    difficulty: "easy",
  },
  {
    chapter: 8,
    question: "The global stabilization system of the core includes the:",
    options: ["Transverse abdominis and multifidus", "Quadratus lumborum, obliques, and hip adductors", "Biceps and triceps", "Diaphragm and pelvic floor only"],
    correct_answer: 1,
    explanation: "The global stabilization system includes muscles that attach from the pelvis to the spine: quadratus lumborum, obliques, and hip adductors. They transfer loads between upper and lower extremities and provide trunk stability.",
    difficulty: "medium",
  },
  {
    chapter: 8,
    question: "A client has difficulty maintaining a neutral spine during a plank. The trainer should:",
    options: ["Have them hold the plank longer to build endurance", "Regress to a modified plank (knees on ground) and teach the drawing-in maneuver", "Progress them to a side plank for more challenge", "Eliminate core exercises from their program"],
    correct_answer: 1,
    explanation: "When a client cannot maintain proper form, the exercise should be regressed. A modified plank with knees down reduces the demand while allowing the client to learn the drawing-in maneuver and build proper stabilization patterns.",
    difficulty: "easy",
  },
  {
    chapter: 8,
    question: "The movement system of the core includes which muscles?",
    options: ["Transverse abdominis and internal obliques", "Latissimus dorsi, hip flexors, hamstrings, and quadriceps", "Pelvic floor and diaphragm", "Multifidus and rotatores"],
    correct_answer: 1,
    explanation: "The global movement system includes muscles that attach the spine/pelvis to the extremities: latissimus dorsi, hip flexors, hamstrings, and quadriceps. These muscles are primarily responsible for producing movement.",
    difficulty: "medium",
  },
  {
    chapter: 8,
    question: "Core strength exercises in Phase 2-4 of the OPT model progress by:",
    options: ["Removing all stabilization demands", "Introducing controlled spinal motion against resistance through a full range of motion", "Only using heavy machines", "Performing core exercises on unstable surfaces at maximal speed"],
    correct_answer: 1,
    explanation: "Core strength training in Phases 2-4 introduces more dynamic movements with controlled spinal motion, such as cable rotations and medicine ball exercises, building on the stabilization foundation from Phase 1.",
    difficulty: "medium",
  },
  {
    chapter: 8,
    question: "A weak core can contribute to all of the following EXCEPT:",
    options: ["Low back pain", "Knee valgus during squatting", "Improved power transfer between limbs", "Excessive forward lean during overhead squat"],
    correct_answer: 2,
    explanation: "A weak core impairs power transfer between limbs — it does not improve it. A weak core contributes to low back pain, compensations like knee valgus, forward lean, and overall decreased functional performance.",
    difficulty: "easy",
  },
  {
    chapter: 8,
    question: "Core power exercises in Phase 5 of the OPT model include:",
    options: ["Slow, sustained planks held for 60+ seconds", "Explosive movements like medicine ball throws and rotation chops at high velocity", "Machine-based crunches at heavy loads", "Only isometric exercises with added weight"],
    correct_answer: 1,
    explanation: "Core power exercises involve explosive, high-velocity movements such as medicine ball throws, rotation chops, and slam balls. They train the core to produce and transfer force rapidly.",
    difficulty: "easy",
  },
  {
    chapter: 8,
    question: "Which of the following best explains why core training should precede extremity training in a workout?",
    options: ["Core muscles need the most warm-up time", "A fatigued core cannot properly stabilize the spine during loaded movements", "Core exercises burn more calories than other exercises", "Core muscles recover faster than extremity muscles"],
    correct_answer: 1,
    explanation: "The core must be activated and ready to stabilize the spine before loading the extremities. Training core early ensures it can function as a stable base during subsequent compound exercises, reducing injury risk.",
    difficulty: "hard",
  },

  // ============================================================
  // Chapter 9: Balance Training
  // ============================================================
  {
    chapter: 9,
    question: "Balance training primarily improves which physiological system?",
    options: ["Cardiovascular system", "Proprioceptive and neuromuscular systems", "Digestive system", "Endocrine system"],
    correct_answer: 1,
    explanation: "Balance training enhances the proprioceptive and neuromuscular systems by challenging the body's ability to sense its position in space and react to maintain stability. Proprioceptors in joints, muscles, and skin are trained.",
    difficulty: "easy",
  },
  {
    chapter: 9,
    question: "Which of the following is a proprioceptor involved in balance?",
    options: ["Red blood cells", "Muscle spindles", "Mitochondria", "Motor neurons"],
    correct_answer: 1,
    explanation: "Muscle spindles are proprioceptors that sense changes in muscle length and rate of length change. Along with the GTO, joint receptors, and vestibular system, they provide critical sensory information for maintaining balance.",
    difficulty: "easy",
  },
  {
    chapter: 9,
    question: "A client who can easily balance on one leg on a stable surface should be progressed to:",
    options: ["Two legs on a stable surface", "One leg on an unstable surface (foam pad, BOSU, etc.)", "Seated exercises only", "Heavy bilateral squats"],
    correct_answer: 1,
    explanation: "Balance progressions move from stable to unstable surfaces: two legs stable, one leg stable, two legs unstable, one leg unstable. Adding an unstable surface increases the proprioceptive demand.",
    difficulty: "easy",
  },
  {
    chapter: 9,
    question: "Phase 1 (Stabilization) balance exercises should involve:",
    options: ["Dynamic movements with jumping and hopping", "Minimal joint movement while maintaining balance on stable or unstable surfaces", "Heavy loaded single-leg exercises", "Explosive multidirectional movements"],
    correct_answer: 1,
    explanation: "Stabilization balance exercises involve minimal joint motion and focus on maintaining a stable position. Examples include single-leg balance and single-leg balance on a foam pad. This trains the neuromuscular system to stabilize.",
    difficulty: "medium",
  },
  {
    chapter: 9,
    question: "The three sensory systems that contribute to balance are:",
    options: ["Muscular, skeletal, and cardiovascular", "Visual, vestibular, and somatosensory (proprioceptive)", "Sympathetic, parasympathetic, and somatic", "Auditory, visual, and olfactory"],
    correct_answer: 1,
    explanation: "Balance is maintained through integration of three sensory systems: visual (sight), vestibular (inner ear), and somatosensory/proprioceptive (receptors in muscles, tendons, and joints sensing body position).",
    difficulty: "medium",
  },
  {
    chapter: 9,
    question: "Closing the eyes during a single-leg balance exercise primarily challenges which sensory input?",
    options: ["It eliminates vestibular input", "It removes visual input, forcing greater reliance on proprioceptive and vestibular systems", "It increases somatosensory input", "It has no effect on balance difficulty"],
    correct_answer: 1,
    explanation: "Closing the eyes removes visual input, forcing the body to rely more heavily on proprioceptive (somatosensory) and vestibular systems to maintain balance. This is an effective progression strategy.",
    difficulty: "medium",
  },
  {
    chapter: 9,
    question: "Strength-level balance exercises (Phases 2-4) progress by:",
    options: ["Reducing the challenge to make exercises easier", "Adding dynamic movement through a full range of motion while maintaining balance", "Eliminating all unstable surface training", "Only performing bilateral exercises"],
    correct_answer: 1,
    explanation: "Strength-level balance exercises add dynamic movement (like single-leg squats, lunges with reaches) through a full range of motion while maintaining balance. This progresses from the static holds of stabilization level.",
    difficulty: "medium",
  },
  {
    chapter: 9,
    question: "A 70-year-old client beginning an exercise program should have balance training prioritized because:",
    options: ["Older adults enjoy balance exercises more than strength training", "Fall prevention through improved proprioception and stability is critical for older adults", "Balance training replaces the need for cardiovascular exercise", "Balance training builds more muscle than resistance training"],
    correct_answer: 1,
    explanation: "Falls are a leading cause of injury and death in older adults. Balance training improves proprioception, reaction time, and stability, directly reducing fall risk and maintaining functional independence.",
    difficulty: "easy",
  },
  {
    chapter: 9,
    question: "Power-level balance exercises (Phase 5) include:",
    options: ["Static single-leg stands held for 60 seconds", "Hopping, bounding, and dynamic stabilization upon landing", "Slow bilateral movements on stable surfaces", "Seated balance exercises only"],
    correct_answer: 1,
    explanation: "Power-level balance exercises involve multiplanar, dynamic movements with controlled landing and stabilization. Examples include single-leg hop to stabilization and box jump-downs with hold.",
    difficulty: "medium",
  },
  {
    chapter: 9,
    question: "A client repeatedly loses balance to the right during single-leg stands on their left foot. This most likely indicates:",
    options: ["Strong left hip abductors", "Weakness or poor neuromuscular control of the left hip stabilizers (gluteus medius)", "Excessive flexibility in the right ankle", "Overactive left quadriceps"],
    correct_answer: 1,
    explanation: "Falling toward the unsupported side (right) during a left single-leg stand suggests the left hip abductors (primarily gluteus medius) are weak or poorly controlled, as they cannot stabilize the pelvis over the stance leg.",
    difficulty: "hard",
  },
  {
    chapter: 9,
    question: "Which of the following is the correct progression for balance training?",
    options: ["Unstable surface to stable surface to eyes closed", "Two legs stable, single leg stable, two legs unstable, single leg unstable", "Single leg unstable to two legs stable", "Only train balance on machines"],
    correct_answer: 1,
    explanation: "The correct balance progression reduces the base of support and/or stability: two legs on stable surface, single leg on stable surface, two legs on unstable surface, single leg on unstable surface. Additional progressions include closing eyes or adding movement.",
    difficulty: "easy",
  },

  // ============================================================
  // Chapter 10: Plyometric (Reactive) Training
  // ============================================================
  {
    chapter: 10,
    question: "The stretch-shortening cycle consists of which three phases?",
    options: ["Warm-up, work, cool-down", "Eccentric (loading), amortization (transition), concentric (unloading)", "Isometric, concentric, eccentric", "Acceleration, deceleration, stabilization"],
    correct_answer: 1,
    explanation: "The stretch-shortening cycle has three phases: eccentric (muscle lengthens and stores elastic energy), amortization (brief transition between eccentric and concentric), and concentric (muscle shortens and releases stored energy).",
    difficulty: "medium",
  },
  {
    chapter: 10,
    question: "The amortization phase of the stretch-shortening cycle should be:",
    options: ["As long as possible for maximum rest", "As short as possible to maximize power output", "At least 5 seconds", "Eliminated entirely for best results"],
    correct_answer: 1,
    explanation: "The amortization phase should be as short as possible. A prolonged amortization phase allows stored elastic energy to dissipate as heat, reducing the power output of the subsequent concentric phase.",
    difficulty: "medium",
  },
  {
    chapter: 10,
    question: "Plyometric training is most closely associated with which phase of the OPT model?",
    options: ["Phase 1 — Stabilization Endurance", "Phase 2 — Strength Endurance", "Phase 3 — Muscular Development", "Phase 5 — Power"],
    correct_answer: 3,
    explanation: "Plyometric (reactive) training is a key component of Phase 5 (Power) in the OPT model, designed to develop the ability to produce maximum force in the shortest time possible.",
    difficulty: "easy",
  },
  {
    chapter: 10,
    question: "A squat jump is an example of which type of plyometric exercise?",
    options: ["Stabilization level", "Strength level", "Power level", "Corrective level"],
    correct_answer: 2,
    explanation: "A squat jump is a power-level plyometric exercise involving a dynamic, explosive movement (jumping) as fast as possible. Stabilization-level exercises involve holding a landing, and strength-level exercises involve controlled repeated jumping.",
    difficulty: "medium",
  },
  {
    chapter: 10,
    question: "Which of the following is a stabilization-level reactive training exercise?",
    options: ["Box jump with maximum height", "Tuck jump", "Squat jump with hold upon landing", "Depth jump to broad jump"],
    correct_answer: 2,
    explanation: "A squat jump landing and holding the position (stabilization) is a stabilization-level reactive exercise. The emphasis is on landing mechanics and holding a stable position for 3-5 seconds, not explosive power.",
    difficulty: "easy",
  },
  {
    chapter: 10,
    question: "Before beginning plyometric training, a client should demonstrate:",
    options: ["The ability to bench press their body weight", "Adequate core strength, balance, and joint stability", "A VO2 max above 50 mL/kg/min", "The ability to run a 6-minute mile"],
    correct_answer: 1,
    explanation: "Plyometric training places high demands on the musculoskeletal system. Clients need adequate levels of core strength, balance, and joint stability (typically built in earlier OPT phases) before safely performing plyometrics.",
    difficulty: "easy",
  },
  {
    chapter: 10,
    question: "Reactive training exercises at the strength level are characterized by:",
    options: ["Landing and holding for 3-5 seconds", "Repeated jumps with controlled speed and moderate intensity", "Maximum effort single jumps", "Slow, controlled lowering movements only"],
    correct_answer: 1,
    explanation: "Strength-level reactive exercises involve dynamic, repeated movements with controlled speed. Examples include squat jumps and tuck jumps performed repetitively with moderate intensity and controlled landing.",
    difficulty: "medium",
  },
  {
    chapter: 10,
    question: "During a plyometric box jump, a client lands with their knees collapsing inward. The trainer should:",
    options: ["Increase the box height to challenge them more", "Continue the exercise since some compensation is normal", "Regress the exercise and address the knee valgus compensation with corrective strategies", "Add ankle weights to strengthen the legs"],
    correct_answer: 2,
    explanation: "Knee valgus during landing indicates poor neuromuscular control and potential injury risk. The trainer should regress the exercise, address the underlying compensation (overactive adductors, underactive glute med) with corrective exercise, and rebuild proper mechanics.",
    difficulty: "medium",
  },
  {
    chapter: 10,
    question: "The primary purpose of plyometric training is to:",
    options: ["Increase muscle size (hypertrophy)", "Improve muscular endurance", "Enhance the ability to generate maximum force in minimum time (power)", "Improve cardiovascular endurance"],
    correct_answer: 2,
    explanation: "Plyometric training develops power — the ability to produce maximum force as quickly as possible. It trains the neuromuscular system to utilize the stretch-shortening cycle more efficiently.",
    difficulty: "easy",
  },
  {
    chapter: 10,
    question: "A depth jump involves stepping off a box and immediately jumping upon landing. This exercise maximizes power by:",
    options: ["Allowing a long rest period between jumps", "Using gravity to increase the eccentric load, storing more elastic energy for a powerful concentric phase", "Reducing the demand on the joints", "Eliminating the need for the amortization phase"],
    correct_answer: 1,
    explanation: "The height of the box increases the eccentric load upon landing (more gravitational force). This stores more elastic energy in the muscles and tendons, which is rapidly released during the subsequent jump if the amortization phase is kept short.",
    difficulty: "hard",
  },
  {
    chapter: 10,
    question: "Which of the following best describes the progression of reactive training across OPT levels?",
    options: ["Power exercises first, then strength, then stabilization", "Stabilization (land and hold), strength (repeated jumps), power (explosive maximum effort)", "All levels use the same exercises at different speeds", "Reactive training only occurs in Phase 5"],
    correct_answer: 1,
    explanation: "Reactive training progresses from stabilization (land and hold for 3-5 seconds), to strength (repeated controlled jumps), to power (explosive, maximum-effort jumps). Each level builds on the neuromuscular control of the previous.",
    difficulty: "medium",
  },
  {
    chapter: 10,
    question: "A client performing ice skaters (lateral bounding) is training reactive ability primarily in which plane of motion?",
    options: ["Sagittal plane", "Frontal plane", "Transverse plane", "All planes equally"],
    correct_answer: 1,
    explanation: "Ice skaters (lateral bounds) involve side-to-side movement, which occurs primarily in the frontal (coronal) plane. This trains lateral reactive power and is important for sports involving cutting and lateral movement.",
    difficulty: "medium",
  },

  // ============================================================
  // Chapters 11-20: Existing questions preserved
  // ============================================================

  // Chapter 12
  {
    chapter: 12,
    question: "In OPT Phase 1 (Stabilization Endurance), what is the recommended rep range?",
    options: ["1-5 reps", "6-10 reps", "12-20 reps", "25-30 reps"],
    correct_answer: 2,
    explanation: "Phase 1 uses 12-20 reps with low intensity and a slow tempo (4/2/1) to build muscular endurance and stabilization. The focus is on proper form and neuromuscular control, not heavy loads.",
    difficulty: "easy",
  },
  {
    chapter: 12,
    question: "What tempo is recommended for Phase 1 (Stabilization Endurance) exercises?",
    options: ["1/0/1 (fast)", "2/0/2 (moderate)", "4/2/1 (slow eccentric)", "X/0/X (explosive)"],
    correct_answer: 2,
    explanation: "Phase 1 uses a 4/2/1 tempo: 4-second eccentric, 2-second isometric hold, 1-second concentric. The slow eccentric phase increases time under tension and demands more stabilization.",
    difficulty: "medium",
  },
  {
    chapter: 12,
    question: "A client who can perform 20 push-ups easily but shows poor scapular stability should start in which OPT phase?",
    options: ["Phase 2 — Strength Endurance", "Phase 3 — Muscular Development", "Phase 1 — Stabilization Endurance", "Phase 4 — Maximal Strength"],
    correct_answer: 2,
    explanation: "Regardless of strength levels, any client showing movement compensations or stability issues should start in Phase 1 to correct imbalances before progressing. Strength without stability leads to injury.",
    difficulty: "medium",
  },

  // Chapter 13
  {
    chapter: 13,
    question: "The OPT model consists of how many phases across how many levels?",
    options: ["3 phases, 2 levels", "5 phases, 3 levels", "4 phases, 4 levels", "6 phases, 3 levels"],
    correct_answer: 1,
    explanation: "The OPT model has 5 phases across 3 levels: Level 1 (Stabilization) = Phase 1, Level 2 (Strength) = Phases 2-4, Level 3 (Power) = Phase 5.",
    difficulty: "easy",
  },

  // Chapter 14
  {
    chapter: 14,
    question: "How many calories does one gram of fat provide?",
    options: ["4 calories", "7 calories", "9 calories", "11 calories"],
    correct_answer: 2,
    explanation: "Fat provides 9 calories per gram — more than double that of carbohydrates (4 cal/g) or protein (4 cal/g). This is why fat is the most calorie-dense macronutrient.",
    difficulty: "easy",
  },
  {
    chapter: 14,
    question: "Which component accounts for the largest portion of total daily energy expenditure (TDEE)?",
    options: ["Physical activity", "Thermic effect of food", "Basal metabolic rate (BMR)", "Non-exercise activity thermogenesis"],
    correct_answer: 2,
    explanation: "BMR accounts for approximately 70% of total daily energy expenditure. Physical activity accounts for ~20% and the thermic effect of food for ~10%.",
    difficulty: "medium",
  },

  // Chapter 17
  {
    chapter: 17,
    question: "For older adult clients, which training consideration is most important?",
    options: ["Maximize heavy lifting immediately", "Emphasize balance, stability, and functional movements", "Focus only on cardiovascular training", "Skip warm-ups to save time"],
    correct_answer: 1,
    explanation: "Older adults benefit most from programs emphasizing balance, stability, and functional movements that support activities of daily living and reduce fall risk. Always start with Phase 1 principles.",
    difficulty: "easy",
  },

  // Chapter 19
  {
    chapter: 19,
    question: "Which of the following is outside the scope of practice for a personal trainer?",
    options: ["Creating exercise programs", "Providing general nutrition information", "Diagnosing a client's knee pain", "Performing fitness assessments"],
    correct_answer: 2,
    explanation: "Personal trainers cannot diagnose injuries or medical conditions — that's the scope of licensed medical professionals. Trainers can refer clients to appropriate healthcare providers when needed.",
    difficulty: "easy",
  },
  {
    chapter: 19,
    question: "What is the purpose of the PAR-Q questionnaire?",
    options: ["Measure body composition", "Screen for potential health risks before exercise", "Assess cardiovascular fitness", "Determine training experience level"],
    correct_answer: 1,
    explanation: "The Physical Activity Readiness Questionnaire (PAR-Q) is a pre-participation screening tool that identifies individuals who may need medical clearance before starting an exercise program.",
    difficulty: "easy",
  },
];
