export type FunFact = {
  chapter: number;
  emoji: string;
  fact: string;
  chapter_label: string;
};

export const funFacts: FunFact[] = [
  {
    chapter: 1,
    emoji: "📊",
    fact: "Over 80% of gym-goers who start a new exercise program quit within the first 6 months. NASM-certified trainers are trained specifically in behavior-change strategies to beat that statistic.",
    chapter_label: "Ch 1 — The Modern State of Health and Fitness",
  },
  {
    chapter: 1,
    emoji: "💰",
    fact: "The U.S. fitness industry generates over $35 billion annually, yet nearly 70% of American adults are still classified as overweight or obese.",
    chapter_label: "Ch 1 — The Modern State of Health and Fitness",
  },
  {
    chapter: 1,
    emoji: "🏥",
    fact: "Physical inactivity is now identified as the fourth leading risk factor for global mortality, responsible for roughly 3.2 million deaths each year.",
    chapter_label: "Ch 1 — The Modern State of Health and Fitness",
  },
  {
    chapter: 2,
    emoji: "🦴",
    fact: "Your skeletal system completely replaces itself roughly every 10 years. Weight-bearing exercise accelerates this remodeling, which is why resistance training helps prevent osteoporosis.",
    chapter_label: "Ch 2 — Basic Exercise Science",
  },
  {
    chapter: 2,
    emoji: "⚡",
    fact: "A single muscle fiber can contract in as little as 5 milliseconds, yet the brain coordinates millions of fibers simultaneously just to pick up a coffee cup.",
    chapter_label: "Ch 2 — Basic Exercise Science",
  },
  {
    chapter: 2,
    emoji: "🔬",
    fact: "The sarcomere, the smallest functional unit of muscle contraction, is only about 2 micrometers long — yet it's the engine behind every squat, sprint, and deadlift you'll ever do.",
    chapter_label: "Ch 2 — Basic Exercise Science",
  },
  {
    chapter: 3,
    emoji: "🧠",
    fact: "Your nervous system can transmit signals at up to 270 mph. That's faster than a Formula 1 car and is why you can catch a ball before you consciously decide to.",
    chapter_label: "Ch 3 — The Nervous, Skeletal, and Muscular Systems",
  },
  {
    chapter: 3,
    emoji: "💪",
    fact: "The gluteus maximus is the largest muscle in the human body, yet most people can't activate it properly due to prolonged sitting — a phenomenon trainers call 'gluteal amnesia.'",
    chapter_label: "Ch 3 — The Nervous, Skeletal, and Muscular Systems",
  },
  {
    chapter: 3,
    emoji: "🦵",
    fact: "The Achilles tendon can withstand forces up to 1,000 pounds during running. It's the strongest tendon in the body, yet also one of the most commonly injured.",
    chapter_label: "Ch 3 — The Nervous, Skeletal, and Muscular Systems",
  },
  {
    chapter: 4,
    emoji: "🏃",
    fact: "Your body stores only about 90 seconds worth of ATP at any given time. Every energy system you learn about in exercise science exists because the body must constantly remake this molecule.",
    chapter_label: "Ch 4 — The Cardiorespiratory, Endocrine, and Digestive Systems",
  },
  {
    chapter: 4,
    emoji: "❤️",
    fact: "A trained endurance athlete's heart can pump up to 40 liters of blood per minute — double that of an untrained person. The heart literally remodels itself in response to cardio training.",
    chapter_label: "Ch 4 — The Cardiorespiratory, Endocrine, and Digestive Systems",
  },
  {
    chapter: 4,
    emoji: "🧪",
    fact: "Growth hormone secretion spikes up to 700% during deep sleep. This is why sleep is considered just as important as training for muscle growth and recovery.",
    chapter_label: "Ch 4 — The Cardiorespiratory, Endocrine, and Digestive Systems",
  },
  {
    chapter: 5,
    emoji: "🧬",
    fact: "Muscle tissue burns about 6 calories per pound per day at rest, while fat burns only 2. Adding 10 pounds of muscle raises your resting metabolism by roughly 40 calories daily.",
    chapter_label: "Ch 5 — Human Movement Science",
  },
  {
    chapter: 5,
    emoji: "⚖️",
    fact: "The body's center of gravity shifts constantly during movement. NASM's movement system model explains how the kinetic chain must adjust in real time to maintain balance.",
    chapter_label: "Ch 5 — Human Movement Science",
  },
  {
    chapter: 6,
    emoji: "🔗",
    fact: "Fascia — the connective tissue wrapping every muscle — can generate up to 2,000 pounds of tensile force per square inch. Foam rolling targets this tissue to improve movement quality.",
    chapter_label: "Ch 6 — Fitness Assessment",
  },
  {
    chapter: 6,
    emoji: "🦶",
    fact: "During the overhead squat assessment, if someone's knees cave inward, it often indicates weak glutes — not a knee problem. The real dysfunction is usually far from where the symptom appears.",
    chapter_label: "Ch 6 — Fitness Assessment",
  },
  {
    chapter: 6,
    emoji: "📐",
    fact: "The overhead squat assessment can reveal compensations in all five major kinetic chain checkpoints in under 30 seconds, making it one of the most efficient movement screens available.",
    chapter_label: "Ch 6 — Fitness Assessment",
  },
  {
    chapter: 7,
    emoji: "🧘",
    fact: "Static stretching before explosive activity can temporarily reduce power output by up to 30%. That's why NASM recommends dynamic stretching before workouts and static stretching after.",
    chapter_label: "Ch 7 — Flexibility Training Concepts",
  },
  {
    chapter: 7,
    emoji: "🤸",
    fact: "The Golgi tendon organ, a tiny receptor in your tendons, is the reason you can relax deeper into a stretch after holding it for 30 seconds. It literally overrides your muscle's protective tension.",
    chapter_label: "Ch 7 — Flexibility Training Concepts",
  },
  {
    chapter: 8,
    emoji: "🏋️",
    fact: "Resistance training increases bone density more effectively than any supplement. Wolff's Law states that bone remodels along the lines of mechanical stress placed upon it.",
    chapter_label: "Ch 8 — Cardiorespiratory Fitness Training",
  },
  {
    chapter: 8,
    emoji: "🫀",
    fact: "EPOC (excess post-exercise oxygen consumption) can elevate your metabolism for up to 38 hours after a high-intensity workout. Your body is literally burning extra calories while you recover.",
    chapter_label: "Ch 8 — Cardiorespiratory Fitness Training",
  },
  {
    chapter: 9,
    emoji: "🎯",
    fact: "The core is not just your 'abs.' It includes 29 muscles that attach to the lumbo-pelvic-hip complex, and it activates milliseconds before any limb movement to stabilize the spine.",
    chapter_label: "Ch 9 — Core Training Concepts",
  },
  {
    chapter: 9,
    emoji: "🌀",
    fact: "The transverse abdominis — the deepest core muscle — acts like a natural weight belt. Learning to activate it properly is the foundation of NASM's core training approach.",
    chapter_label: "Ch 9 — Core Training Concepts",
  },
  {
    chapter: 10,
    emoji: "⚖️",
    fact: "Balance training improves reaction time in athletes by up to 20%. Your proprioceptors — tiny sensors in joints and muscles — get sharper the more you challenge them on unstable surfaces.",
    chapter_label: "Ch 10 — Balance Training Concepts",
  },
  {
    chapter: 10,
    emoji: "🧍",
    fact: "Even standing on one foot with your eyes closed activates over 100 muscles simultaneously. Balance is one of the most neurologically demanding types of exercise.",
    chapter_label: "Ch 10 — Balance Training Concepts",
  },
  {
    chapter: 11,
    emoji: "🏈",
    fact: "Plyometric training can improve vertical jump height by 5-10% in just 6 weeks. The stretch-shortening cycle it trains is what separates explosive athletes from everyone else.",
    chapter_label: "Ch 11 — Plyometric (Reactive) Training Concepts",
  },
  {
    chapter: 11,
    emoji: "🦘",
    fact: "During a depth jump, your tendons store and release elastic energy like a spring — producing more force than your muscles could generate on their own through pure contraction.",
    chapter_label: "Ch 11 — Plyometric (Reactive) Training Concepts",
  },
  {
    chapter: 12,
    emoji: "💥",
    fact: "Speed is a skill, not just a genetic gift. Sprint mechanics can be coached, and proper arm drive alone can improve 40-yard dash times by 0.1-0.2 seconds.",
    chapter_label: "Ch 12 — Speed, Agility, and Quickness Training",
  },
  {
    chapter: 12,
    emoji: "🔄",
    fact: "During a rapid change of direction, your body can experience forces up to 5 times your body weight. Agility training prepares your joints and muscles to handle these extreme loads safely.",
    chapter_label: "Ch 12 — Speed, Agility, and Quickness Training",
  },
  {
    chapter: 13,
    emoji: "📈",
    fact: "Beginners can gain strength by up to 40% in the first 2-3 months of training, mostly from neural adaptations — the muscles barely change size, but the brain gets dramatically better at using them.",
    chapter_label: "Ch 13 — Resistance Training Concepts",
  },
  {
    chapter: 13,
    emoji: "🔁",
    fact: "The NASM OPT model uses three training phases (stabilization, strength, power) because periodization prevents plateaus. The body adapts to any single stimulus within 4-6 weeks.",
    chapter_label: "Ch 13 — Resistance Training Concepts",
  },
  {
    chapter: 13,
    emoji: "🪢",
    fact: "Eccentric (lowering) contractions cause more muscle damage than concentric ones, which is why you're more sore from walking downhill than uphill. This damage is actually the stimulus for growth.",
    chapter_label: "Ch 13 — Resistance Training Concepts",
  },
  {
    chapter: 14,
    emoji: "🏗️",
    fact: "The NASM OPT model was designed as a systematic progression. It's one of the few training models backed by peer-reviewed research and is used by over 1.4 million certified professionals.",
    chapter_label: "Ch 14 — The Optimum Performance Training (OPT) Model",
  },
  {
    chapter: 14,
    emoji: "📊",
    fact: "Phase 1 of the OPT model (stabilization endurance) uses high reps, slow tempos, and unstable surfaces. Most trainers skip it, but it builds the joint stability foundation that prevents injuries in later phases.",
    chapter_label: "Ch 14 — The Optimum Performance Training (OPT) Model",
  },
  {
    chapter: 15,
    emoji: "🍎",
    fact: "A pound of body fat stores about 3,500 calories of energy. But metabolism isn't simple math — hormones, NEAT, and the thermic effect of food all influence whether a calorie surplus becomes fat or muscle.",
    chapter_label: "Ch 15 — Nutrition",
  },
  {
    chapter: 15,
    emoji: "💧",
    fact: "Just 2% dehydration can decrease exercise performance by up to 25%. Thirst is a lagging indicator — by the time you feel thirsty, performance has already declined.",
    chapter_label: "Ch 15 — Nutrition",
  },
  {
    chapter: 15,
    emoji: "🥩",
    fact: "Protein has the highest thermic effect of any macronutrient — your body burns 20-30% of protein calories just digesting it, compared to only 5-10% for carbs and 0-3% for fats.",
    chapter_label: "Ch 15 — Nutrition",
  },
  {
    chapter: 16,
    emoji: "🧴",
    fact: "Creatine is one of the most researched supplements in history with over 500 studies. It's proven to increase strength and power, yet many people still believe myths about it being dangerous.",
    chapter_label: "Ch 16 — Supplementation",
  },
  {
    chapter: 16,
    emoji: "☕",
    fact: "Caffeine can improve endurance performance by 3-5% and increase strength output. It works by blocking adenosine receptors in the brain, delaying the perception of fatigue.",
    chapter_label: "Ch 16 — Supplementation",
  },
  {
    chapter: 17,
    emoji: "🗣️",
    fact: "Research shows that motivational interviewing — asking open-ended questions instead of giving direct advice — is 80% more effective at driving long-term behavior change in clients.",
    chapter_label: "Ch 17 — Behavioral Coaching",
  },
  {
    chapter: 17,
    emoji: "🎯",
    fact: "The 'stages of change' model reveals that most new clients aren't in the 'action' stage yet. Pushing someone to act before they're mentally ready is the number-one cause of dropout.",
    chapter_label: "Ch 17 — Behavioral Coaching",
  },
  {
    chapter: 18,
    emoji: "🤰",
    fact: "Pregnant women who exercise regularly have 50% lower rates of gestational diabetes and shorter labor durations on average. Exercise during pregnancy is not just safe — it's recommended.",
    chapter_label: "Ch 18 — Special Populations",
  },
  {
    chapter: 18,
    emoji: "👴",
    fact: "After age 30, adults lose 3-8% of muscle mass per decade if they don't resistance train. This age-related muscle loss (sarcopenia) is now considered a clinical condition.",
    chapter_label: "Ch 18 — Special Populations",
  },
  {
    chapter: 18,
    emoji: "🫁",
    fact: "People with hypertension should avoid the Valsalva maneuver (holding breath during lifts) because it can spike blood pressure above 300/200 mmHg momentarily.",
    chapter_label: "Ch 18 — Special Populations",
  },
  {
    chapter: 19,
    emoji: "📋",
    fact: "NASM recommends reassessing clients every 4-6 weeks. Without regular assessments, trainers can't objectively prove progress — and clients who don't see measurable results are more likely to quit.",
    chapter_label: "Ch 19 — Program Design",
  },
  {
    chapter: 19,
    emoji: "⏱️",
    fact: "The ideal rest period between sets depends entirely on the training goal: 0-90 seconds for endurance, 1-2 minutes for hypertrophy, and 3-5 minutes for maximal strength.",
    chapter_label: "Ch 19 — Program Design",
  },
  {
    chapter: 20,
    emoji: "🤝",
    fact: "Personal trainers who follow up with clients within 24 hours of a missed session retain those clients at 3x the rate. The business of training is just as important as the science.",
    chapter_label: "Ch 20 — The Fitness Professional",
  },
  {
    chapter: 20,
    emoji: "📱",
    fact: "The average personal trainer retains a client for only 3-6 months. Those who use systematic progress tracking and goal-setting extend retention to over 12 months on average.",
    chapter_label: "Ch 20 — The Fitness Professional",
  },
  {
    chapter: 5,
    emoji: "🦿",
    fact: "Your body uses three types of levers to move. Your jaw is a third-class lever, your elbow is a first-class lever, and rising onto your toes uses a second-class lever — all working like simple machines.",
    chapter_label: "Ch 5 — Human Movement Science",
  },
  {
    chapter: 8,
    emoji: "🫁",
    fact: "VO2 max — the gold standard of cardiovascular fitness — can be improved by 15-20% with consistent training. Elite endurance athletes have VO2 max values nearly double those of sedentary adults.",
    chapter_label: "Ch 8 — Cardiorespiratory Fitness Training",
  },
];
